### ISSUE TITLE
Font detection and selection with eulervm?

### ISSUE THREAD

**Issue by josephwright** [josephwright/siunitx#195]
[Reported by [Michael Forbes](https://bitbucket.org/mforbes)]

I am finding the font selection and detection mechanism very difficult to figure out, but I am not sure if this is a bug or simply documentation errors.

I am using the following test

```
\documentclass{article}
\usepackage[osf]{mathpazo}
\usepackage[euler-digits]{eulervm}
\usepackage{siunitx}
\newcommand{\ssitest}{
  \def\x{\SI{13.46}{fm}}
  \begin{itemize}
  \item Text (normal, bold, italic, bold-italic, mono-space, sans-serif,
    small-caps):\\
    \x, \textbf{\x}, \textit{\x}, \textbf{\textit{\x}}, \texttt{\x}, \textsf{\x}, \textsc{\x}. 
  \item Math (normal, bold, italic, bold-italic, mono-space, sans-serif):\\ 
    $\x$, $\mathbf{\x}$, $\mathit{\x}$, $\mathbf{\mathit{\x}}$, $\mathtt{\x}$, $\mathsf{\x}$.
  \item Display math:
    \[\x, \mathbf{\x}, \mathit{\x}, \mathbf{\mathit{\x}}, \mathtt{\x}, \mathsf{\x}.\]
  \end{itemize}
}
\newcommand{\sitest}{
  {\ssitest}
  Now with sans-serif body fonts.
  {\sffamily\ssitest}
}
\begin{document}
```

This document demonstrates the use of fonts with the `\texttt{siunitx}` package. The body fonts are Palatino with old-style figures (1234567890) while the math fonts are Euler `$(1234567890)$`.
1. The documentation states that "By default, all text is typeset in the current upright, serif math font." When I issue: `{\sitest}` however, everything is typeset in Palatino osf figures - the text font, not the math font (Euler).
2. I can't seem to figure out how to get `siunitx` to detect that it is in math mode, and then to use Euler. I have tried many combinations of mode detection, but unless I change the text font to Euler, or explicitly set `math-rm` to use Euler, I cannot get auto-detection to work. Is this by design, or am I missing something, or is there a problem with using `eulervm`?

Edit: Okay. If I kill `\usepackage{eulervm}` then the math font is used as in the documentation, so this is somehow related to a problem with `eulervm`. Michael.

**Comment by gpcf** [comment]
How do I make siunitx not use the euler font, but the `\mathrm` font instead?
