### ISSUE TITLE
Merging \numlist and \numrange into \num

### ISSUE THREAD

**Issue by josephwright** [josephwright/siunitx#210]
From an e-mail

> I want to write ranges in lists of numbers. For example, I want to get the output 1.2, `3.4--5.6`, `7.8--9.0` with the input `\num{1.2;3.4~5.6;7.8~9.0}`. I used `~` instead of `--` because the parser might confuse `--` with minus sign. I need this feature because I often write sentences like: ...five protons (`\delta 7.24, 6.98--6.8`0) were observed in aromatic region....

**Comment by eg9** [comment]
I'd go with a different command, too.

**Comment by josephwright** [comment]
OK, these are semantically different ideas: I'm closing WONTFIX.
