### ISSUE TITLE
"number-unit-product" should default to a full space

### ISSUE THREAD

**Issue by josephwright** [josephwright/siunitx#230]
As pointed out in http://tex.stackexchange.com/questions/127817/how-much-space-between-number-and-unit/127827#comment287535_127817, the SI docs say that the number-unit product should be a full space. This is a 'breaking' if small change.

**Comment by mhchem** [comment]
See my counter-argument at http://tex.stackexchange.com/a/324137/73371 that the SI doc says anything about the with of the space between quantity and unit.
