### ISSUE TITLE
Comparators appear in numerator of fractions

### ISSUE THREAD

**Issue by EdwinChan** [josephwright/siunitx#237]
... whereas `\sim\frac12` seems more desirable. Minimum example:

```
\documentclass{article}
\usepackage{amsmath}
\usepackage[quotient-mode=fraction]{siunitx}
\begin{document}
\sisetup{fraction-function=\frac}\num{\sim1/2}
\sisetup{fraction-function=\dfrac}\num{\sim1/2}
\sisetup{fraction-function=\tfrac}\num{\sim1/2}
\end{document}
```

Probably not related, but it's not possible to set `fraction-function` in the preamble.

**Edit**:

The last point was confusing. What I meant is simply that the following is not valid:

```
\documentclass{article}
\usepackage{amsmath}
\usepackage[quotient-mode=fraction,fraction-function=\frac]{siunitx}
\begin{document}
\num{1/2}
\end{document}
```

In my limited knowledge, I assume it's due to `\frac` being expanded.

**Comment by josephwright** [comment]
I'm not carrying the quotients idea forward to v3, so I'm closing here.
