### ISSUE TITLE
Notation error for small uncertainties

### ISSUE THREAD

**Issue by tvwerkhoven** [josephwright/siunitx#242]
For uncertainties smaller than the smallest significant digit specified in the value, the uncertainty is printed wrongly, i.e.

```
\num{12.3 +- 6}       -> 12.3 +- 6.0
\num{12.3 +- 0.6}     -> 12.3 +- 0.6
\num{12.3 +- 0.06}    -> 12.30 +- 0.06
\num{12.3 +- 0.006}   -> 12.30 +- 0.06
```

The last line is wrong, I expect

```
\num{12.3 +- 0.006}   -> 12.300 +- 0.006
```

I am using version 2.5q from MacTeX 2013.

**Comment by josephwright** [comment]
Fixed in v3.
