### ISSUE TITLE
tabular numbers with separated uncertainty

### ISSUE THREAD

**Issue by migueldvb** [josephwright/siunitx#244]
I would like to format the space reserved for a number shown in a table with separated uncertainty. It seems that when I use the table-format option the brackets around the mantissa disappear. This is reported at
http://tex.stackexchange.com/questions/147801/siunitx-tabular-numbers-with-separated-uncertainty

**Comment by mjayvizzle** [comment]
It would be great if this issue could be fixed. At the moment, there is no method to reserve the right amount of space for this kind of number formats. The workaround proposed (https://tex.stackexchange.com/questions/147801/siunitx-tabular-numbers-with-separated-uncertainty) does not reserve the right amount of space, so this doesn't solve anything...

**Comment by josephwright** [comment]
Fixed in v3 (development) - release likely in the summer/autumn.
