### ISSUE TITLE
Automatic per-mode switch from symbol to reciprocal

### ISSUE THREAD

**Issue by biozic** [josephwright/siunitx#252]
I think there could be a way to make the package output a unit with a single slash using `per-mode=symbol` and fallback to `per-mode=reciprocal` when there is more than one slash:

``` LaTeX
\documentclass{article}
\usepackage{siunitx}
% ... options ...
\begin{document}
\SI{1}{\metre\per\second}            % would output 1 m/s
\SI{1}{\ampere\per\metre\per\second} % would output 1 A m-1 s-1
\end{document}
```

See TeX.SX question http://tex.stackexchange.com/questions/184043/automatic-per-mode-switch-from-symbol-to-reciprocal.

**Comment by porglezomp** [comment]
I just came looking for this today, I'd really like to have this.

**Comment by josephwright** [comment]
I see how to do this: count up the number of negative powers before formatting, then alter the formatting approach. I'll need a name for the setting.

**Comment by josephwright** [comment]
I have a way to do this, it's really a question now of an option name.

**Comment by josephwright** [comment]
Option added, hopefully the naming is OK

**Comment by biozic** [comment]
This looks very good and the naming is OK for me. Excellent work, thank you.
