### ISSUE TITLE
Wrong number of decimal places with +- notation for uncertainty.

### ISSUE THREAD

**Issue by agusdallalba** [josephwright/siunitx#261]
Minimal example:

``` TeX
\documentclass{article}
\usepackage{siunitx}

\begin{document}
\num{1+-0.02}
\end{document}
```

Expected result: 1.00(2), or 1.00 ± 0.02 with separate-uncertainty = true.

Actual result: 1.0(2), or 1.0 ± 0.2 with separate-uncertainty = true.

**Comment by tacruc** [comment]
I think i got the same problem
```
\usepackage{siunitx}
\sisetup{separate-uncertainty}
\SI{5800\pm200}{\kelvin}
```
Expected result: (5800±200) K
Actual result: (5800.0±20.0) K

**Comment by josephwright** [comment]
Fixed in upcoming v3.
