### ISSUE TITLE
range commands to have a different bracket style

### ISSUE THREAD

**Issue by hollandjg** [josephwright/siunitx#262]
It's sometimes required that ranges are typeset using square brackets, but that other brackets be round. Is it possible to add an option so that the \SIrange bracket characters can be specified without affecting any other bracket style?

**Comment by josephwright** [comment]
In v3, I've split all the brackets internally, but at the moment nothings exposed for the user. I guess my question is how this interacts with brackets needed to avoid ambiguous numbers. I'll put this one down for v3.2 - it's an interface question, mainly.

**Comment by hollandjg** [comment]
Awesome! Thanks @josephwright!
