### ISSUE TITLE
Conflict with [luatexja-ruby] (luatex): "ERROR: Missing number, treated as zero."

### ISSUE THREAD

**Issue by Araeos** [josephwright/siunitx#263]
# Reproduction

Compiling this with the luatex engine explains the bug.

    \documentclass[a4paper]{article}
    % Shows a bug using siunitx with luatexja-ruby in which \num{41} does
    % not produce "41" but instead "0=41" along with the error message
    % "ERROR: Missing number, treated as zero."
    %
    % Tex-live version: TeX 3.14159265 (TeX Live 2014/Arch Linux)
    %                   kpathsea version 6.2.0
    \usepackage{siunitx}
    % Enable japanese support.
    \usepackage{luatexja-preset}
    % The ruby command that sets small furigana text over other text
    % (japanese kanji normally).
    \usepackage{luatexja-ruby}

    % Optionally select japense fonts.
    \setmainjfont{IPA Mincho} % \mcfamily
    \setsansjfont{IPA Gothic} % \gtfamily

    \begin{document}
        \ruby{日本}{これはにほんご}

        1. This adds an faulty zero: \num{5}, \num{9}\\
        2. The next one works again: \num{5}, \num{9}
        
        \ruby{日本}{これはにほんご}\\
        3. Directly in the same paragraph does not show the bug: \num{5}, \num{9}
        
        4. But directly after the paragraph is buggy: \num{5}, \num{9}
        
        5. Afterwards is no problem \num{5}, \num{9}
    \end{document}

# Description

I expect \num{x} to just print the number x, but at least on my system it prints 0=x (where x is a number) along with error messages.

The fonts can be changed or commented out if they don't show correctly.

I don't know whether the luatexja-ruby package is at fault or not but I am promoting awareness if nothing else.

EDIT: The issue does not occur when the second argument to \ruby is short. For example \ruby{日本}{にほん} is short enough to not produce any errors on my system.

**Comment by josephwright** [comment]
This is definitely works for me, sorry.
