### ISSUE TITLE
retain-unity-mantissa after rounding

### ISSUE THREAD

**Issue by neapel** [josephwright/siunitx#265]
It seems the unity mantissa is currently discarded **before** rounding:

``` latex
\sisetup{round-mode=figures, retain-unity-mantissa=false, scientific-notation=true}
\num{1e9} renders $10^9$
but \num[round-precision=1]{1.0e9}, \num[zero-decimal-to-integer=true]{1.0e9},
\num{1000000000} and \num{0.1e10} render $1\times 10^9$
```

It would be nice to have an option to also discard any unity mantissa produced **after** rounding, so that the above examples all render as `$10^9$`

(I'm creating a plot using PGF, `\pgfmathprintnumber` doesn't have this functionality at all; so I redefined it as `\num`, but it's being passed strings like `1.0e0` and `1.0e9` for log axis labels; that `.0` over which I have no control prevents discarding the mantissa)

**Comment by neapel** [comment]
Maybe related, if there's an explicit zero exponent the mantissa gets discarded, but the exponent isn't printed either (not even with scientific-notation), rendering nothing:

```latex
\sisetup{retain-unity-mantissa=false}
(\num{1}) got (1) expected (1) -- ok,
(\num{1e0}) got () expected (1) -- weird,
```

**Comment by josephwright** [comment]
This is sorted in v3: I'm moving the option to `print-unity-mantissa`, explicitly coming after processing.
