### ISSUE TITLE
Math symbol in SI unit declaration

### ISSUE THREAD

**Issue by migueldvb** [josephwright/siunitx#266]
It used to be possible to include a math symbol in a SI unit declaration as in this example
```
\DeclareSIUnit\msunyr{{$M_\odot$}\,yr^{-1}}
```
But since upgrading to siunitx 2015/01/21 v2.6e this unit gives the error:
```
! Missing } inserted.
<inserted text> 
                }
l.303 ... {(\si{\km\per\s})} & {(\si{\msunyr})} \\
```
`\ensuremath` works but the symbol is displayed in non-italic mode.
```
\DeclareSIUnit\msunyr{\ensuremath{M_\odot}\,yr^{-1}}
```
Is it possible to include math notation in a new unit declaration?

**Comment by josephwright** [comment]
An odd looking unit, but it should work with `\ensuremath`:
```latex
\documentclass{article}
\usepackage{siunitx}
\DeclareSIUnit\msunyr{\ensuremath{M_\odot}\,yr^{-1}}
\begin{document}
\si{\msunyr}
\end{document}
```

**Comment by josephwright** [comment]
I've thought about this: I've always been clear that `\ensuremath` is needed to force math mode, so the use of `$` is not supported.
