### ISSUE TITLE
! Undefined control sequence. \__siunitx_font_weight: ->\lseries 

### ISSUE THREAD

**Issue by tudscr** [josephwright/siunitx#268]
If `\seriesdefault`was set to `l` the package tries to use `\lseries` but this command is not provided by any class or package ASAIK.
```latex
    \documentclass{article}
    \usepackage{siunitx}
    \sisetup{detect-all}
    \def\seriesdefault{l}
    \begin{document}
    % the command \lseries is not defined
    \SI{-1984}{m^{-42}}
    \end{document}
```

**Comment by josephwright** [comment]
This looks STATUS BYDESIGN to me. It's not expected that users will set `\seriesdefault` themselves rather that if a font uses `l` series that `siunitx` can work with it. Such examples do exist.

**Comment by tudscr** [comment]
Actually, I'm providing such a package. The only example I found so far is `drm.sty` I can deal with this issues by simple adding

    \AfterPackage*{siunitx}{%
      \providecommand*\lseries{\fontseries{l}\selectfont}
    }

to my font package.
