### ISSUE TITLE
Number too big. scientific-notation=true

### ISSUE THREAD

**Issue by big-r81** [josephwright/siunitx#272]
Hi,

I'm getting an error if i use numbers with more than 9 digits.
 
The MWE is:

```
\documentclass{article}
\usepackage{siunitx}

\begin{document}
	\num[round-precision=3,round-mode=figures,scientific-notation=true]{9999999999}	
\end{document}
```
siunitx version: 2.6g (revision 37680)
Tex verion: MacTex 2015

So, whats wrong?

Cheers,
Ronny

**Comment by josephwright** [comment]
This is fixed in the latest release :-)

**Comment by big-r81** [comment]
Thanks. Great! ;-)
