### ISSUE TITLE
let number-color only color the number and not the power. 

### ISSUE THREAD

**Issue by Tchiller** [josephwright/siunitx#275]
`\SI[number-color=red]{1}{\square\metre}`  results in a coloured 2. I have to do`{\color{red}\SI[unit-color=black]{1}{\square\metre}}` or`\SI[power-font=unit,number-color=red]{1}{\square\metre}` in order to get that right. 

I know, this is already known to you, but in order to have it tracked here, I post it anyway. 

Kind regards and thanks!

**Comment by josephwright** [comment]
You want `\sisetup{power-font  = unit}`.
