### ISSUE TITLE
add-integer-zero=false ignored with scientific-notation=fixed

### ISSUE THREAD

**Issue by PhilippWendler** [josephwright/siunitx#276]
With the options `add-integer-zero=false, scientific-notation=fixed` I would expect both `\num{.1}` and `\num{1e-1}` to print `.1`, but the actual result is `0.1`.

**Comment by josephwright** [comment]
I've thought about this: I feel this is 'by design'. The `add-integer-zero=false` option is really about the users literal input: once you start post-processing then more normalisation is to be expected.

**Comment by PhilippWendler** [comment]
This means that there is no way to achieve an output of `.1` if the input is in scientific notation with siunitx?

**Comment by josephwright** [comment]
At present no. I'm always happy to look again at things if you can point to a good use case.

**Comment by howalpert** [comment]
I have been struggling with this as an inexperienced user, and perhaps can present a good case.

When writing in APA style, statistics without an integer zero unless it is possible for the number to exceed (absolute value of) 1.0.

Several statistics cannot exceed 1.0, notably correlations (e.g., _r_, Pearson-product moment correlation) and _p_ (probability).

I calculate my statistics in R and use them in LaTex via knitr. A typical sentence might include

($R^2 = \num[add-integer-zero = false]{\Sexpr{sy_lm_dec_pa_ran_ef.r2}}$, $\Delta R^2 = \num[add-integer-zero = false]{\Sexpr{delta_lm_dec_pa_ran_vs_ef}}$, $F[\num{\Sexpr{hr_lm_dec_pa_ran_vs_ef.df1}}, \num{\Sexpr{hr_lm_dec_pa_ran_vs_ef.df2}}] = \num[round-precision = 1]{\Sexpr{hr_lm_dec_pa_ran_vs_ef.f}},$ $p = \num[add-integer-zero = false]{\Sexpr{hr_lm_dec_pa_ran_vs_ef.p}}$)

It would print as
(R2 = 0.54, R2 = 0.01, F[1, 56] = 1.8, p = 0.18)

But it should print as
(R2 = .54, R2 = .01, F[1, 56] = 1.8, p = .18)

Your consideration of this or advice on available fixes would be most appreciated.

How
