### ISSUE TITLE
Cannot declare molar units

### ISSUE THREAD

**Issue by Aryanix** [josephwright/siunitx#279]
I am trying to overwrite the small cap on `\Molar` to be a normal cap M and I cannot seem to change it.  I have tried:
```latex
\DeclareSIUnit[]\Molar{M}
\DeclareSIUnit{\Molar}{M}
\DeclareSIUnit{\Molar}{\textup{M}}
```
I even tried to change \molar to M using the same methods and it doesn't change it from it's default.

Is the `\DeclareSIUnit` not working on these units or am I doing it wrong?

**Comment by josephwright** [comment]
'Out of the box' `\Molar` is not defined, and the above should all work. Can you add an example of your input, including `\listfiles`, and also what you get in the log for a `File list`?

**Comment by Aryanix** [comment]
I am still really new to LaTeX, so I hope this is what you asked for.

\documentclass[12pt]{article}

\usepackage{times} 
\usepackage{parskip} 
\usepackage{graphicx}
\usepackage{array} 
\usepackage{booktabs} 
\usepackage[paper=letterpaper, margin=1in, nohead, pdftex]{geometry} 
\usepackage{tikz, pgfplots} 
\usepackage{caption, subcaption} 
\usepackage{todonotes}
\usepackage{fancyref}
\usepackage{chemmacros} 
\usepackage[version=4]{mhchem} 
\usepackage{siunitx} 

\pgfplotsset{ every non boxed x axis/.append style={x axis line style=-}, every non boxed y axis/.append style={y axis line style=-}} 
\pgfplotsset{every tick label/.append style={font=\small}} 
\pgfplotsset{every axis label/.append style={font=\small}} 
\pgfplotsset{every axis legend/.append style={font=\small}} 

\presetkeys{todonotes}{inline, size=\tiny, color=green!50}{} 

\newcommand{\FeIII}{\ox[pos=super]{3, Fe}}

\sisetup{detect-all}
\DeclareSIUnit{\litre}{L}

\listfiles

\begin{document}

\SI{0.1}{\Molar} \ce[CaCl2]

\end{document}

*File List*
 article.cls    2014/09/29 v1.4h Standard LaTeX document class
  size12.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
   times.sty    2005/04/12 PSNFSS-v9.2a (SPQR) 
 parskip.sty    2001/04/09 non-zero parskip adjustments
graphicx.sty    2014/10/28 v1.0g Enhanced LaTeX Graphics (DPC,SPQR)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
graphics.sty    2014/10/28 v1.0p Standard LaTeX Graphics (DPC,SPQR)
    trig.sty    1999/03/16 v1.09 sin cos tan (DPC)
graphics.cfg    2010/04/23 v1.9 graphics configuration of TeX Live
  pdftex.def    2011/05/27 v0.06d Graphics/color for pdfTeX
infwarerr.sty    2010/04/08 v1.3 Providing info/warning/error messages (HO)
 ltxcmds.sty    2011/11/09 v1.22 LaTeX kernel commands for general use (HO)
   array.sty    2014/10/28 v2.4c Tabular extension package (FMi)
booktabs.sty    2005/04/14 v1.61803 publication quality tables
geometry.sty    2010/09/12 v5.6 Page Geometry
   ifpdf.sty    2011/01/30 v2.3 Provides the ifpdf switch (HO)
  ifvtex.sty    2010/03/01 v1.5 Detect VTeX and its facilities (HO)
 ifxetex.sty    2010/09/12 v0.6 Provides ifxetex conditional
    tikz.sty    2013/12/13 v3.0.0 (rcs-revision 1.142)
     pgf.sty    2013/12/18 v3.0.0 (rcs-revision 1.14)
  pgfrcs.sty    2013/12/20 v3.0.0 (rcs-revision 1.28)
everyshi.sty    2001/05/15 v3.00 EveryShipout Package (MS)
  pgfrcs.code.tex
 pgfcore.sty    2010/04/11 v3.0.0 (rcs-revision 1.7)
  pgfsys.sty    2013/11/30 v3.0.0 (rcs-revision 1.47)
  pgfsys.code.tex
pgfsyssoftpath.code.tex    2013/09/09  (rcs-revision 1.9)
pgfsysprotocol.code.tex    2006/10/16  (rcs-revision 1.4)
  xcolor.sty    2007/01/21 v2.11 LaTeX color extensions (UK)
   color.cfg    2007/01/18 v1.5 color configuration of teTeX/TeXLive
 pgfcore.code.tex
pgfcomp-version-0-65.sty    2007/07/03 v3.0.0 (rcs-revision 1.7)
pgfcomp-version-1-18.sty    2007/07/23 v3.0.0 (rcs-revision 1.1)
  pgffor.sty    2013/12/13 v3.0.0 (rcs-revision 1.25)
 pgfkeys.sty    
 pgfkeys.code.tex
 pgfmath.sty    
 pgfmath.code.tex
  pgffor.code.tex
    tikz.code.tex
pgfplots.sty    2015/05/02 v1.12.1 Data Visualization (1.12.1)
 caption.sty    2013/05/02 v3.3-89 Customizing captions (AR)
caption3.sty    2013/05/02 v1.6-88 caption3 kernel (AR)
subcaption.sty    2013/02/03 v1.1-62 Sub-captions (AR)
todonotes.sty    2012/07/25
  ifthen.sty    2014/09/29 v1.1c Standard LaTeX ifthen package (DPC)
 xkeyval.sty    2014/12/03 v2.7a package option processing (HA)
 xkeyval.tex    2014/12/03 v2.7a key=value parser (HA)
    calc.sty    2014/10/28 v4.3 Infix arithmetic (KKT,FJ)
fancyref.sty    1999/02/03 v0.9c Fancy cross-referencing
varioref.sty    2014/10/28 v1.5a package for extended references (FMi)
chemmacros.sty    2015/02/08 v4.7 loads of little helpers for chemists (CN)
   expl3.sty    2015/03/01 v5547 L3 programming layer (loader) 
expl3-code.tex    2015/03/01 v5547 L3 programming layer 
l3unicode-data.def    2015/03/01 v5544 L3 Unicode data
l3pdfmode.def    2015/03/01 v5544 L3 Experimental driver: PDF mode
  xparse.sty    2014/11/25 v5471 L3 Experimental document command parser
l3keys2e.sty    2014/11/25 v5471 LaTeX2e option processing using LaTeX3 keys
 environ.sty    2014/05/04 v0.3 A new way to define environments
trimspaces.sty    2009/09/17 v1.1 Trim spaces around a token list
scrlfile.sty    2015/05/06 v3.17a KOMA-Script package (loading files)
etoolbox.sty    2015/05/04 v2.2 e-TeX tools for LaTeX (JAW)
translations.sty    2014/01/23 v1.2a internationalization of LaTeX2e packages (
CN)
cnltx-base.sty    2015/01/11 v0.12 LaTeX tools and documenting facilities (CN)
 pgfopts.sty    2014/07/10 v2.1a LaTeX package options with pgfkeys
pdftexcmds.sty    2011/11/29 v0.20 Utility functions of pdfTeX for LuaTeX (HO)
ifluatex.sty    2010/03/01 v1.3 Provides the ifluatex switch (HO)
   xfrac.sty    2014/05/04 v4728 L3 Experimental split-level fractions
 amstext.sty    2000/06/29 v2.01
  amsgen.sty    1999/11/30 v2.0
textcomp.sty    2005/09/27 v1.99g Standard LaTeX package
  ts1enc.def    2001/06/05 v3.0e (jk/car/fm) Standard LaTeX file
xtemplate.sty    2014/11/25 v5471 L3 Experimental prototype document functions
 siunitx.sty    2015/01/21 v2.6e A comprehensive (SI) units package
translator.sty    2010/06/12 ver 1.10
translator-language-mappings.tex
mathtools.sty    2015/05/11 v1.16 mathematical typesetting tools
 mhsetup.sty    2010/01/21 v1.2a programming setup (MH)
 amsmath.sty    2013/01/14 v2.14 AMS math features
  amsbsy.sty    1999/11/29 v1.2d
  amsopn.sty    1999/12/14 v2.01 operator names
      bm.sty    2014/10/28 v1.1c Bold Symbol Support (DPC/FMi)
chemformula.sty    2015/04/03 v4.10a typeset chemical compounds and reactions
nicefrac.sty    1998/08/04 v0.9b Nice fractions
chemgreek.sty    2015/04/09 v1.0 interface for upright greek letters for use in
 chemistry (CN)
  mhchem.sty    2015/04/23 v4.01 for typesetting chemical formulae
 l3regex.sty    2014/11/25 v5471 L3 Experimental regular expressions
l3tl-build.sty    2014/08/25 v5378 L3 Experimental token list construction
l3tl-analysis.sty    2014/05/06 v4745 L3 Experimental token lists analysis
   l3str.sty    2014/11/25 v5471 L3 Experimental strings
  l3flag.sty    2014/11/25 v5471 L3 Experimental flags
l3str-convert.sty    2014/06/03 v5028 L3 Experimental string encoding conversio
ns
  xspace.sty    2014/10/28 v1.13 Space after command names (DPC,MH)
  ts1cmr.fd    2014/09/29 v2.5h Standard LaTeX font definitions
  ot1ptm.fd    2001/06/04 font definitions for OT1/ptm.
supp-pdf.mkii
epstopdf-base.sty    2010/02/09 v2.5 Base part for package epstopdf
  grfext.sty    2010/08/19 v1.1 Manage graphics extensions (HO)
kvdefinekeys.sty    2011/04/07 v1.3 Define keys (HO)
kvoptions.sty    2011/06/30 v3.11 Key value format for package options (HO)
kvsetkeys.sty    2012/04/25 v1.16 Key value parser (HO)
etexcmds.sty    2011/02/16 v1.5 Avoid name clashes with e-TeX commands (HO)
epstopdf-sys.cfg    2010/07/13 v1.3 Configuration of (r)epstopdf for TeX Live
translations-basic-dictionary-english.trsl    (english translation file `transl
ations-basic-dictionary')
translator-basic-dictionary-English.dict    
siunitx-abbreviations.cfg    2015/01/21 v2.6e siunitx: Abbreviated units

**Comment by josephwright** [comment]
The `chemmacros` package sets up a `\Molar` unit at the beginning of the document. To over-ride this, the easiest approach is
```latex
\AtBeginDocument{\DeclareSIUnit\Molar{M}}
```
after loading `siunitx`.

**Comment by Aryanix** [comment]
THANK YOU!
