### ISSUE TITLE
exponent-to-prefix and units with reciprocal power

### ISSUE THREAD

**Issue by lbaeni** [josephwright/siunitx#283]
I like to use the `exponent-to-prefix` option for units with reciprocal power.

From the following sample I get 1 ks-1 as output instead of 1 ms-1.

```
\documentclass{article}

\usepackage{siunitx}

\begin{document}
\SI[scientific-notation = engineering, exponent-to-prefix]{1e3}{\per\second}
\end{document}
```

Is there maybe a workaround for this issue?

**Comment by josephwright** [comment]
I see where the issue is here: fix coming up.
