### ISSUE TITLE
\celsius is formatted wrongly in italics

### ISSUE THREAD

**Issue by carlodri** [josephwright/siunitx#285]
this piece of code:
```latex
\documentclass[11pt, a4paper]{article}
\usepackage[italian]{babel}
\usepackage[utf8x]{inputenx}
\usepackage[T1]{fontenc}
\usepackage[detect-all=true]{siunitx}
\begin{document}
	Testing: \SI{45}{\celsius}
\end{document}
```

gives me this output:

![image](https://cloud.githubusercontent.com/assets/5230366/12354356/a6dc4860-bb95-11e5-96b7-6c068752216e.png)

where the celsius symbol is wrongly typeset in italics. The culprit is the `detect-all=true` option, removing it solves the problem.

Using `siunitx 2016/01/05 v2.6o`

**Comment by josephwright** [comment]
Yes, I'm aware of this! I'm trying to find a solution to this issue without breaking other stuff (_i.e._ why it changed in the first place).

**Comment by carlodri** [comment]
super-fast feedback, thanks @josephwright !
