### ISSUE TITLE
units that have arguments

### ISSUE THREAD

**Issue by joshmaxsilverman** [josephwright/siunitx#286]
I'm trying to define a unit that can take an argument like so

`OD\textsubscript{600}`

In general, the subscript can be whatever number. Is there a way to define a unit that has a variable subscript?

**Comment by josephwright** [comment]
You'll need to do this as a stand-alone unit using `\DeclareSIUnit`. (Formally, this is not how units work, though it is of course common: the value is at some point, the unit is independent of that.)
