### ISSUE TITLE
Removing decimal zeros from engineering notation

### ISSUE THREAD

**Issue by russkel** [josephwright/siunitx#287]
Hi,
With my setup
```
\usepackage{siunitx} %formatting for SI units
\sisetup{scientific-notation = engineering, separate-uncertainty = true}
\sisetup{zero-decimal-to-integer}
```
When I use ``\SI{9900}{\ohm}`` I get the output ``9.900 × 10^3 Ω``. Is it possible to strip the trailing 0s while maintaining everything else? I have tried many combinations of options and haven't been able to.

Thanks,
Russ

**Comment by josephwright** [comment]
Looks like you want to use rounding: the package has know way of knowing if the zeros here are significant or not.
```
\documentclass{article}
\usepackage{siunitx} %formatting for SI units
\sisetup{scientific-notation = engineering, separate-uncertainty = true}
\sisetup{zero-decimal-to-integer}

\begin{document}
\SI[round-mode = figures]{9900}{\ohm}
\end{document}
```

**Comment by russkel** [comment]
That looks like it has done the trick! I thought I was going to lose some of the engineering notation setup.
Thanks a lot.
