### ISSUE TITLE
inter-unit-product not showing when reciprocal-positive-first is used

### ISSUE THREAD

**Issue by Tchiller** [josephwright/siunitx#288]
As shown [here](http://tex.stackexchange.com/q/166898) or in this MWE:

```
% arara: pdflatex

\documentclass{article}
\usepackage{siunitx}
\sisetup{inter-unit-product=\times}

\begin{document}
    \noindent
    \si[per-mode = reciprocal-positive-first]{\per\second\second\second}\\
    \si[per-mode = reciprocal]{\second\second\per\second}
\end{document}
```

there is a problem with the inter-unit-product while in use with reciprocal-positive-first. 

Just in order for you to track this issue for v3.0
Thanks.

**Comment by josephwright** [comment]
This is 'works for me' with the current v2 release and in v3.
