### ISSUE TITLE
No warning in case options concerning color are used but any color package is loaded

### ISSUE THREAD

**Issue by dbitouze** [josephwright/siunitx#289]
The following MWE shows that, if any package providing access to colors is loaded, `siunitx` options concerning color have no effect (okay), but silently (not okay). Would it be possible for `siunitx` to issue at least a warning?

```
\documentclass{article}
\usepackage{siunitx}
% \usepackage{xcolor}
\sisetup{negative-color=red}
\begin{document}
\num{-4}
\end{document}

```

**Comment by josephwright** [comment]
This is 'by design': it's the users choice whether to load `color` or not.

**Comment by dbitouze** [comment]
If the user wants negative numbers to be colorized, I don't see any reason for him to not want to load color. IMHO, a warning would be helpful: I experienced this today when a student of mine didn't understand why his negative number was not in color (and me didn't immediately realized what caused this issue).

**Comment by dbitouze** [comment]
Thanks!
