### ISSUE TITLE
round-mode = figures, wrong rounding

### ISSUE THREAD

**Issue by erielf** [josephwright/siunitx#290]
Hi!

Thanks for a great package!

`\SI[round-mode = figures,round-precision = 1]{380}{\N}`
should produce `4*10^2` or `0.4*10^3`, not 400 (which has an unknown number of significant digits between 1-3). This problem persists with round-precision = 2 as well as with scientific-notation = engineering.
Could this be fixed, or is there some way to make it work as I intend?

Best wishes,
Erik

**Comment by josephwright** [comment]
You've not set scientific notation. As such, this behaviour is as-expected. I can see that you can argue that the number of sig. figs here is undefined but that is a pretty common case!
