### ISSUE TITLE
scientific-notation: Wrong rounding of large integers

### ISSUE THREAD

**Issue by erielf** [josephwright/siunitx#291]
This
`\num[round-mode = figures,scientific-notation = engineering,round-precision = 3]{5219602288}`
should produce `522*10^9` but gives `2.15*10^9`
I think it is because the number has 10 integer digits. At 9 digits it seems to work fine.

Thanks for looking into this!
Erik

**Comment by josephwright** [comment]
Not seeing this in the current release (v2.6q) with example
```
\listfiles
\documentclass{article}
\usepackage{siunitx}
\begin{document}

\num[round-mode = figures,scientific-notation = engineering,round-precision = 3]{5219602288}
\end{document}
```
Can you add a MWE and your file log?

**Comment by josephwright** [comment]
Definitely working here in release v2 and with v3-alpha.
