### ISSUE TITLE
\square\degree (or \degree\squared) fails with "Double superscript" error

### ISSUE THREAD

**Issue by murach** [josephwright/siunitx#293]
When using one of the units mentioned in the title, the latex compilation will fail with the error also mentioned in the title. In older releases of siunitx, using such units used to work fine. One can circumvent the issue by using \ang{123}² or so, but I think \square\degree and \degree\squared should work as well.

The siunitx version in use here is 2015.104.2.6hsvn37870-23.2 (this may be the versioning number of the OpenSuse Tumbleweed repository, but I hope at least the SVN identifier helps to identify which version this really is).

I'd be happy to provide further info if needed.

**Comment by josephwright** [comment]
I see what you mean, though I've never come across this notation. I'm therefore suspicious of whether it should work: can you point to an example?

**Comment by murach** [comment]
In our field of research (gamma ray astronomy) we very often talk about squared angular distances, eg the squared angular distance between one photon and the reconstructed direction. When writing about this in a paper or thesis, one would want to state something like $\Theta^2 = \SI{1}{\square\degree}$.
In this paper for example such a notation could have been used, but the authors circumvented the problem by using "degrees²": http://arxiv.org/abs/astro-ph/0607333v1 (pdf page 6, Fig. 6). But I guess you were looking for an example showing the actual usage of \degree\squared, right? I could only find one currently not yet published PhD thesis, most papers I quickly skimmed make use of the circumvention given above. I think this is inconsistent, though, since people do use the degree symbol (°) to indicate normal angles, so I think squaring that should be possible. What do you think?

**Comment by josephwright** [comment]
@murach What I'm after is an example in the published literature, so showing what journal/publishing staff do with such notation.

**Comment by murach** [comment]
Sorry for taking so long to reply. Indeed I couldn't find an example using my suggested notation (°²), and also wikipedia suggests the usage of "deg²": https://en.wikipedia.org/wiki/Square_degree
So although it felt like a regression to me (since "°²" used to work in older releases), I guess it's not a bug that it now doesn't work anymore. Now I have to go convince the SI standard authors to introduce my suggested notation ;P

**Comment by josephwright** [comment]
This is working in the v3 development code.
