### ISSUE TITLE
Options retain-unity-mantissa and scientific-notation don't work together

### ISSUE THREAD

**Issue by bzindovic** [josephwright/siunitx#294]
The output of the following command:
`\num[retain-unity-mantissa = false, scientific-notation = true]{0.001}`
is 1 \cdot 10^{-3} instead of just 10^{-3}.

**Comment by josephwright** [comment]
That's not surprising to me: I'd say this situation here is simply undefined! The unity mantissa business is about parsing the input, so it's usurping to me: you don't have a unit mantissa. I guess I'll have to either document this or alter the code path: the latter course of action is easier!
