### ISSUE TITLE
Mention a siunitx.cfg file with cyrillic units in siunitx documentation

### ISSUE THREAD

**Issue by ScumCoder** [josephwright/siunitx#296]
[GOST 8.417-2002](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B6%D0%B4%D1%83%D0%BD%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D0%B0%D1%8F_%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0_%D0%B5%D0%B4%D0%B8%D0%BD%D0%B8%D1%86#.D0.9E.D1.81.D0.BD.D0.BE.D0.B2.D0.BD.D1.8B.D0.B5_.D0.B5.D0.B4.D0.B8.D0.BD.D0.B8.D1.86.D1.8B) prescribes to use Russian designations for measurement units, and also for prefixes.

[I have created](https://gitlab.com/ScumCoder/siunitx-russian) a `siunitx.cfg` file with all cyrillic definitions I could find.

I don't think such functionality is worth integrating into `siunitx` itself, but I think it is worth mentioning the existence of such file in the package documentation, to make `siunitx` accessible for Russian-speaking (and -writing) users. Or maybe just include this file in the package distribution.

**Comment by josephwright** [comment]
I've had Russian speakers ask about similar things before. I'm afraid this is a straight 'no': the international standard uses Roman/Greek letters for _all_ units, there's no 'except if you write in Cyrillic' rule!

**Comment by ScumCoder** [comment]
> there's no 'except if you write in Cyrillic' rule

Ugh... actually, there _is_ such rule, and it is called GOST (государственный стандарт; state standard). In this particular case, this is [GOST 8.417-2002](http://docs.cntd.ru/document/1200031406) ("Units of quantities") that I mentioned in the first post. Nobody ever used the letter `s` to denote `секунда` or `kg` to denote `килограмм` in thousands of thousands of Russian scientific articles published over last 2 or 3 centuries, and nobody will, at least in foreseeable future.

Anyway, you are the creator of this package, so obviously it's up to you to decide.

**Comment by josephwright** [comment]
@ScumCoder The rules for SI are defined by the BIPM, I'm afraid. Since the release of v2 I've been very clear that the standard code in `siunitx` will stick to the 'rules': if I start on 'it would be nice' stuff I end up in all sorts of trouble. (I'm a chemist and a common unit for me is non-standard, so I always have to define it in the preamble.)

**Comment by ScumCoder** [comment]
> Since the release of v2 I've been very clear that the standard code in siunitx will stick to the 'rules'

I'm all for that. This is why I explicitly said that I'm _not_ suggesting to add anything in your code base. Only to _mention_ that such file exists. So basically I suggested to add one line somewhere at the end of the manual that says something like "if you are Russian, go here". That's all.

**Comment by josephwright** [comment]
@ScumCoder  OK, I'll consider a form of words I'm happy with

**Comment by josephwright** [comment]
I'm avoiding site-dependent code in v3, so no more `.cfg` files.
