### ISSUE TITLE
exponent-to-prefix in \SIrange

### ISSUE THREAD

**Issue by lbaeni** [josephwright/siunitx#297]
Using the `exponent-to-prefix` option in `\SIrange` yields wrong unit prefix conversions in some cases.

```
\documentclass{article}

\usepackage{siunitx}

\begin{document}
\SIrange[scientific-notation = engineering, exponent-to-prefix]{0.3}{6e3}{\m}\\
\SIrange[scientific-notation = engineering, exponent-to-prefix]{0.3}{6}{\m}
\end{document}
```

The first example outputs correctly 300 mm to 6 km. But the second one results in 300 mm to 6 mm.

The problem seems to appears if no unit prefix conversion is needed for the upper boundary of the range.

**Comment by josephwright** [comment]
Basically fixed in v3, although I've adjusted how ranges work so they have the same unit at both 'ends'.
