### ISSUE TITLE
Greek letter mu missing in \micro (siunitx 2017/03/23 v2.7f)

### ISSUE THREAD

**Issue by gvdeynde** [josephwright/siunitx#304]
Using xelatex (This is XeTeX, Version 3.14159265-2.6-0.99997 (MiKTeX 2.9.6300 64-bit) (preloaded format=xelatex 2017.4.18)  18 APR 2017 17:10) or lualatex (This is LuaTeX, Version 1.0.4 (MiKTeX 2.9.6300 64-bit)  (format=lualatex 2017.4.18)  18 APR 2017 17:19) from a recently updated MikTeX installation, I'm loosing the mu in \SI.  The glyph is available, since $\mu$ works. 

Am I doing something wrong?

MWE:

```
\documentclass[a4,t]{beamer}
\usefonttheme{professionalfonts}
\usepackage{fontspec}
\usepackage[]{unicode-math}
\setmainfont{Segoe UI}
\setmathfont{Asana Math}
\usepackage{siunitx}

\begin{document}

\SI{20}{\milli\sievert} or 
\SI{20}{\micro\sievert}

$\SI{20}{\micro\sievert}$

$20 \mu$Sv

\end{document}
```

**Comment by josephwright** [comment]
You have a complex font situation: `siunitx` has some 'guesses' for common cases but this is not one. As detailed in Section 7.6 of the manual, probably
```latex
\sisetup{
  math-micro = \text{μ},
  text-micro  = μ
}
```
is an appropriate setting.

**Comment by gvdeynde** [comment]
Thanks. That seems to work. Being a XeTeX font novice, could you explain why this is a "complex font situation"? I just wanted to use the beamer class with my own choice (better said: my company's choice) fonts for text and math. Is there a way to simplify?
