### ISSUE TITLE
l3kernel update breaks siunitx

### ISSUE THREAD

**Issue by u-fischer** [josephwright/siunitx#311]
siunitx uses the boolean `\c_sys_engine_xetex_bool`. This boolean is as far as I can see not defined. Until now this didn't lead to errors as expl3 didn't complain about `\bool_if:NT\c_some_unknown_bool{abc}`. But this has changed after the last l3kernel update. And now it is no longer possible to load fontspec together with siunitx:

```

\documentclass{article}
\usepackage{siunitx}
\usepackage{fontspec}
\begin{document}

blub
\end{document}
```

```
! Undefined control sequence.
<argument> \c_sys_engine_xetex_bool 
                         
l.7 \begin{document}
```

**Comment by josephwright** [comment]
Ooops ... I'll sort ASAP
