### ISSUE TITLE
\ang not working with parse-numbers=false

### ISSUE THREAD

**Issue by tom75de** [josephwright/siunitx#313]
If I try this

    \documentclass{scrartcl}
    \usepackage[utf8]{inputenc}
    \usepackage{siunitx}
    \begin{document}
    \sisetup{parse-numbers=false}
    \ang{1,\overline{6}}
    \end{document}

I get the following error messages
```
! Undefined control sequence.
<argument> \l__siunitx_angle_minte_zero_bool 
                                             
l.6     \ang{1,\overline{6}}
                            
? 
! Missing number, treated as zero.
<to be read again> 
                   \relax 
l.6     \ang{1,\overline{6}}
```
Regards,
Tom

**Comment by josephwright** [comment]
Already fixed by 0c70f01dd526b8e5aa50694b34609c00538d7879: I'll update CTAN.
