### ISSUE TITLE
Using `siunitx` with the `cellspace` package: probably simpler now

### ISSUE THREAD

**Issue by dbitouze** [josephwright/siunitx#315]
Since its last release (v1.7), the `cellspace` package allows using a different column name:

>**Using a different column name**
> An other column name than `S` can be used if `S` conflicts with the user’s own definitions or a package’s. A keyval option can be passed to the package to that effect;
>```latex
>\usepackage[column=O]{cellspace}
>```
>can be used to provide cellspace’s functionality through the `O` column modifier instead of the `S` column modifier.

Hence maybe the "Using `siunitx` with the `cellspace` package" section from `siunitx`'s documentation could be revised.

**Comment by josephwright** [comment]
Probably it would be best to see if this facility is available and use it if it is.

**Comment by u-fischer** [comment]
Using this option with siunitx  doesn't work currently:

```
\documentclass{article}
\usepackage{siunitx}
\usepackage[column=Q]{cellspace}

\begin{document}
\begin{tabular}{Qc c}
    \hline
A   &   123   \\
    \hline
\end{tabular}
\end{document}
```

gives the error 

~~~~
Runaway argument?
\NC@do *\NC@do w\NC@do W\NC@do Q\NC@do C\q_stop \cs_undefine:N \NC@find@S \ETC.
! File ended while scanning use of \__siunitx_tmp:w.
~~~~

tested on TL18 and TL17.
