### ISSUE TITLE
enhancements: exponent-to-prefix  w/o unit; retain-unity-mantissa=false when input is not scientific

### ISSUE THREAD

**Issue by wrfranklin** [josephwright/siunitx#316]
siunitx is great!     Here are two enhancements that would be useful, if possible.

1. Enable exponent-to-prefix  when no unit is specified.   I.e.,   \SI{1000000}{} or \num{1000000} would typeset as 1M, similar to \SI{1000000}{\g} producing 1Mg.

2. Have  \num[scientific-notation = true,retain-unity-mantissa=false]{1000000} produce 10^6,not 1x10^6, as
 \num[scientific-notation = true,retain-unity-mantissa=false]{1e6} does.

Thanks.

**Comment by josephwright** [comment]
The first issue is the same as https://github.com/josephwright/siunitx/issues/378, which I'm keeping open. The second issue doesn't really follow: I can't drop the digits there so it's not got a mantissa of `1`, it's `1.000000`.
