### ISSUE TITLE
\ang \degree don't work with mathspec package

### ISSUE THREAD

**Issue by mrclary** [josephwright/siunitx#317]
\ang and \degree commands don't work when the mathspec package is loaded. No error is raised, but the degree symbol is absent.

```latex
\documentclass{article}
\usepackage{mathspec}
\usepackage{siunitx}

\begin{document}
hello world \SI{2}{\degree}
\end{document}
```

**Comment by josephwright** [comment]
Fixed in v3: release likely later in the year.
