### ISSUE TITLE
Turning off unit parsing leads to unexpected output

### ISSUE THREAD

**Issue by lblblb** [josephwright/siunitx#318]
Thank you for this great package!

I tried the option `parse-units=false` in my document today and observed two anomalies with it. See my example. First, `\si` will place a `1` directly before the units. Second, the `\pm` symbol gets written out when using `\SI`, even though it is not a unit so should not be affected by turning the unit parsing off.

```
\documentclass{article}
\usepackage{siunitx}
\sisetup{
    per-mode = symbol,
    separate-uncertainty,
    parse-units = false % causes bug
}
\begin{document}\obeylines
\SI{10}{\mm}
\si{\mm}
\num{1+-1}
\SI{1+-1}{\mm}
\end{document} 
```
![3](https://user-images.githubusercontent.com/12690798/32251654-3fcd725a-be92-11e7-94a4-8bfe49af65b0.png)

**Comment by josephwright** [comment]
Mumble, the `\pm` issue: I'll have to think about where I should be handling it ...

**Comment by josephwright** [comment]
Working in v3-pre-alpha: I'll close as this will be fixed once I can release.
