### ISSUE TITLE
Uncertainty displayed wrong with non-matching decimal places

### ISSUE THREAD

**Issue by lblblb** [josephwright/siunitx#322]
The bug occurs when the decimal places between number and uncertainty don't match and it causes the uncertainty to be displayed wrong. As `siunitx` parses and understands (per the manual) numbers so I expected it to interpret all of these correctly.

My example shows that the main number can get away with having one less decimal place than the uncertainty, but no less than that. 

```
\documentclass{article}
\usepackage{siunitx}

% same with separated uncertainty
%\sisetup{separate-uncertainty}

\begin{document}
% no decimal zero
\num{2+-0,1} % correct

\num{2+-0,01} % wrong

\num{2+-0,001} % wrong

---

% one decimal zero
\num{2,0+-0,1} % correct

\num{2,0+-0,01} % correct

\num{2,0+-0,001} % wrong

---

% two decimal zeros
\num{2,00+-0,1} % correct, uncertainty gets trailing zero

\num{2,00+-0,01} % correct

\num{2,00+-0,001} % correct

\end{document}
```
![2017-11-23 10_18_21-start](https://user-images.githubusercontent.com/12690798/33165638-d4af4fcc-d037-11e7-8530-81a5f29cf7d7.png)

**Comment by josephwright** [comment]
The behaviour here is undefined: the input simply doesn't have sufficient precision to support the suggested uncertainty.

**Comment by lblblb** [comment]
I agree with you when using the parantheses notation – e.g.&nbsp;2,0(1) – but with the plus-minus-notation there is no real need to match the decimals of number and uncertainty for the output. I understand that `siunitx` is written with measurement results in mind, but there are other uses where the decimal places do not need to be matched. In technical drawings for example, 2&nbsp;+−&nbsp;0.01 means 2&nbsp;mm nominal with a tolerance (_not_ uncertainty) of 0.01&nbsp;mm in either direction. The nominal value is assumed to be 2.00&nbsp;mm for calculations, but never written that way. As such, a `\SI{2+-0.01}{\mm}` would be perfectly valid for these uses.

**Comment by josephwright** [comment]
@lblblb I'll look at this for v3, though I've always been absolutely clear that `siunitx` deals with uncertainties not tolerances. (People want the latter to be asymmetric, which makes life very complex: it is doable but I fear only at the expense of clear core functionality.) What would of course be needed here is an option which deals with the fact that the `2` isn't being 'expanded' to include the number of significant figures implied by the uncertainty.

**Comment by josephwright** [comment]
I've pondered this a bit and think there is a way to handle it without having to make too many changes, at least in the v3 code (I'm working to have that ready for next summer). The plan is in two parts: 'expand' input numbers if the uncertainty requires it, and then allow rounding of purely the value, leaving the uncertainty unchanged. The net result will be what you want: not maximum efficiency for this case but fitting with the general scheme, and the fact that the focus of the package is measured values.

**Comment by josephwright** [comment]
This is working in v3: I'll close. (Release is likely toward the end of the year.)
