### ISSUE TITLE
Math is broken with siunitx and \setsansfont{DejaVuSans.ttf}

### ISSUE THREAD

**Issue by Socob** [josephwright/siunitx#323]
This seems really obscure, and I’m not sure who the “culprit” is, but I guess I’ll start looking here.

Math output seems to be broken when both `siunitx` is loaded and `\setsansfont{DejaVuSans.ttf}` is set using `fontspec`. See the following example:
```latex
\documentclass{scrartcl}

\usepackage{amsmath}
\usepackage{mathtools}
\usepackage{fontspec}
% removing either of the following lines fixes the problem
\setsansfont{DejaVuSans.ttf}
\usepackage{siunitx}

\begin{document}

\begin{equation*}
	T(v^*, w) = v^\dagger T w
	\mapsto (v^\dagger \underbrace{M^\dagger) T (M}_{= T} w)
\end{equation*}

\begin{equation*}
	\det(A)
	= \sum_{\mathclap{i_1, \dots, i_n = 1}}^{n} \varepsilon^{i_1 \dots i_n} A_{1 i_1} \dots A_{n i_n}
\end{equation*}

\begin{equation*}
	(M \varepsilon M^T)_{12}
	= \sum_{i, j = 1}^2 M_{1i} \varepsilon^{ij} (M^T)_{j2}
	= \sum_{i, j = 1}^2 \varepsilon^{ij} M_{1i} M_{2j}
	= \det(M)
	= 1
	= \varepsilon^{12}
\end{equation*}

\end{document}
```
If *both* of the the lines `\setsansfont{DejaVuSans.ttf}` and `\usepackage{siunitx}` are present, math operators are broken. The sum signs are way too small (they look like inline math), the subscripts completely disappear and the remaining spacing is off (the superscripts stick to the sum signs with no space in between). Also, the superscripts on everything else seem to be placed too far away:

![broken output](https://user-images.githubusercontent.com/1915511/33216980-671a5b0a-d136-11e7-9485-cff61f4c3a8a.png)

For reference, this is what it looks like if *either of the two lines* is removed:

![correct output](https://user-images.githubusercontent.com/1915511/33217001-81fe2dfc-d136-11e7-9afd-3a2704de7928.png)

Now the weird part (as if this weren’t weird enough yet): This only seems to happen with DejaVu Sans (at least I haven’t found any other font with the problem; FreeSans works without issue, for example). Also, the problem only seems to affect LuaTeX – XeTeX gives the same (correct) output in both cases.

Version info: siunitx 2017/08/02 v2.7j, fontspec 2017/09/22 v2.6e, LuaTeX v1.0.4.
This problem has probably been introduced somewhere recently, because this was definitely working for me three months ago.

**Comment by josephwright** [comment]
Working with TL'18 releases: I can only assume an engine bug (`siunitx` does nothing in terms of changing fonts generally).
