### ISSUE TITLE
Command conflict with `physics` package

### ISSUE THREAD

**Issue by zoqaeski** [josephwright/siunitx#325]
The [physics](https://ctan.org/pkg/physics) package defines the command `\qty` which conflicts with `siunitx` version 3, which also defines a command with the same name.

The `physics` command is a convenience wrapper for automatic bracket sizing; I've never used it myself in any of my documents, but I'm sure there are users of both packages that might.

**Comment by josephwright** [comment]
I'm aware of that: currently the interfaces for v3 are largely exploratory.

**Comment by e-kwsm** [comment]
The issue is not resolved. `physics` uses `\DeclareDocumentCommand` to defile `\qty`, while `siunitx` uses `\NewDocumentEnvironment`; `\ProvideDocumentEnvironment` or `\DeclareDocumentCommand` would be preferred.

**Comment by josephwright** [comment]
No, because as I said this is exploratory work.
