### ISSUE TITLE
SIrange broken in math mode

### ISSUE THREAD

**Issue by charlesbaynham** [josephwright/siunitx#326]
In siunitx v2.7j, typesetting ranges in math mode results in the `range-phrase` also being in math mode when it shouldn't be. 

MWE:

	\documentclass{article}

	\usepackage{siunitx}

	\begin{document}

	The sun emits radiation principally in its black-body spectrum, extending roughly from $\lambda = \SIrange{390}{700}{\nano\meter}$. 

	\end{document}

**Comment by josephwright** [comment]
As the docs say, `\SIrange` has to be used in text mode: I may be able to address this in v3.

**Comment by charlesbaynham** [comment]
Apologies, I missed that. Still, might be nice to have it work as expected in math mode too.
