### ISSUE TITLE
Option to remove a minus sign when a number rounds to 0

### ISSUE THREAD

**Issue by eg9** [josephwright/siunitx#329]
Reference https://tex.stackexchange.com/questions/416283/

Depending on the field or the particular application, a minus sign might be kept or removed upon a round operation that produces 0.

I believe it would be a good addition having an option for removal in this case.

**Comment by josephwright** [comment]
I'm looking at this, certainly for v3.0 if not back-ported to v2.x. The obvious question in a v3 context is where does this apply? I've not covered 'negative zero', so there are a few possibles:

- Allow `-0.0` generally, and filter out at the printing stage (something like `print-negative-zero`): that's then not tied to rounding
- Suppress it during rounding (`round-negative-zero = false` or similar), with either allowing or suppressing it at the input stage separately
- Other approaches ...

Implementation should be easy enough, but I could do with an idea of how general the concept needs to be.

**Comment by josephwright** [comment]
Current dev code removes the sign if we round to zero: I likely still need to work a bit more on it.

**Comment by josephwright** [comment]
I'm pushing to v3.1 - I'd like to finalise v3, and this is essentially an enhancement.

**Comment by josephwright** [comment]
@eg9 Please see if the option name here makes sense

**Comment by eg9** [comment]
@josephwright Seems good, once it's clear what it refers to. But why not `retain-negative-zero`?

**Comment by josephwright** [comment]
@eg9 b3f81faa0c3bf47746b439d5c8073fc83d8a2578 :) I've tried to be clear that `retain-...` is about _parsing_, whereas here we are in the 'processing' step (mainly `round-...` options); I also have `print-...` for output where the internal form is unaffected. The idea then is people might reuse the parser to have numbers which are 'the same' based on internal form. (I have an open issue to make the parser expandable, which will probably help with that!)

**Comment by eg9** [comment]
@josephwright Fine, then.
