### ISSUE TITLE
Option to add a space between preunit and number

### ISSUE THREAD

**Issue by wojciechbielecki** [josephwright/siunitx#330]
There is no easy option to add a space (i.e. product sign) between the preunit and the number when using `\SI{123}[preunit]{}`.

The current workaround is to define a unit with a thin space at the end, like `\DeclareSIUnit[]{\EURs}{\textsc{eur\,}}`, but then it is useful only with `\SI` command, and not on its own in `\si`, as it will add extra space. This requires defining two units for the two purposes.

Example:
<img width="1001" alt="screen shot 2018-03-03 at 21 20 48" src="https://user-images.githubusercontent.com/33196739/36938908-c868651a-1f28-11e8-894f-180cd3e99592.png">

Code:
```latex
\documentclass{article}
\usepackage[round-mode=places,round-integer-to-decimal]{siunitx}

% Using full spaces for demonstration
\DeclareSIUnit[]{\EURspace}{\textsc{eur\ }}
\DeclareSIUnit[]{\EUR}{\textsc{eur}}

\begin{document}
\verb|\EURspace| defined as \verb|\textsc{eur\ }|. \\
\verb|\EUR| defined as \verb|\textsc{eur}|. \\
Using \verb|\si{\EURspace}|: \si{\EURspace}. (bad) \\
Using \verb|\SI{123.00}[\EURspace]{}|: \SI{123}[\EURspace]{}. (ok) \\
Using \verb|\si{\EUR}|: \si{\EUR}. (ok) \\
Using \verb|\SI{123.00}[\EUR]{}|: \SI{123}[\EUR]{}. (bad) \\
\end{document}```

**Comment by wojciechbielecki** [comment]
Perhaps this could be solved by adding an option `unit-number-product` in parallel to existing `number-unit-product`.

I understand that the current behaviour may be expected when using currencies symbols (€, $, £), but with ISO codes, [there should be a space](http://publications.europa.eu/code/en/en-370303.htm).

**Comment by josephwright** [comment]
For v3 I dropped the pre-unit as it really wasn't a good idea. As such, I'm closing here.
