### ISSUE TITLE
\astronomicalunit macro has the wrong output

### ISSUE THREAD

**Issue by aragilar** [josephwright/siunitx#332]
Usually the symbol for astronomical unit is AU not ua. Can this be updated?

**Comment by josephwright** [comment]
I follow the BIPM on standard symbols. The current Brochure has this as 'ua' (see https://www.bipm.org/utils/common/pdf/si_brochure_8_en.pdf, table 7), though admittedly they've removed it from the website version (https://www.bipm.org/en/publications/si-brochure/table7.html).

**Comment by aragilar** [comment]
Odd, I've never seen astronomical unit as ua. According to wikipedia, BIPM recommended using ua in 2006 (https://en.wikipedia.org/wiki/Astronomical_unit#Symbol_usage), but they changes to using au in 2014 (see https://www.bipm.org/en/publications/si-brochure/table6.html).

**Comment by josephwright** [comment]
Tricky one: whilst the website is useful the PDF is definitive ... I'm not sure the formal rules can be changed between SI versions!

**Comment by aragilar** [comment]
You could drop astronomical unit (as happened with parsec and lightyear), which would avoid confusion, if you feel modifying it is problematic. It's worth noting that the IAU recommends au (which I'd rank higher in terms of standards for astronomy related things, and presumably the reason BIPM changed their recommendation).

**Comment by josephwright** [comment]
I've decided to make the change here: the key for me is that I have to have some way of explaining the units I cover (and the symbols) beyond 'I thought it was a good idea'. That does seem to be the case here, so I'm happy to alter.
