### ISSUE TITLE
'Undefined control sequence' Error in siunitx.sty

### ISSUE THREAD

**Issue by suiramnox** [josephwright/siunitx#333]
Since I updated to the newest version 2.7l I always get the following two Errors:

line 258 ! Undefined control sequence.<argument> \seq_const_from_clist:Nn\c__siunitx_old_options_seq {addsign,all... }
line 258! Undefined control sequence.<argument> ...list:Nn \c__siunitx_old_options_seq{addsign,allowlitunits,all... }

Any ideas how to fix that?

**Comment by josephwright** [comment]
Can you add an example and the `.log` that you get?

**Comment by josephwright** [comment]
You've got `l3kernel` installed as 'you' but `siunitx` installed system-wide. Probably you need to run the MiKTeX Update Wizard in 'user' and 'admin' modes.

**Comment by suiramnox** [comment]
Ah, okay. I removed `siunitx`, `l3kernel` and `l3packages` from my personal folder an reinstalled the packages as administrator. And it works! 

Thank you so much, Mr. Wright!!
