### ISSUE TITLE
math mode gives different result with different engines

### ISSUE THREAD

**Issue by moewew** [josephwright/siunitx#334]
Consider
```latex
\listfiles
\documentclass{article}

\ifx\Umathcode\undefined
\usepackage[osf]{libertine}
\else
\usepackage{fontspec}
\setmainfont[Numbers={OldStyle}]{Linux Libertine O}
\fi

\usepackage{siunitx}

\sisetup{
  detect-all,
}

\begin{document}
  \begin{itemize}
    \item Regular numbers in text mode: main font, as expected: 2469
    \item SI numbers in text mode: main font, as expected: \num{2469}
    \item Numbers in math mode: math font, as expected: $2469$
    \item SI numbers in math mode: text font, not expected: $\num{2469}$
  \end{itemize}
\end{document}
```
when run with pdfLaTeX (MikTeX's 1.40.19) gives
![danslisnsg-pdflatex](https://user-images.githubusercontent.com/6755835/38170635-bf404bb0-358a-11e8-998f-2603ad20c7b3.png)
this is what I would have expected from the option.

With XeLaTeX (0.99999) I get
![danslisnsg-xelatex](https://user-images.githubusercontent.com/6755835/38170643-e0e98966-358a-11e8-8494-44387b8a60e7.png)
here `siunitx` ignores the math mode in the last item.

With LuaLaTeX (1.07.0)
![danslisnsg-lualatex](https://user-images.githubusercontent.com/6755835/38170661-2cdf61ba-358b-11e8-8db8-82fbadcf1a3e.png)
math mode is ignored in the last item and the numerals are not old style.

Similar results can be obtained if `mode` is forced explicitly instead of using `detect-all`.
`mode=math` still gives text fonts for XeLaTeX and LuaLaTeX, while pdfLaTeX gives the math font as expected.

Is this a failure to understand the options on my part or is there something more to it?

<details>
<summary>Output of <code>\listfiles</code></summary>

```
 *File List*
 article.cls    2014/09/29 v1.4h Standard LaTeX document class
  size10.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
fontspec.sty    2017/11/09 v2.6g Font selection for XeLaTeX and LuaLaTeX
  xparse.sty    2018/02/21 L3 Experimental document command parser
   expl3.sty    2018/03/05 L3 programming layer (loader) 
expl3-code.tex    2018/03/05 L3 programming layer 
l3pdfmode.def    2017/03/18 v L3 Experimental driver: PDF mode
fontspec-luatex.sty    2017/11/09 v2.6g Font selection for XeLaTeX and LuaLaTeX

 fontenc.sty
   tuenc.def    2017/04/05 v2.0i Standard LaTeX file
fontspec.cfg
 siunitx.sty    2018-03-20 v2.7m A comprehensive (SI) units package
 amstext.sty    2000/06/29 v2.01 AMS text
  amsgen.sty    1999/11/30 v2.0 generic functions
   array.sty    2016/10/06 v2.4d Tabular extension package (FMi)
l3keys2e.sty    2018/02/21 LaTeX2e option processing using LaTeX3 keys
translator.sty    2018/01/04 v1.12 Easy translation of strings in LaTeX
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
translator-basic-dictionary-English.dict    
siunitx-abbreviations.cfg    2017/11/26 v2.7k siunitx: Abbreviated units
 ***********
```
</details>

**Comment by josephwright** [comment]
It is expected, but it helps if you are comparing the right thing :) You want
```latex
$\mathrm{2469}$
```
in the reference versions. Looks like the two different approaches to loading the font set up `\mathrm` numerals differently (not surprising: the  back-end is entirely different).

**Comment by moewew** [comment]
Ah, now that makes more sense.

This issue arose from a question on a German TeX forum https://golatex.de/zwei-probleme-mit-siunitx-t20542.html that has since also been posted on TeX.SX: https://tex.stackexchange.com/q/424292/35864

I was trying to figure out how `detect-all` works and why `mode=math` did not give the same output of numbers and units as recreated in math mode. The original question was about the Omega for `\ohm`, but I see now that there is quite a lot going on for the Omega.

Regarding the Omega a tried
```latex
\listfiles
\documentclass{article}

\ifx\Umathcode\undefined
\usepackage[osf]{libertine}
\else
\usepackage{fontspec}
\setmainfont[Numbers={OldStyle}]{Linux Libertine O}
\fi

\usepackage{siunitx}

\sisetup{
  mode=math,
  redefine-symbols=false,
  math-ohm = {\ensuremath{\Omega}},
  text-ohm = {\ensuremath{\Omega}},
}

\begin{document}
  \begin{itemize}
    \item Regular numbers in text mode: main font, as expected: \SI{2469}{\ohm}
    \item SI numbers in text mode: main font, as expected: \SI{2469}{\ohm}
    \item Numbers in math mode: math font, as expected: $2469 \Omega$
    \item SI numbers in math mode: text font, not expected: $\SI{2469}{\ohm}$
  \end{itemize}
\end{document}
```
with limited success (pdfLaTeX worked as I expected, LuaLaTeX and XeLaTeX not so much). But I may well be misunderstanding things here.

**Comment by u-fischer** [comment]
It is the same problem that is popping up currently in other places: siunitx uses \mathrm, and \mathrm is a textfont which can or can not fit the math font.  fontspec is normally setting \mathrm to the main text font, and if this differ from the math font in your first example. You can use `\usepackage[no-math]{fontspec}`.

With unicode-math I would explictly for \mathrm to use the math font:

~~~~
\documentclass{article}

\ifx\Umathcode\undefined
\usepackage[osf]{libertine}
\else
\usepackage{unicode-math}
\setmainfont[Numbers={OldStyle}]{Linux Libertine O}
%or alternativly
%\setmathfont{Libertinus Math}
%\setmathfontface\mathrm{Libertinus Math}
\setmathfont{Latin Modern Math}
\setmathfontface\mathrm{Latin Modern Math}
\fi

\usepackage{siunitx}

\sisetup{
  detect-all,
}

\begin{document}
  \begin{itemize}
    \item Regular numbers in text mode: main font, as expected: 2469
    \item SI numbers in text mode: main font, as expected: \num{2469}
    \item Numbers in math mode: math font, as expected: $2469$
    \item SI numbers in math mode: text font, not expected: $\num{2469}$
  \end{itemize}
\end{document}
~~~~

**Comment by josephwright** [comment]
I guess I need to finalise v3: I've got a very different model there for how to deal with font selection, and it is much better aligned with how Unicode engines view fonts.

**Comment by moewew** [comment]
To my limited understanding it would be more intuitive if `\mathrm` selected the upright shape of the math font instead of the text font (I'd expect `\text` to select the text font). If I understand correctly this is more or less what happens with pdfLaTeX.

Is there any chance to have the Unicode engines behave the same (with `fontspec` ) by default?

**Comment by josephwright** [comment]
Fixed in the v3 code.
