### ISSUE TITLE
issues printing bold math with unicode-math and missing minus sign

### ISSUE THREAD

**Issue by itzsimpl** [josephwright/siunitx#338]
I am working on a document with custom typography based on EB Garamond (Georg Duffner's version with two optical sizes; https://github.com/georgd/EB-Garamond). I succeeded setting up correct math printing with `unicode-math`, but I am running into issues with the `siunitx` package. On the attached picture generated with `XeLaTeX` you can notice that:

1) the minus sign is missing in superscripts when in text mode (lines 2 and 4),
2) the output in math mode uses the wrong font (OldStyle numerals instead of Lining) (lines 6 and 8 vs 5 and 7)
3) siunitx fails to detect/select bold math font (line 8 vs 7).

![image](https://user-images.githubusercontent.com/4784070/40543018-dbd76e08-6022-11e8-9e1f-256f2bbea173.png)

I was able to correct issues 1) and 2), but I am unable to solve issue 3). 

Issue 1) can be solved by adding
`
\ExplSyntaxOn
\tl_gset:Nn \c__siunitx_minus_tl { \ensuremath{ - } }
\ExplSyntaxOff
`
into the preamble.

Issue 2) arises from the fact that `unicode-math` interprets `\mathrm` as a 'text math font' (also `\mathtextrm)` and therefore can be solved either by calling
`
\unimathsetup{mathrm=sym} 
`
that will make all math be printed with the 'math math font' `(\symrm),` or calling
`
\sisetup{math-rm=symrm}
`
that will configure siunitx to use `\symrm` for `math-rm` output.

As regards issue 3) I noticed that siunitx toggles bold output with `\bfseries` for text and `\boldmath` for math. However, `\boldmath` with unicode-math does not work (at least in my case). In math mode I can achieve the bold output simply by calling `\mathbfup` or `\symbf` (for 'math math') and `\mathbf` or `\mathtextbf` (for 'text math') output, but if I call `$\symbf{123 \num{123} 123}$` only the first and last number are printed in bold.

Would it be possible to introduce a similar concept as `math-rm`, `math-tt`, `math-sf` for math bold output?

**Comment by josephwright** [comment]
I'm aware of issues with Unicode fonts: the underlying assumptions are very different from classical TeX. I'm working on v3 of `siunitx` which should I think sort all of this, but by using an entirely different approach to font control (in the end this is *necessary*). Hopefully some progress is happening: I'll see if I can sort the immediate issue for v2.

**Comment by josephwright** [comment]
Could you add an example of the input you are using? I'd like to test against my v3 experiments, and also try to solve for v2 if possible.

**Comment by itzsimpl** [comment]
The example was produced with the following minimal code:
```
\documentclass{article}

\RequirePackage{microtype}
\RequirePackage{realscripts}
\RequirePackage{amsmath} 
\RequirePackage{amssymb}
\RequirePackage[math-style=french,bold-style=upright]{unicode-math} 
\RequirePackage{ragged2e} 

\setmainfont{EBGaramond12-Regular.otf}[ % https://github.com/georgd/EB-Garamond
	Path=fonts/EBGaramond/,
	Ligatures={TeX,Discretionary},
	UprightFeatures={
		SizeFeatures={
			{Size=-8, Font={EBGaramond08-Regular.otf}},
			{Size= 8-, Font={EBGaramond12-Regular.otf}}
		}
	}, 
	ItalicFont={EBGaramond12-Italic.otf},
	ItalicFeatures={
		SizeFeatures={
			{Size=-8, Font={EBGaramond08-Italic.otf}}, 
			{Size= 8-, Font={EBGaramond12-Italic.otf}}
		}
	},
	Mapping=tex-text,
	Numbers={OldStyle},
	AutoFakeBold=1.5
]

\setsansfont{SourceSansPro}[ % https://github.com/adobe-fonts/source-sans-pro, 2.020R-ro/1.075R-it 
	Path=fonts/SourceSansPro/,
	Mapping=tex-text, 
	Ligatures={TeX}, 
	Numbers={OldStyle}, 
	UprightFont={*-Regular.otf},
	ItalicFont={*-It.otf},
	BoldFont={*-Semibold.otf},
	BoldItalicFont={*-SemiboldIt.otf},
	Scale=MatchLowercase
]

\setmonofont{SourceCodePro}[ % https://github.com/adobe-fonts/source-code-pro, 2.030R-ro/1.050R-it 
	Path=fonts/SourceCodePro/,
	Mapping=tex-text, 
	Ligatures={TeX}, 
	UprightFont={*-Regular.otf},
	ItalicFont={*-It.otf},
	BoldFont={*-Semibold.otf},
	BoldItalicFont={*-SemiboldIt.otf},
	Numbers={OldStyle}, 
	Scale=MatchLowercase
]

\setmathfont{Garamond-math.otf}[ % https://github.com/YuanshengZhao/Garamond-Math
	Path=fonts/Garamond-Math/,
	StylisticSet=1
] 

\RequirePackage{siunitx}
\sisetup{detect-all, 
	math-rm=\symup, % force siunitx to print using \sym* instead of \math* (\math* will print OldStyle numerals, like \mathtext*)
	math-sf=\symsf, 
	math-tt=\symtt  
}


\ExplSyntaxOn
\AtBeginDocument{ % these patches need to be called last, after preamble finishes, i.e. at begin document 
	% patch for siunitx package so than the minus sign gets printed in math and text mode
	\tl_gset:Nn \c__siunitx_minus_tl { \ensuremath{ - } }
	
	% patch for realscript package so that proper subscripts get printed with EBGaramond
	% EBGaramond (+subs) equal to (+dnom) rather than typical scientific inferiors
	\DeclareDocumentCommand \realsubscript {m} {
		\fontspec_if_fontspec_font:TF {
			\fontspec_if_opentype:TF
			{ \fontspec_if_feature:nTF {+sinf}
				{ {\addfontfeature{VerticalPosition=ScientificInferior}#1} }
				{ \fontspec_if_feature:nTF {+subs}
					{ {\addfontfeature{VerticalPosition=Inferior}#1} }
					{ \fakesubscript{#1} }
				}
			}
			{ \fontspec_if_aat_feature:nnTF {10} {2}
				{ {\addfontfeature{VerticalPosition=Inferior}#1} }
				{ \fakesubscript{#1} }
			}
		}
		{ \fakesubscript{#1} }
	}
}
\ExplSyntaxOff

\begin{document}
    
    \noindent
	\begin{tabular}{lr}
		text & -9.832\,\times\,10\textsuperscript{-1389} \quad -9.832\,\times\,10\textsuperscript{\pm321} \quad 123 \quad a\textsubscript{bd} \quad a\textsuperscript{pq} \quad a\textsubsuperscript{bd}{pq} \\
		siunitx text & \num{-9.832e-1389} \quad \num{-9.832e\pm321} \quad \num{123} \quad \si{a_{bd}} \quad \si{a^{pq}} \quad \si{a^{pq}_{bd}} \\
		{\bfseries bold text}  & {\bfseries -9.832\,\times\,10\textsuperscript{-1389} \quad -9.832\,\times\,10$^\pm$\textsuperscript{321} \quad 123 \quad a\textsubscript{bd} \quad a\textsuperscript{pq} \quad a\textsubsuperscript{bd}{pq}} \\
		{\bfseries bold text siunitx}  & {\bfseries \num{-9.832e-1389} \quad \num{-9.832e\pm321} \quad \num{123} \quad \si{a_{bd}} \quad \si{a^{pq}} \quad \si{a_{bd}^{pq}}} \\
		math  & $-9.832\,\times\,10^{-1389} \quad -9.832\,\times\,10^{\pm321} \quad 123 \quad \symrm{a_{bd} \quad a^{pq} \quad a_{bd}^{pq}}$ \\
		siunitx math  & $\num{-9.832e-1389} \quad \num{-9.832e\pm321} \quad \num{123} \quad \si{a_{bd}} \quad \si{a^{pq}} \quad \si{a_{bd}^{pq}}$ \\
		{\bfseries symbf bold math}  & {$\symbf{-9.832\,\times\,10^{-1389} \quad 9.832\,\times\,10^{\pm321} \quad 123 \quad a_{bd} \quad a^{pq} \quad a_{bd}^{pq}}$} \\
		{\bfseries siunitx symbf bold math}  & {$\symbf{\num{-9.832e-1389} \quad \num{-9.832e\pm321} \quad \num{123} \quad \si{a_{bd}} \quad \si{a^{pq}} \quad \si{a_{bd}^{pq}}}$} \\
	\end{tabular}

\end{document}
```

Note that I compiled with XeLaTeX and that doing so generates the following warnings:

```
LaTeX Font Warning: Font shape `TU/Garamond-math.otf(1)/bx/n' undefined
(Font)              using `TU/Garamond-math.otf(1)/m/n' instead on input line 1
02.

LaTeX Font Warning: Font shape `TU/Garamond-math.otf(2)/bx/n' undefined
(Font)              using `TU/Garamond-math.otf(2)/m/n' instead on input line 1
02.

LaTeX Font Warning: Font shape `TU/Garamond-math.otf(3)/bx/n' undefined
(Font)              using `TU/Garamond-math.otf(3)/m/n' instead on input line 1
02.
```

these are all caused by the line `bold text siunitx`, as by commenting out this line makes the warnings disappear. Note also that there are some issues with Denominators/Subscripts/ScientificInferiors in the case of `SourceSansPro`, `SourceCodePro`, as calling `\addfontfeatures{RawFeature=+dnom/+subs/+sinf}` does not work, even though the fonts do have this feature available.

**Comment by septatrix** [comment]
> I'm aware of issues with Unicode fonts: the underlying assumptions are very different from classical TeX. I'm working on v3 of `siunitx` which should I think sort all of this, but by using an entirely different approach to font control (in the end this is _necessary_). Hopefully some progress is happening: I'll see if I can sort the immediate issue for v2.

Can v3 already be tested somewhere? Is it the current master branch or do you develop somewhere privately? I would like to try the font handling as I also am using two fonts with different digits for text and math mode and this really stand out in a display math environment...

**Comment by josephwright** [comment]
It's the current master branch

**Comment by septatrix** [comment]
I tried the alpha 2 version from the release page and it looks great so far. It does exactly what I want and I also like the new interface - thanks for the great work so far!

**Comment by josephwright** [comment]
This is fixed in v3 - plan is to release by the autumn (I am hoping for a beta by June)
