### ISSUE TITLE
feature request: realsupersubscripts

### ISSUE THREAD

**Issue by itzsimpl** [josephwright/siunitx#339]
As some typefaces have specifically designed subscripts and superscripts, would it be possible to configure `siunitx` to use those at least for text output? See for example the package `realscripts,` which implements the functions `\textsuperscript,` `\textsubscript,` and `\textsubsuperscript.` With it and by adding into the preamble `\cs_set_eq:NN \__siunitx_print_text_super:n \textsuperscript` and `\cs_set_eq:NN \__siunitx_print_text_sub:n \textsubscript` I was able to achieve what I want for subscripts and superscripts when printing numbers in text mode, but the solution fails when printing superscripts in text mode.

**Comment by josephwright** [comment]
The concern I have here is that the output might be different between text and math mode where the font is the same: there's a reason the current code doesn't simply use `\textsuperscript`/`\textsubscript` (compare the vertical positions of glyphs). I'll think about it.

**Comment by itzsimpl** [comment]
Professionally designed superscripts and subscripts have a visual weight that matches other characters better than a faked version (faked with a scaled down version of the original characters). I would assume that in the context of `siunitx` one can restrict themselves to pure subscripts and superscripts (i.e. no sub-sub, sup-sup, sub-sup … second level versions). In this sense it would be a shame to miss on a professionally designed font feature. 

To be clear, the vertical positioning is precisely why I am voting for this feature. 
If you compare 

![image](https://user-images.githubusercontent.com/4784070/40614108-9399654a-6281-11e8-810c-b1f1a9b0e969.png)

obtained with
`$\symrm{{kg}_{pol}^{2}\,{mol}_{cat}^{-1}\,{h}^{-1}}$`
and
`kg\textsubsuperscript{pol}{2}\,mol\textsubsuperscript{cat}{-1}\,h\textsuperscript{-1}`
you will notice that in math mode 1) the subscripts and superscripts are larger. But what really bothers me is that in math mode 2) the baselines of the subscripts are not vertical aligned ('cat' is positioned higher than 'pol'). 

The only problem I see with `\textsubscript,` `\textsuperscirpt` is that frequently only a subset of characters is included in the sub/superscript range (e.g. missing special symbols like math minus, plusminus, greek letters,...).

**Comment by josephwright** [comment]
@itzsimpl That's rather the point: the two outcomes need to be the same _irrespective_ of the choice of text/math mode ...

**Comment by josephwright** [comment]
(Aside: sub/superscripts aren't scaled down, at least with CM, they are taken from a font with a different design size ...)

**Comment by josephwright** [comment]
The new code in v3 works very hard to produce the same lower-level LaTeX as one would type in by hand. As such, I think that should push this issue 'along'.

**Comment by josephwright** [comment]
This is covered by #595.
