### ISSUE TITLE
top-level defs of units or \per etc

### ISSUE THREAD

**Issue by FrankMittelbach** [josephwright/siunitx#341]
The top-level def of `\to` is its usual math definition but if one checks the definition of `\metre` or `\per`the expansion is `\ERROR`.

Wouldn't it be better to leave them undefined at top-level ( or rather whatever they are outside `\si`)? That way users can define their own definition and that works identically whether or not the definition is done before or after loading `siunitx`.

**Comment by josephwright** [comment]
The definitions here are provided using the `\AtBeginDocument` hook, so only where there is no other global definition active. They are set up for a couple of reasons:

- In the current release, I provide an `s` column for units. As TeX tries to expand tokens at the start of cells, having units globally undefined is an issue there! In the development code, I'm planning to drop this feature: it's easy to achieve something similar using `collcell` and `\unit` (or `\si` if I don't rename it).

- Where units appear in an expansion context, they need to be defined. This is most obvious in `pgfplots`, where something like `\addlegendentryexpanded{\SI{\x}{\volt}` might reasonably come up in a plot (I use that type of construct). Having to add `\noexpand` everywhere is a pain and non-consistent ...

**Comment by FrankMittelbach** [comment]
ok makes sense
