### ISSUE TITLE
Zero uncertainty causes error

### ISSUE THREAD

**Issue by ross-chaudhry** [josephwright/siunitx#349]
Consider the following test code:
```
\documentclass{article}
\usepackage{siunitx}
\begin{document}
\num{1 \pm 0}
\end{document}
```
On my machine, I get:
```
$ pdflatex tmp.tex 
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016) (preloaded format=pdflatex)
<SNIPPED>
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! siunitx error: "misplaced-sign-token"
! 
! Misplaced sign token '1 \pm 0'.
! 
! See the siunitx documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.5 \num{1 \pm 0}
                 
? 
```
This does not occur if the syntax `\num{1 (0)}` is used instead. Presumably this is a bug? In my testing, it occurs every time an uncertainty of zero is specified using the separate uncertainty form (with `\pm`). The version of `siunitx` is:
```
Package: siunitx 2016/03/01 v2.6q A comprehensive (SI) units package
```
Note: Often, one should never have 0 uncertainty - either the quantity is exact (no uncertainty) or it is not (must have nonzero uncertainty). Under certain conditions, though, an inexact quantity does have 0 uncertainty. For example, the probability of an event occurring, if it happens for *every* sample, is 1, with an estimated uncertainty of 0.

**Comment by josephwright** [comment]
I agree this is a bug, but it's very much an edge case: I'm tempted to leave this for v3.

**Comment by ross-chaudhry** [comment]
I don't have a problem with leaving it for now - it's rare and produces a full error. So there's no risk of a user not noticing the output is wrong. Plus, the workaround is easy.
