### ISSUE TITLE
degree doesn't work, celsius does

### ISSUE THREAD

**Issue by jmarrec** [josephwright/siunitx#351]
https://github.com/josephwright/siunitx/blob/12849f31d93b48e70a927b23d56b6a39dc98cf5f/siunitx-unit.dtx#L2265

https://github.com/josephwright/siunitx/blob/12849f31d93b48e70a927b23d56b6a39dc98cf5f/siunitx-unit.dtx#L2340

Could the problem be that `\degreeCelsius` uses `\ensuremath` while `\degree` doesn't?

**Comment by jmarrec** [comment]
I have the same exact problem with `\ang{10}` too.

**Comment by jmarrec** [comment]
If I overwrite degree like this 

```
\DeclareSIUnit[number-unit-product = \,]
\degree{ \ensuremath { { } ^ { \circ } } }
```

Then it works fine.

**Comment by josephwright** [comment]
Not sure I follow: you've linked to the unreleased v3 code .... could I have a full example?

**Comment by jmarrec** [comment]
@josephwright https://gist.github.com/jmarrec/a3c4d493eeef8d5f5520f8e0ee695018

Built with `xelatex test.tex`, result:

![image](https://user-images.githubusercontent.com/5479063/47165165-be86e000-d2f9-11e8-855c-cd47323130da.png)

**Comment by jmarrec** [comment]
I've installed the latest texlive (tex --version = TeX 3.14159265 (TeX Live 2019/dev/Debian)), and that gives my siunitx 2.7k. Same problem.

If I clean up my tex file and only keep the siunitx package it works as expected though, so I suppose there's something conflicting. But still adding \ensuremath to the \degree one at least make it work with my config. Didn't find a way to properly redefine the \ang macro though.

**Comment by e-kwsm** [comment]
The MWE is
```tex
\documentclass{article}
\usepackage{mathspec}
\usepackage{siunitx}
\begin{document}
ang: \ang{180}
degree: \SI{180}{\degree}

Celsius: \SI{180}{\celsius}
\end{document}
```

and `mathspec` causes the situation.

**Comment by josephwright** [comment]
It's a documented feature of of `siunitx` v2 that non-standard font set ups (which include anything involving system fonts) may need manual adjustment. The upcoming v3 code will address much of this, as the font control approach is entirely different. I anticipate a release of the new code around the end of this year, depending on how I get on with the remaining issues.

**Comment by jmarrec** [comment]
Thank you both for your help on this. I’ll close the issue as there isn’t really any action needed (perhaps a FAQ section on the readme could be an idea).

**Comment by mrpiggi** [comment]
With v3 this issue is still present as `\degree` does not print anything:
```latex
\documentclass{article}
\usepackage[no-math]{fontspec}
\usepackage{siunitx}
\begin{document}
ang: \ang{180}
degree: \SI{180}{\degree}?
Celsius: \SI{180}{\celsius}?
\end{document}
```

**Comment by josephwright** [comment]
Hmm, that's a tricky one: @wspr is there an official interface to know if `no-math` is active or not?

**Comment by josephwright** [comment]
@mrpiggi Could you open a new issue on this? The one here was really about a mess-up in released v3 code, whereas your one is about 'partial' usage of `fontspec`.

**Comment by wspr** [comment]
@josephwright — there is no official interface to test for this but I’d be happy to add one… of course, saying and doing are two different things for me at the moment :-(

**Comment by josephwright** [comment]
@wspr I think for the moment I'll simply not worry about `fontspec` being loaded: it's not absolutely essential to do that test.
