### ISSUE TITLE
expand-to-prefix combined with scientific-notation=engineering leads to infinite loop

### ISSUE THREAD

**Issue by Garonenur** [josephwright/siunitx#353]
I know that the option `expand-to-prefix` is quite new and has a few problems, but with this:
```tex
\documentclass[]{report}
\usepackage[]{siunitx}

\sisetup{
  scientific-notation=engineering,
  exponent-to-prefix,
}
\begin{document}

\SI{123}{x}, % the following produce infinite loops:
% \SI{1234}{x},
% \SI{1234567890}{x},
% \SI{1234}{\kilo x}

% these do not:
\SI{1234}{\kilo\g}

\sisetup{exponent-to-prefix=false}

\SI{1234}{x}

\SI{1234}{\kilo x}
\end{document}
```
I get infinite loops, resulting in latex hanging without any error produced.

Is there a way to get around this? Or at least check this and produce an error, so one does not wonder why compilation takes so much longer than usual ;)

**Comment by josephwright** [comment]
I'm not exactly surprised: you are trying to convert 'literal' units to use a prefix. However, that should probably yield an error. I'll check this for v3 (I doubt I'll make any more changes to v2).

**Comment by josephwright** [comment]
Fixed in v3
