### ISSUE TITLE
Babel Spanish + "<" and ">" input-comparators problems

### ISSUE THREAD

**Issue by ilario** [josephwright/siunitx#355]
I'm having errors when using < and > in combination with Spanish in Babel.
The other comparators (=, \sim, \ge...) works as expected.
Some other languages in Babel (I tried just Italian and English) does not trigger the error.

Minimal NON working example:

```
\documentclass{article}
\usepackage[spanish]{babel}
\usepackage{siunitx}

\begin{document}
T is \SI{< 200}{\kelvin}.

T is \SI{> 200}{\kelvin}.
\end{document}
```

Output:

```
T is .
T is .
```

Error messages:

```
! Package siunitx Error: Invalid token '<' in numerical input.
! Package siunitx Error: Invalid numerical input '<200'.
```
Thanks

**Comment by josephwright** [comment]
Hmm, I'm amazed that hasn't come up before. I'll give it a bit of thought: I guess I need to work out whether I should deal with actives in the parsing stage.

**Comment by nignasi** [comment]
I think `es-noquoting` option (see http://texdoc.net/texmf-dist/doc/generic/babel-spanish/spanish.pdf 
 page 12) solves the problem unless you need to use spanish quotes.

```
\documentclass{article}
\usepackage[spanish, es-noquoting]{babel}
\usepackage{siunitx}

\begin{document}
T is \SI{< 200}{\kelvin}.

T is \SI{> 200}{\kelvin}.
\end{document}
```

**Comment by josephwright** [comment]
I'm discussing with the rest of the LaTeX team: I'm wondering if this needs a mechanism in `expl3` (it's a gneral issue).

**Comment by Rmano** [comment]
@josephwright  I'm not sure it's related, but `babel-spanish` has also a couple of problem with `~`, even with `shorthands=off`: https://github.com/latex3/babel/issues/38 and https://github.com/latex3/babel/issues/39 (they are marked closed because Jeff moved them to the `babel-spanish` repo, but FWIK they are still here)
