### ISSUE TITLE
brackets-power not resolving within silist

### ISSUE THREAD

**Issue by c3h899** [josephwright/siunitx#356]
Use of the "product-units = brackets-power" option for SIlists does not yield consistent results with usage of SI call. Appears SIlist is not translating the bracketed units.

Usage:
\SIlist[product-units =  brackets-power]{10 x 20;30 x 40}{\meter}

Returns "(10 x 20 and 30 x 40) m"
When Expecting "(10 x 20 and 30 x 40) m^2"

This holds true for single-element lists. Such is fundamentally inconsistent with the corresponding SI:
\SI[product-units =  brackets-power]{10 x 20}{\meter}

Which returns "(10 x 20) m^2"

**Comment by josephwright** [comment]
To be honest, this looks well outside of the range of cases I wrote `\SIlist` to support. At least I should issue some kind of warning ...

**Comment by josephwright** [comment]
My plans for v3 separate out the idea of products from 'general' quantities, so this ends up as 'wont fix' in that I'm not going to support that use case.
