### ISSUE TITLE
causes an error with Unicode characters

### ISSUE THREAD

**Issue by vinc17fr** [josephwright/siunitx#358]
Under Debian/unstable, when I use siunitx in the following document:
```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{siunitx}
\DeclareUnicodeCharacter{00B1}{\ensuremath{\pm}}
\DeclareUnicodeCharacter{00B7}{\ensuremath{\cdot}}
\begin{document}
Plus or minus: $±$ and ±.
Cdot: $·$ and ·.
\end{document}
```
latex gives the following error:
```
! Undefined control sequence.
<argument> \textpm 
                   
l.7 Plus or minus: $±
                      $ and ±.
```
The cause seems to be that using siunitx has the effect to load /usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu, and its character definitions do not work.

This was my original bug report in the Debian BTS: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=683620

**Comment by josephwright** [comment]
In v2, `siunitx` loads 'just enough' `textcomp` to work. Here, that means that underlying code assumes `\textcomp` is defined, hence the issue. In v3 (development) I have a slightly different take, but that only takes us from an error to a missing glyph. I'd suggest that you want to delay your change
```latex
\AtBeginDocument{\DeclareUnicodeCharacter{00B1}{\ensuremath{\pm}}}
```
as that will fix things.
