### ISSUE TITLE
S column + math mode + sign => invalid numerical input '-'

### ISSUE THREAD

**Issue by Arkonos** [josephwright/siunitx#359]
The S column type has troubles with signs and maths environment.
I can use the second line as a workaround, but it's less desirable.

    \documentclass[10pt,a4paper]{article}
    \usepackage[utf8x]{inputenc}
    \usepackage{siunitx}
    \begin{document}
      \begin{table}
        \begin{tabular}{S}
           $\frac{1}{2}$ \\ % works
           $\frac{-1}{2}$ \\ % works
          -$\frac{1}{2}$    % breaks
        \end{tabular}
      \end{table}
    \end{document}

Error: `Package siunitx Error: Invalid numerical input '-'. \end`

<details>
<summary>Log File</summary>
<p>This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018/Arch Linux) (preloaded format=pdflatex 2019.4.25)  12 MAY 2019 03:16
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**bug.tex
(./bug.tex
LaTeX2e <2018-12-01>
(/usr/share/texmf-dist/tex/latex/base/article.cls
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
(/usr/share/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2018/09/03 v1.4i Standard LaTeX file (size option)
)
\c@part=\count80
\c@section=\count81
\c@subsection=\count82
\c@subsubsection=\count83
\c@paragraph=\count84
\c@subparagraph=\count85
\c@figure=\count86
\c@table=\count87
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
)
(/usr/share/texmf-dist/tex/latex/base/inputenc.sty
Package: inputenc 2018/08/11 v1.3c Input encoding file
\inpenc@prehook=\toks14
\inpenc@posthook=\toks15

(/usr/share/texmf-dist/tex/latex/ucs/utf8x.def
File: utf8x.def 2004/10/17 UCS: Input encoding UTF-8
))
(/usr/share/texmf-dist/tex/latex/ucs/ucs.sty
Package: ucs 2013/05/11 v2.2 UCS: Unicode input support

(/usr/share/texmf-dist/tex/latex/ucs/data/uni-global.def
File: uni-global.def 2013/05/13 UCS: Unicode global data
)
\uc@secondtry=\count88
\uc@combtoks=\toks16
\uc@combtoksb=\toks17
\uc@temptokena=\toks18
)
(/usr/share/texmf-dist/tex/latex/siunitx/siunitx.sty
(/usr/share/texmf-dist/tex/latex/l3kernel/expl3.sty
Package: expl3 2019-02-15 L3 programming layer (loader) 

(/usr/share/texmf-dist/tex/latex/l3kernel/expl3-code.tex
Package: expl3 2019-02-15 L3 programming layer (code)
\c_max_int=\count89
\l_tmpa_int=\count90
\l_tmpb_int=\count91
\g_tmpa_int=\count92
\g_tmpb_int=\count93
\g__kernel_prg_map_int=\count94
\c_log_iow=\count95
\l_iow_line_count_int=\count96
\l__iow_line_target_int=\count97
\l__iow_one_indent_int=\count98
\l__iow_indent_int=\count99
\c_zero_dim=\dimen103
\c_max_dim=\dimen104
\l_tmpa_dim=\dimen105
\l_tmpb_dim=\dimen106
\g_tmpa_dim=\dimen107
\g_tmpb_dim=\dimen108
\c_zero_skip=\skip43
\c_max_skip=\skip44
\l_tmpa_skip=\skip45
\l_tmpb_skip=\skip46
\g_tmpa_skip=\skip47
\g_tmpb_skip=\skip48
\c_zero_muskip=\muskip10
\c_max_muskip=\muskip11
\l_tmpa_muskip=\muskip12
\l_tmpb_muskip=\muskip13
\g_tmpa_muskip=\muskip14
\g_tmpb_muskip=\muskip15
\l_keys_choice_int=\count100
\l__intarray_loop_int=\count101
\c__intarray_sp_dim=\dimen109
\g__intarray_font_int=\count102
\c__fp_leading_shift_int=\count103
\c__fp_middle_shift_int=\count104
\c__fp_trailing_shift_int=\count105
\c__fp_big_leading_shift_int=\count106
\c__fp_big_middle_shift_int=\count107
\c__fp_big_trailing_shift_int=\count108
\c__fp_Bigg_leading_shift_int=\count109
\c__fp_Bigg_middle_shift_int=\count110
\c__fp_Bigg_trailing_shift_int=\count111
\c__kernel_randint_max_int=\count112
\g__fp_array_int=\count113
\l__fp_array_loop_int=\count114
\l__sort_length_int=\count115
\l__sort_min_int=\count116
\l__sort_top_int=\count117
\l__sort_max_int=\count118
\l__sort_true_max_int=\count119
\l__sort_block_int=\count120
\l__sort_begin_int=\count121
\l__sort_end_int=\count122
\l__sort_A_int=\count123
\l__sort_B_int=\count124
\l__sort_C_int=\count125
\l__tl_analysis_normal_int=\count126
\l__tl_analysis_index_int=\count127
\l__tl_analysis_nesting_int=\count128
\l__tl_analysis_type_int=\count129
\l__regex_internal_a_int=\count130
\l__regex_internal_b_int=\count131
\l__regex_internal_c_int=\count132
\l__regex_balance_int=\count133
\l__regex_group_level_int=\count134
\l__regex_mode_int=\count135
\c__regex_cs_in_class_mode_int=\count136
\c__regex_cs_mode_int=\count137
\l__regex_catcodes_int=\count138
\l__regex_default_catcodes_int=\count139
\c__regex_catcode_D_int=\count140
\c__regex_catcode_S_int=\count141
\c__regex_catcode_L_int=\count142
\c__regex_catcode_O_int=\count143
\c__regex_catcode_A_int=\count144
\c__regex_all_catcodes_int=\count145
\l__regex_show_lines_int=\count146
\l__regex_min_state_int=\count147
\l__regex_max_state_int=\count148
\l__regex_left_state_int=\count149
\l__regex_right_state_int=\count150
\l__regex_capturing_group_int=\count151
\l__regex_min_pos_int=\count152
\l__regex_max_pos_int=\count153
\l__regex_curr_pos_int=\count154
\l__regex_start_pos_int=\count155
\l__regex_success_pos_int=\count156
\l__regex_curr_char_int=\count157
\l__regex_curr_catcode_int=\count158
\l__regex_last_char_int=\count159
\l__regex_case_changed_char_int=\count160
\l__regex_curr_state_int=\count161
\l__regex_step_int=\count162
\l__regex_min_active_int=\count163
\l__regex_max_active_int=\count164
\l__regex_replacement_csnames_int=\count165
\l__regex_match_count_int=\count166
\l__regex_min_submatch_int=\count167
\l__regex_submatch_int=\count168
\l__regex_zeroth_submatch_int=\count169
\g__regex_trace_regex_int=\count170
\c_empty_box=\box27
\l_tmpa_box=\box28
\l_tmpb_box=\box29
\g_tmpa_box=\box30
\g_tmpb_box=\box31
\l__box_top_dim=\dimen110
\l__box_bottom_dim=\dimen111
\l__box_left_dim=\dimen112
\l__box_right_dim=\dimen113
\l__box_top_new_dim=\dimen114
\l__box_bottom_new_dim=\dimen115
\l__box_left_new_dim=\dimen116
\l__box_right_new_dim=\dimen117
\l__box_internal_box=\box32
\l__coffin_internal_box=\box33
\l__coffin_internal_dim=\dimen118
\l__coffin_offset_x_dim=\dimen119
\l__coffin_offset_y_dim=\dimen120
\l__coffin_x_dim=\dimen121
\l__coffin_y_dim=\dimen122
\l__coffin_x_prime_dim=\dimen123
\l__coffin_y_prime_dim=\dimen124
\c_empty_coffin=\box34
\l__coffin_aligned_coffin=\box35
\l__coffin_aligned_internal_coffin=\box36
\l_tmpa_coffin=\box37
\l_tmpb_coffin=\box38
\g_tmpa_coffin=\box39
\g_tmpb_coffin=\box40
\c__coffin_empty_coffin=\box41
\l__coffin_display_coffin=\box42
\l__coffin_display_coord_coffin=\box43
\l__coffin_display_pole_coffin=\box44
\l__coffin_display_offset_dim=\dimen125
\l__coffin_display_x_dim=\dimen126
\l__coffin_display_y_dim=\dimen127
\g__file_internal_ior=\read1
\l__coffin_bounding_shift_dim=\dimen128
\l__coffin_left_corner_dim=\dimen129
\l__coffin_right_corner_dim=\dimen130
\l__coffin_bottom_corner_dim=\dimen131
\l__coffin_top_corner_dim=\dimen132
\l__coffin_scaled_total_height_dim=\dimen133
\l__coffin_scaled_width_dim=\dimen134
\l__seq_internal_a_int=\count171
\l__seq_internal_b_int=\count172
)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3pdfmode.def
File: l3pdfmode.def 2019-02-15 v L3 Experimental driver: PDF mode
\l__driver_color_stack_int=\count173
))
(/usr/share/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
Package: xparse 2018-10-17 L3 Experimental document command parser
\l__xparse_current_arg_int=\count174
\g__xparse_grabber_int=\count175
\l__xparse_m_args_int=\count176
\l__xparse_mandatory_args_int=\count177
\l__xparse_v_nesting_int=\count178
)
Package: siunitx 2018/05/17 v2.7s A comprehensive (SI) units package

(/usr/share/texmf-dist/tex/latex/amsmath/amstext.sty
Package: amstext 2000/06/29 v2.01 AMS text

(/usr/share/texmf-dist/tex/latex/amsmath/amsgen.sty
File: amsgen.sty 1999/11/30 v2.0 generic functions
\@emptytoks=\toks19
\ex@=\dimen135
))
(/usr/share/texmf-dist/tex/latex/tools/array.sty
Package: array 2018/12/30 v2.4k Tabular extension package (FMi)
\col@sep=\dimen136
\ar@mcellbox=\box45
\extrarowheight=\dimen137
\NC@list=\toks20
\extratabsurround=\skip49
\backup@length=\skip50
\ar@cellbox=\box46
)
(/usr/share/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty
Package: l3keys2e 2018-10-17 LaTeX2e option processing using LaTeX3 keys
)
\l__siunitx_tmp_box=\box47
\l__siunitx_tmp_dim=\dimen138
\l__siunitx_tmp_int=\count179
\l__siunitx_number_mantissa_length_int=\count180
\l__siunitx_number_uncert_length_int=\count181
\l__siunitx_round_int=\count182
\l__siunitx_process_decimal_int=\count183
\l__siunitx_process_uncertainty_int=\count184
\l__siunitx_process_fixed_int=\count185
\l__siunitx_process_integer_min_int=\count186
\l__siunitx_process_precision_int=\count187
\l__siunitx_group_min_int=\count188
\l__siunitx_angle_marker_box=\box48
\l__siunitx_angle_unit_box=\box49
\l__siunitx_angle_marker_dim=\dimen139
\l__siunitx_angle_unit_dim=\dimen140
\l__siunitx_unit_int=\count189
\l__siunitx_unit_denominator_int=\count190
\l__siunitx_unit_numerator_int=\count191
\l__siunitx_unit_prefix_int=\count192
\l__siunitx_unit_prefix_base_int=\count193
\l__siunitx_unit_prefix_gram_int=\count194
\l__siunitx_number_product_int=\count195
\c__siunitx_one_fill_skip=\skip51
\l__siunitx_table_unit_align_skip=\skip52
\l__siunitx_table_exponent_dim=\dimen141
\l__siunitx_table_integer_dim=\dimen142
\l__siunitx_table_mantissa_dim=\dimen143
\l__siunitx_table_marker_dim=\dimen144
\l__siunitx_table_result_dim=\dimen145
\l__siunitx_table_uncert_dim=\dimen146
\l__siunitx_table_fill_pre_dim=\dimen147
\l__siunitx_table_fill_post_dim=\dimen148
\l__siunitx_table_fill_mid_dim=\dimen149
\l__siunitx_table_pre_box=\box50
\l__siunitx_table_post_box=\box51
\l__siunitx_table_mantissa_box=\box52
\l__siunitx_table_result_box=\box53
\l__siunitx_table_number_align_skip=\skip53
\l__siunitx_table_text_align_skip=\skip54

(/usr/share/texmf-dist/tex/latex/translator/translator.sty
Package: translator 2018/01/04 v1.12 Easy translation of strings in LaTeX

(/usr/share/texmf-dist/tex/latex/graphics/keyval.sty
Package: keyval 2014/10/28 v1.15 key=value parser (DPC)
\KV@toks@=\toks21
))) (./bug.aux)
\openout1 = `bug.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.

(/usr/share/texmf-dist/tex/latex/ucs/ucsencs.def
File: ucsencs.def 2011/01/21 Fixes to fontencodings LGR, T3
)
(/usr/share/texmf-dist/tex/latex/translator/translator-basic-dictionary-English
.dict
Dictionary: translator-basic-dictionary, Language: English 
) (/usr/share/texmf-dist/tex/latex/siunitx/siunitx-abbreviations.cfg
File: siunitx-abbreviations.cfg 2017/11/26 v2.7k siunitx: Abbreviated units
)
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <7> on input line 4.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <5> on input line 4.

! Package siunitx Error: Invalid numerical input '-'.

For immediate help type H <return>.
 ...                                              
                                                  
l.9 		\end
          {tabular}

The input given as a number does not make logical sense. This happens, for
example, if a number only contains a sign.

[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (./bug.aux) ) 
Here is how much of TeX's memory you used:
 12318 strings out of 492616
 259864 string characters out of 6135177
 281109 words of memory out of 5000000
 16243 multiletter control sequences out of 15000+600000
 533747 words of font info for 30 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 40i,10n,63p,323b,317s stack positions out of 5000i,500n,10000p,200000b,80000s
</usr/share
/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb></usr/share/texmf-dist/fon
ts/type1/public/amsfonts/cm/cmr7.pfb>
Output written on bug.pdf (1 page, 15539 bytes).
PDF statistics:
 16 PDF objects out of 1000 (max. 8388607)
 10 compressed objects within 1 object stream
 0 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)
</p>
</details>

**Comment by josephwright** [comment]
In all three cases, you are relying on the fact that `siunitx` will automatically pick up non-numerical content and set it before a number. The moment you put in `$`, you are effectively forcing  `siunitx` to parse as 'non-numerical'. You have a couple of options. First, you could turn off the number parser for the entire column. There's a slight wrinkle that you'll want to make `\frac` robust to make that work:
```latex
\documentclass[10pt,a4paper]{article}
\usepackage{siunitx}
\usepackage{etoolbox}
\robustify\frac
\begin{document}
  \begin{table}
    \begin{tabular}{S[parse-numbers = false]}
       \frac{1}{2}  \\
       \frac{-1}{2} \\
      -\frac{1}{2}  \\
    \end{tabular}
  \end{table}
\end{document}
```
Secondly, you could tell `siunitx` that the whole content of the cell is 'textual' by wrapping in braces
```latex
\documentclass[10pt,a4paper]{article}
\usepackage{siunitx}
\begin{document}
  \begin{table}
    \begin{tabular}{S}
       {$\frac{1}{2}$}  \\
       {$\frac{-1}{2}$} \\
       {$-\frac{1}{2}$} \\
    \end{tabular}
  \end{table}
\end{document}
```
