### ISSUE TITLE
List of all supported units?

### ISSUE THREAD

**Issue by ep12** [josephwright/siunitx#360]
Is there a list with all supported units? A simple txt list or table? I need to check that the tex code my script exports can only contain supported units... Or maybe a grep, sed, awk whatever command I can run to generate such a list?

**Comment by josephwright** [comment]
Best to query the package itself here. For example
```latex
\documentclass{article}
\usepackage{siunitx}
\begin{document}

\ExplSyntaxOn

\iow_open:Nn \g_tmpa_iow { siunitx-units.txt }
\seq_map_inline:Nn \l_siunitx_unit_symbolic_seq
  {
    \iow_now:Nn \g_tmpa_iow  {#1}
  }
\ExplSyntaxOff

\end{document}
```
will create `siunitx-unitx.txt` listing every 'symbolic' unit known.

**Comment by ep12** [comment]
That is exactly what I was searching for! Thanks a lot for the quick reply! :+1: :smile:
