### ISSUE TITLE
Prefixes with /decibel give an error.

### ISSUE THREAD

**Issue by DmasterD** [josephwright/siunitx#361]
For my document I'd like to use milli decibels (mdB), but siunitx gives an error, see the following code:

    \documentclass{article}
    \usepackage{siunitx}
    \begin{document}
    \SI{1}{\milli\decibel}
    \end{document}

The other prefixes don't seem to work either.
The `scientific-notation = engineering` can't handle this stuff, which gives some error about an exponent not being able to be converted to a prefix.

**Comment by josephwright** [comment]
The decibel is already a prefixed unit: its a tenth of a bel. Now, the bel is hardly ever used, so it's a bit odd, but formally the base unit here is not a decibel. Can you point to people using the unit in the way you've requested?

**Comment by DmasterD** [comment]
Well, milli decibel would be used less than decibel, like near to none.
I can only point to the circuit simulator I use, LTSpice, which shows mdB for values between -1 and 1.
It just happened on accident that I had some values between -1 dB and 1 dB for the outputs of my amplifiers.

I've got the engineering notation set for my whole document, so it automatically tried to put these prefixes in front of dB.
I guess would make more sense if you'd prevent engineering prefixes from being put in front of decibel.

**Comment by josephwright** [comment]
You could simply re-declare the unit with options
```latex
\documentclass{article}
\usepackage{siunitx}
\DeclareSIUnit[scientific-notation = false]{\decibel}{\deci\bel}
\sisetup{scientific-notation = true}
\begin{document}
\SI{1000}{\metre} but \SI{1000}{\decibel}.
\end{document}
```

**Comment by DmasterD** [comment]
That's a nice solution for my document. I'm statisfied with that. 🙂
Well then, if anyone ever gets this error, hopefully they'll find this solution too.
