### ISSUE TITLE
ENH: Small improvement to documentation, section "Symbols and XETEX"

### ISSUE THREAD

**Issue by jakobjakobson13** [josephwright/siunitx#363]
Dear Joseph,

if you change the code snippet in the section 7.6 "Symbols and XETEX" from
```latex
\sisetup{
math-micro = \text{μ},
text-micro = μ
}
```
to
```latex
\sisetup{
math-micro = \text{\textmu},
text-micro = \textmu
}
```
the code works for pdflatex AND xetex. And the textcomp package is part of the latex distribution, so that should work without any problems.
Perhaps you could also set the second code snippet as the default configuration, then you could delete the subsection.

Regards

Jakob

**Comment by josephwright** [comment]
The v3 code handles this much more cleanly: closing.
