### ISSUE TITLE
Insert negative kerning between exponent and per-slash

### ISSUE THREAD

**Issue by schtandard** [josephwright/siunitx#364]
As discussed in [this StackExchange question][sxquestion] and on page 169 of the TeXbook, the spacing in `\(x^2 \! / 2\)` is preferable to the one in `\(x^2 / 2\)`. While the literal input `\si{cm^3 / s}` should not be changed in this way, it would be nice for the macro input `\si[per-mode=symbol]{\cubic\centi\meter\per\second}` to produce the nicer spacing.

- Maybe only if `per-mode` is `/`?
- There should be an option to turn this feature off.
- The amount of kerning inserted could also be an option.

[sxquestion]: https://tex.stackexchange.com/questions/501304/space-after-exponent-for-si-command-using-siunitx-package

**Comment by josephwright** [comment]
I'm going to 'future' this

**Comment by josephwright** [comment]
I have a mechanism for this set up, just have to agree on the final details - exactly what to correct with

**Comment by eg9** [comment]
The correction is font dependent. Using Unicode math fonts for simplicity of setup, we can see what happens.

```latex
\documentclass{article}
\usepackage{unicode-math}

\setmathfont{Latin Modern Math}
\setmathfont{STIX Two Math}[version=stix]
\setmathfont{TeX Gyre Termes Math}[version=tgt]

\newcommand{\test}{$\mathrm{m}^3/\mathrm{s}$}
\newcommand{\testthin}{$\mathrm{m}^3\!/\mathrm{s}$}
\newcommand{\testscr}{$\mathrm{m}^3\kern-\scriptspace/\mathrm{s}$}

\begin{document}

\test~--~\testthin~--~\testscr

\mathversion{stix}
\test~--~\testthin~--~\testscr

\mathversion{tgt}
\test~--~\testthin~--~\testscr

\end{document}
```

<img width="390" alt="image" src="https://user-images.githubusercontent.com/302839/160483523-55714237-ce89-42a9-aa78-d76a95538047.png">

In all cases, `\kern-\scriptspace` seems too small a correction. But for STIX Two, `\!` seems too much, while it seems good for Latin Modern and for TeX Gyre Termes.

Probably an option to set the amount of kerning, with default value `\!`, that is, `\mkern-3mu` seems to be the best strategy.
