### ISSUE TITLE
round-mode=figures failes for number an epsilon smaller than 1

### ISSUE THREAD

**Issue by T-F-S** [josephwright/siunitx#365]
Using `round-mode=figures` for numbers which are a little bit smaller than 1 add a further zero to the output. This does not happen for e.g. numbers which are a little bit smaller than 2.

Consider the following example which should produce output with 3 valid figures:

```latex
\documentclass{article}

\usepackage{siunitx}
\sisetup{round-mode=figures,round-precision=3,round-integer-to-decimal}

\begin{document}

\num{0.9999} (problem)

\num{1}

\num{1.0000}

\num{1.0001}

\num{1.9999}

\num{2}

\num{2.0000}

\num{2.0001}

\end{document}
```

![siunitx-365-output](https://user-images.githubusercontent.com/7982989/62767140-49f17d80-ba94-11e9-86e9-66407e849c7f.png)

**Comment by josephwright** [comment]
This is fixed in v3-alpha-1, which I'm back working on: hopefully a usable release by the end of the year (beta at least). I'll close on the grounds will be sorted 'real soon now'.
