### ISSUE TITLE
extra dash in \numrange

### ISSUE THREAD

**Issue by matsievskiysv** [josephwright/siunitx#368]
When `\numrange` is configured to use `\text{\ensuremath{-}}` as a range separator, compilation result depends on spaces between key-value argument pairs in `\usepackage`.

This example
```latex
\documentclass{article}

\usepackage{amsmath}
\usepackage[range-phrase={\text{\ensuremath{-}}}]{siunitx}

\begin{document}
Text \numrange{1}{2}

Equation \(\numrange{1}{2}\)
\end{document}
```
compiles to
![image](https://user-images.githubusercontent.com/26824900/69043756-b3bee300-0a04-11ea-9d84-1e6a8dee12ee.png)

If space is added after `range-phrase=`:
```latex
\documentclass{article}

\usepackage{amsmath}
\usepackage[range-phrase= {\text{\ensuremath{-}}}]{siunitx}

\begin{document}
Text \numrange{1}{2}

Equation \(\numrange{1}{2}\)
\end{document}
```
then compilation result has extra dash between range numbers.
![image](https://user-images.githubusercontent.com/26824900/69043833-d6e99280-0a04-11ea-9af4-0be22543692d.png)

This issue arose after the latest Debian texlive update.

#### Versions

Latexmk, John Collins, 18 June 2019. Version 4.65
This is LuaTeX, Version 1.10.0 (TeX Live 2019/Debian)
 article.cls    2019/10/25 v1.4k Standard LaTeX document class
  size10.clo    2019/10/25 v1.4k Standard LaTeX file (size option)
 amsmath.sty    2019/04/01 v2.17c AMS math features
 amstext.sty    2000/06/29 v2.01 AMS text
  amsgen.sty    1999/11/30 v2.0 generic functions
  amsbsy.sty    1999/11/29 v1.2d Bold Symbols
  amsopn.sty    2016/03/08 v2.02 operator names
 siunitx.sty    2019/10/10 v2.7t A comprehensive (SI) units package
   expl3.sty    2019-11-07 L3 programming layer (loader)
expl3-code.tex    2019-11-07 L3 programming layer
l3deprecation.def    2019-04-06 v L3 Deprecated functions
l3backend-pdfmode.def    2019-04-06 L3 backend support: PDF mode
  xparse.sty    2019-10-11 L3 Experimental document command parser
   array.sty    2019/08/31 v2.4l Tabular extension package (FMi)
l3keys2e.sty    2019-10-11 LaTeX2e option processing using LaTeX3 keys
translator.sty    2019-05-31 v1.12a Easy translation of strings in LaTeX
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
translator-basic-dictionary-English.dict
siunitx-abbreviations.cfg    2017/11/26 v2.7k siunitx: Abbreviated units

**Comment by josephwright** [comment]
This is to do with how the LaTeX kernel parses package options. It's hopefully going to be addressed there, but in general I recommend giving options using `\sisetup` unless it's strictly load-only.
