### ISSUE TITLE
Use siunitx with values from external files

### ISSUE THREAD

**Issue by bisco2** [josephwright/siunitx#369]
Hi,

I'm writing a paper and I'm using a lot of numerical values that are stored in external files. I'd like to use siunitx, but it always finds some `\spacefactor` in the data. I have
```
\newcommand{\ii}[1]{\@@input data/includes/#1}
```
to include the files (based on https://tex.stackexchange.com/questions/397803/combine-siunitx-s-column-with-input-value-from-tex-file). Whe I use
```
\num{\ii{5/pknrof.tex}}
```
I get the error `Package siunitx Error: Invalid token '\spacefactor ' in numerical input.`.
The file pknrof.tex only contains the string `5499572`.
How can I get rid of that `\spacefactor`?

**Comment by josephwright** [comment]
Do you have that definition surrounded by `\makeatletter`?

**Comment by bisco2** [comment]
> Do you have that definition surrounded by `\makeatletter`?

Ah, thanks, surrounding the `\ii` definition with `\makeatletter` and `\makeatother` fixes the problem with the `\spacefactor`, thanks!
But now I get the error `! I can't find file 'data/includes/5/pknrof.tex}}'.` It seems somehow to interpret the closing curly braces as part of the filename- if I remove the surrounding `\num{}` the file gets included..
