### ISSUE TITLE
"compact" uncertainty format is incorrect

### ISSUE THREAD

**Issue by PorcelainMouse** [josephwright/siunitx#371]
SIUnitx's implementation of the "compact" format for expressing an uncertain number is incorrect.  According to NIST,

123.45(1.20) is correct,

and

123.45(120) is incorrect.

See https://github.com/lebigot/uncertainties/issues/117 for history.  See CODATA Recommended Values: 2014 Table IX (J. Phys. Chem. Ref. Data, Vol 45, No. 4, 2016) for an example in print.

This also affects interpretation of compact uncertain literal values given to sinunitx for reformatting.

**Comment by josephwright** [comment]
NIST's choice of how to use a 'short' format for uncertainly is simply a different convention from the one `siunitx` follows. They've clearly picked `123.4(5.6)` as a simple shortcut for `123.45 \pm 5.6`, whereas the format used by `siunitx` is that used in e.g. chemical crystallography: uncertainty in the last digits: see for example https://journals.iucr.org/e/services/notesforauthors.html:

> The standard uncertainty (abbreviated s.u.) should be expressed as a number in parentheses following the numerical result and should be on the scale of the least significant digits of the result and usually in the range 2–19.

**Comment by josephwright** [comment]
Actually, NIST themselves don't mention how to handle crossing the radix point on that page, so one can argue the convention either way. The BIPM are the same: https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9-EN.pdf only has an uncertainty in a very small value. Thus we are really taking about not 'correctness' but simply how something is defined. In particular, it's pretty rare to find an s.u. that crosses the decimal marker. (I know NIST do, but as a chemical crystallographer I find the idea of giving an s..u. greater than 19 to be basically wrong.)

The representation used by `siunitx` has been the same from initial release: the compact part is interpreted as working from the least-significant-digit and thus does not take any notice of the radix point. That makes most sense to me (one doesn't need a radix point in the uncertainty when reading from the least-significant figure).

I'm extremely wary of changing the code here (there would be a lot of breakage). I can think about a 'variant' form of input for the next release of `siunitx`, but I would want I think to see wider examples: NIST are important, but they are not the only people with opinions here.

**Comment by PorcelainMouse** [comment]
Personally, I prefer the idea of uncertainty digits as applying to the least sig digits of the nominal value, as well, which makes the radix point unnecessary.  So, I'm not arguing it's a poor choice, only that it is causing a conflict.  I have no python implementation of any format that SIunitx accepts.   I'm trying to appeal to some standard to organize the solution, but I seem to be failing everywhere I turn.  As you see, I've tried reporting this to three different projects.

I need to convince SIunitx and the python 'uncertainties' package to agree on some standard.  Ultimately, the global appeal of the standard is irrelevant; I just thought appealing to a standard would be the simplest way to convince one party to unilaterally adopt the other's convention, making less total work.  If both packages decide to implement the other's format, that will work too.  But, if both expect the other to write new code they don't want, aesthetically, the chance of it happening is very small.

I appreciate the idea that no legitimate experimental result would be reported if there were large uncertainty in the leading digit, but that neglects some important cases I assume you would support.  I think the easiest example to appreciate is that of uncertain calculations.  You may not know, for even mildly complex forms, the combined uncertainty of a calculated value if there are many uncertain dependent values.  That is exactly how I came to this request.  The combined unc may be much larger than the nominal value, ultimately; presumably SIunitx should be able to express these results. Or, what if you calculate the difference of two uncertain numbers and the remainder is on the order of the uncertainty.  That's exactly what you want when you look at residuals. So, I think these are very common cases and I want to be able to use SIunitx to format them.

I'm open to suggestions, but I'm out of ideas at this point.  Should we ask BIPM for their input?  What would make it seem worthwhile to write code so that SIunitx could at least *accept* the other format as input, not output it?

**Comment by josephwright** [comment]
Experience from the development of `siunitx` makes me wary of anything that's not somehow codified as a standard, but at the same time I'm also wary of changing things that go back to v1 over 10 years ago. We seem to have three possible ways forward

- Agree that my interpretation of the rather vague NIST/BIPM rule is clearer than NIST's own when it comes to `123.4 \pm 5.6`, and claim this is the standard by reason of common implementation
- Lobby NIST/BIPM to clarify their description of the rule here, and then I make a change in `siunitx` with come clarity about the reasoning
- I implement a 'allow a decimal' approach without any stated change in desired format

**Comment by PorcelainMouse** [comment]
I doubt I could contribute to the last one, as my LaTeX internals programming is weak, but that one best suits my needs.  The second one could also be helpful, so perhaps I can work on that.

**Comment by josephwright** [comment]
@PorcelainMouse Oh, the TeX code is all my job ;)

**Comment by Lack-of-simmetry** [comment]
I second the request for an option to have the decimal marker in the compact uncertainty format.
In my field, writing values such as 3.3(2.0) is definitively the norm (disclaimer: my field is close to what NIST/BIPM do). For example, a couple of times, values typeset by siunitx like 3.3(20) were a matter of confusion among colleagues.

The GUM ([](https://www.bipm.org/en/publications/guides/gum.html)) in its clause 7.2.2 allows for uncertainties to either correspond to the last digits of the result or to be expressed in the unit of the result. I swap from one to the other if the numerical value of the uncertainty is > 1.

**Comment by josephwright** [comment]
I'll look at this, I'm still thinking about a few issues, but I can see that it would be useful.

**Comment by Lack-of-simmetry** [comment]
Thank you very much, appreciate the efforts!

**Comment by PorcelainMouse** [comment]
I was able to contact BIPM about the issue, but I haven't heard back from them. I know it reached a real person, but, you know, it was kind of a strange request and I have no idea what to expect.

Regarding 7.2.2, this is very interesting and, in form (3), shows the parentheses containing the radix point and other numerical punctuation.  That suggests it should be allowed, at least.  So, that works for me.  It also suggests we should use clear text to describe what we mean when using the parentheses, not just leave it up to the reader to recognize what we mean. A good lesson!

However, it does not answer the core question: how to use *form (2)* if the uncertain digits are on both sides of the radix point, as in my example in the original bug post. In the GUM 7.2.2 example, they have chosen to show the unambiguous case, rather than the edge case I'm running into.

**Comment by josephwright** [comment]
@PorcelainMouse Indeed, edge cases are where the problem falls. I'm going to have to give this some thought, but I will try to cover the desired format: I try to get all 'reasonable' use cases into `siuntx`. Might take a little while: other projects are currently taking up some of my time.

**Comment by josephwright** [comment]
I've moved this up to hit v3.0.0 for release: I have more-or-less solved the issues in my mind. I can now parse the values to my preferred internal form (no marker), and will soon add support for printing them in output. I think that will sort the issue.

**Comment by josephwright** [comment]
@PorcelainMouse , @Lack-of-simmetry  I could do with some thoughts on _output_ formats: I've sorted parsing in `siunitx` v3.0 so there will be no issue with reading `123.45(1.20)` or `1.23(0.04)`. It seems to me there are foru different cases

- Separate uncertainties in all cases: `123.45 \pm 1.20` and `1.23 \pm 0.04`
- Strictly last-digit-based uncertainties: `1.2345(120)` and `1.23(4)`
- 'Mark the radix point': `123.45(1.20)` and `1.23(4)`
- Bracket-the-separate-uncertainty: `123.45(1.20)` and `1.23(0.04)`.

Does that seem right? If so, I think I need to describe these as four different uncertainty modes. My initial suggestions for names (in order)

- `separate`
- `compact`
- `compact-marker`
- `bracket`

The third one is the hardest to name.

Actual implementation is pretty trivial in the v3.0 code, so I can do this if I can get agreement on the naming.

**Comment by Rmano** [comment]
Disclaimer: I definitely use almost only the `separate` format in my field, but yes, I am used to seeing all of them. In my personal opinion, the `compact-marker` is the least attractive --- I would use `compact` or `bracket`. But I am not a metrologist, so take my opinion with a pinch of salt.

**Comment by josephwright** [comment]
Thinking more, this is two options: `separate-uncertainty` as-is, with a new `(compact)-uncertainty-mode` for the more tricky what-happens-in-the-brackets part. I'm just working out the naming.

**Comment by josephwright** [comment]
I've committed something: I'm happy to adjust naming, etc. if there are better ideas. I've gone with splitting the idea of a separate uncertainty from the formatting of a 'bound' one, as the former seems to have exactly one format and is really an entirely separate number. May have some fun here when also implementing https://github.com/josephwright/siunitx/issues/24.

**Comment by PorcelainMouse** [comment]
Hey, this is awesome. Thank you for dealing with this mess.

Yes, I agree with your four different possibilities. I also think the 'compact' format makes sense and is, well, the best looking of the compact format possibilities.  But, that's of secondary importance to me, as I most desire the "correct" (i.e. NIST approved) format to come out of your hard work.

I hope v3.0 comes to texlive soon!

**Comment by josephwright** [comment]
@PorcelainMouse This will go to CTAN once I feel I've given it enough time for people to beta test. I'm not sure how much takeup I have, but I will probably give it about a month at least. There might be a second beta, so likely something like early June.

**Comment by Lack-of-simmetry** [comment]
Thank you very much! Appreciate the efforts.
This will make my life much easier in the future.

I think what you have makes a lot of sense. In my opinion `compact-marker` is clear enough: suggesting it is the same as `compact` but with the extra decimal marker where needed.
