### ISSUE TITLE
Possibility to use different formats for arcseconds in \SI and \ang?

### ISSUE THREAD

**Issue by maxnoe** [josephwright/siunitx#372]
I would like to use "as" as format for arcseconds when used in `\SI`, especially when used together with si prefixes like `milli` or `micro` but still have the ticks `"` when using `\ang`, e.g. to express geographic longitudes/latitudes.

So `\SI{5}{\micro\arcseconds}` should render as 5 µas but `\ang{10;5;5}` should still render as 10°5'5".

Is this possible?

**Comment by josephwright** [comment]
I can see how to do this in v3: I'll put down for v3.1 as it's not so hard but I'd like to finish v3.

**Comment by maxnoe** [comment]
Awesome, thank you for all the work!
