### ISSUE TITLE
Cannot use uncertainty with \ang{}

### ISSUE THREAD

**Issue by mskblackbelt** [josephwright/siunitx#375]
While trying to write up some notes on error analysis and error propagation, I ran into a snag while working with angular information. I expected to be able to write an angle with some uncertainty as `\ang{54.2(1)}`, but when I tried to compile this, I received the following errors:

```latex
./mwe.tex:16: Package siunitx Error: Token '54.2(1)' forbidden in restricted nu
merical
(siunitx)                input.

For immediate help type H <return>.
 ...                                              
                                                  
l.16  \ang{54.2(1)}
                 

The current input must be a real number and cannot contain:
 - an exponent;
 - an uncertainty;
 - a complex part.
```

**Comment by josephwright** [comment]
The error is telling you exactly what is up: the input to `\ang` is restricted. You have to use `\SI{...}{ \degree}`.
