### ISSUE TITLE
Font detection (partially?) broken with Arev in Beamer

### ISSUE THREAD

**Issue by zoqaeski** [josephwright/siunitx#376]
It appears that #122 has returned. Even with the `\usefonttheme{professionalfonts}` option, Beamer still seems to insist on doing all sorts of weird things to the fonts, and using the Arev package to typeset maths in a font closely resembling Helvetica (because Helvetica Neue LT Pro is required for body text according to my institution's style guidelines) causes the output of siunitx to render all numbers and units in italics.

It can be fixed with adding the following immediately after `\begin{document}`:
```
\sisetup{
  detect-all = true,
  detect-family = true,
  detect-display-math=true,
  detect-inline-family=math,
  detect-inline-weight=math,
  math-rm = \mathrm,
```
However, the spacing still looks odd, and I don't know if that is due to siunitx or Arev or Beamer or all of the above.

**Comment by josephwright** [comment]
Could you add an example? I'm not sure if you mean specifically `arev` + `beamer` or more generally.

**Comment by zoqaeski** [comment]
I've only been typesetting slideshows with this combination of fonts in Beamer so far, but its use of themes is sufficiently different from "normal" LaTeX that it took a lot of trial-and-error to get the document looking right. A bit of reading up on Arev suggests that its metrics are just off a bit—it has weird placement of sub- and superscripts as well, so I'm inclined to think it's an `arev` issue rather than a `siunitx` one. 

Are the units supposed to be typeset in the body font or the maths font in equations or maths mode? What I'm seeing is the units being typeset in the maths font if used within a math environment, and it just looks kind of jarring with inline maths.

**Comment by josephwright** [comment]
That's a stylistic question! In 'normal' TeX input, one would expect the 'reference' to be in math mode, but this can come out looking odd depending on the font chosen.
