### ISSUE TITLE
Slanted \ohm when using unicode-math

### ISSUE THREAD

**Issue by zepinglee** [josephwright/siunitx#377]
Package | version
--- | ---
LaTeX2e | 2020-02-02 patch level 3
expl3 | 2020-02-21
amsmath | 2020/01/20 v2.17e
fontspec | 2020/02/21 v2.7i
unicode-math | 2020/01/31 v0.8q
siunitx | 2020/02/20 v2.8

The MWE:
```
\documentclass{article}
\usepackage{amsmath}
\usepackage{unicode-math}
\usepackage{siunitx}
\begin{document}
\si{\ohm} $\si{\ohm}$
\end{document}
```
The document is compiled via `xelatex`.

Screenshot:
<img width="127" alt="Screen Shot 2020-02-23 at 12 10 04 PM" src="https://user-images.githubusercontent.com/12290822/75103429-6e2e3980-5635-11ea-9a62-e0b1ef3bd3dd.png">

The symbols are correct if the `unicode-math` package is omitted:
<img width="113" alt="Screen Shot 2020-02-23 at 12 11 23 PM" src="https://user-images.githubusercontent.com/12290822/75103443-9e75d800-5635-11ea-9600-8bfc3af72445.png">

**Comment by e-kwsm** [comment]
siunitx 2020/01/15 v2.7u works as expected.
