### ISSUE TITLE
ENH: Improvement of localisation

### ISSUE THREAD

**Issue by jakobjakobson13** [josephwright/siunitx#380]
Dear Joseph,

in section "6 Localisation" of your documentation of the SIunitx package you are writing
> Note that the in order for this [the localisation] to work correctly, languages should be given as global (class) options rather than as package options for babel.

Is there any chance the localisation mechanism can be changed in way that the language option has not be given as a global option?

Regards

**Comment by josephwright** [comment]
I'll check with Javier about formal `babel` data structures.

**Comment by jakobjakobson13** [comment]
> I'll check with Javier about formal `babel` data structures.

Great! Would also become compatible with polyglossia by that recoding?

**Comment by wspr** [comment]
Looks to me like the `tracklang` package is the only way to do this, and that adds a dependency to `siunitx` which Joseph may not be interested in doing. What's wrong with setting a global class option?

**Comment by jakobjakobson13** [comment]
> Looks to me like the `tracklang` package is the only way to do this, and that adds a dependency to `siunitx` which Joseph may not be interested in doing. What's wrong with setting a global class option?

Actually nothing in particular, I just never understood the precise difference and reasons why to use global or local options in same cases and in global options in other cases to be honest.

**Comment by josephwright** [comment]
Well, global options are visible to all packages, whereas local ones are only meant for the packages in the `\usepackage` line where they appear.

**Comment by josephwright** [comment]
I think we can call this resolved: using a global option remains the 'correct' approach (we've had some internal discussion on the LaTeX team).
