### ISSUE TITLE
SIrange behaves different inside and outside of math environment

### ISSUE THREAD

**Issue by jakobjakobson13** [josephwright/siunitx#381]
Hi,

the `\SIrange` command behaves different inside and out the math environment as you can see in the following code and in the picture.
```
\documentclass[english]{article}
\usepackage{siunitx}

\begin{document}

\begin{table}
  \begin{tabular}{cc}
    input & output \\
    \hline
    \verb|\SIrange{1}{2}{\m}| & \SIrange{1}{2}{\m} \\
    \verb|$\SIrange{1}{2}{\m}$| & $\SIrange{1}{2}{\m}$  \\    
    \verb|\SIlist{1;2}{\m}| & \SIlist{1;2}{\m} \\
    \verb|$\SIlist{1;2}{\m}$| & $\SIlist{1;2}{\m}$  \\    
  \end{tabular}
\end{table}

\end{document}
```

![siunitx_bug2-crop-1](https://user-images.githubusercontent.com/43045863/80918553-e6b42380-8d65-11ea-8c84-d51ee60465ee.png)

Is this intended?

Regards

**Comment by josephwright** [comment]
`\SIrange` is documented as working only in text mode

**Comment by jakobjakobson13** [comment]
Okay, thanks.
