### ISSUE TITLE
exponent-to-prefix outputs the wrong value

### ISSUE THREAD

**Issue by schtandard** [josephwright/siunitx#383]
`\SI[exponent-to-prefix]{2.5e-7}{\meter\cubed}` outputs 2.5 cm<sup>3</sup>, but the correct value is 0.25 cm<sup>3</sup>.

[Related TeX.SX question.](https://tex.stackexchange.com/q/521215)

**Comment by josephwright** [comment]
I'd like to say 'this is working' in v3, but it's more 'er, as stated this can't work'. If you try the v3 code with 
```latex
\SI[exponent-to-prefix]{2.5e-6}{\meter\cubed}
```
then it will work properly. But 
```latex
\SI[exponent-to-prefix]{2.5e-7}{\meter\cubed}
```
can't work as the resulting power is non-integer. Was it supposed to be `fixed-exponent` too?

**Comment by schtandard** [comment]
I think there are three possibilities of how to deal with this:
1. Do the conversion in some well-defined way. That is, one of the following:
    1. Always keep some significant digits in front of the decimal marker.
    - `{2.5e-7}{\meter\cubed}` → 250 mm³
    - `{2.5e-5}{\meter\cubed}` → 25 cm³
    2. Always keep exactly one digit in front of the decimal marker.
     - `{2.5e-7}{\meter\cubed}` → 0.25 cm³
     - `{2.5e-5}{\meter\cubed}` → 0.025 dm³
     3. Minimize the number of necessary digits on either side of the decimal marker.
     - `{2.5e-7}{\meter\cubed}` → 0.25 cm³
     - `{2.5e-5}{\meter\cubed}` → 25 cm³

     Personally, I would prefer the latter option. (A package option for selecting a strategy is also possible, of course.)
2. Refuse to do the conversion and issue a warning, printing the number as it has been input.
3. Refuse to do anything and issue an error.

Generally, I think that the document author should actively decide how the numbers should be displayed, which is why I never use `exponent-to-prefix` at all and which is why I think the latter two possibilities are absolutely fine. (Even just refusing to do conversion on anything but simple units at all would be a strategy.) However, since we already have `exponent-to-prefix` and people use it, I expect that many authors would enjoy the first possibility.

Related: This gets much more complicated with composite units, of course. Something like `{2.5e-7}{\meter\cubed\per\second}` (or even `\meter\per\second`) could always be converted in many possible ways. The current rule seems to be to apply the conversion only to the first component of the unit. Maybe this is what people expect, I'm not sure. It might be best to just refuse converting these composite units at all.

**Comment by josephwright** [comment]
I'm not keen on trying to 'range guess' input: I think as the main issue here is sorted, I'll close.

**Comment by josephwright** [comment]
@schtandard  Yes, the combo is applied to the first unit only; that's by-design as really this feature is mainly about things with only one unit.
