### ISSUE TITLE
Leak of security key?

### ISSUE THREAD

**Issue by siefkenj** [josephwright/siunitx#387]
https://github.com/josephwright/siunitx/blob/fb02a15cfe2b5ab5b98a7a3b949409c723f77617/.travis.yml#L11

Does this line leak a security key that should not be revealed?

**Comment by josephwright** [comment]
No, this is a standard Travis-CI set up for deployment. The key only works for uploads by the Travis-CI account back to GitHub, it can't be used for anything else.
