### ISSUE TITLE
Examples of localisation not localised

### ISSUE THREAD

**Issue by dbitouze** [josephwright/siunitx#390]
In the documentation, the examples of localisation (§ 6):

```latex
% In English by default
\SIlist{1;2;3}{\metre} \\
\SIrange{1}{10}{\degreeCelsius}  \\
\selectlanguage{french}%
\SIlist{1;2;3}{\metre} \\
\SIrange{1}{10}{\degreeCelsius} \\
\selectlanguage{german}%
\SIlist{1;2;3}{\metre} \\
\SIrange{1}{10}{\degreeCelsius} \\
\selectlanguage{spanish}%
\SIlist{1;2;3}{\metre} \\
\SIrange{1}{10}{\degreeCelsius} \\
```
are not localised:

>1 m, 2 m and 3 m
1 °C to 10 °C
1 m, 2 m and 3 m
1 °C to 10 °C
1 m, 2 m and 3 m
1 °C to 10 °C
1 m, 2 m and 3 m
1 °C to 10 °C

**Comment by froido** [comment]
I observed the same issue with german localization, but I can report that in general localization is working:  the replacement of the decimal separator from "." to "," works fine.

**Comment by froido** [comment]
> I have a feeling this related to a `babel` change: I better check!

I just recognized that everything works fine, when the language like *ngerman* is set as an option in the document class. Is it set as an option for babel, it is not working.

### Language _only_ in document class
```tex
\documentclass[ngerman]{article}
\usepackage{babel}
\usepackage[locale=DE]{siunitx}

\begin{document}
  \SIrange{15.3}{16.7}{\meter}\\
  \SIlist{15.3;16.2;17.1}{\meter}
\end{document}
```

>  15,3 m bis 16,7 m
>  15,3 m, 16,2 m und 17,1 m

### Language in document class _and_ babel
```tex
\documentclass[ngerman]{article}
\usepackage[ngerman]{babel}
\usepackage[locale=DE]{siunitx}

\begin{document}
  \SIrange{15.3}{16.7}{\meter}\\
  \SIlist{15.3;16.2;17.1}{\meter}
\end{document}
```

>  15,3 m bis 16,7 m
>  15,3 m, 16,2 m und 17,1 m

### Language _only_ in babel

```tex
\documentclass{article}
\usepackage[ngerman]{babel}
\usepackage[locale=DE]{siunitx}

\begin{document}
  \SIrange{15.3}{16.7}{\meter}\\
  \SIlist{15.3;16.2;17.1}{\meter}
\end{document}
```

>  15,3 m to 16,7 m
>  15,3 m, 16,2 m and 17,1 m

**Comment by josephwright** [comment]
This is fixed in v3 - beta is out today, final release in the summer.
