### ISSUE TITLE
Inconsistency between global 'french' and locale = FR

### ISSUE THREAD

**Issue by f380cedric** [josephwright/siunitx#392]
## Expected Behavior
`\documentclass[french,...]` and `\sisetup{locale=FR,...}` does the same.

## Current Behavior
Using `documentclass` only converts words (translator) (such as in `SIlist`) but
it does not activate every features of FR locale (such as `,` instead of `.` as decimal delimiter).

It would be nice that if a locale exists under siunitx (UK, US, DE, FR, ZA),
it uses it when detecting the global language.

## Steps to Reproduce
```latex
\documentclass[french]{article}
\usepackage{babel}
\usepackage{siunitx}
\begin{document}
\num{1.1}; \num{1,1}
\end{document}
```

generate `1.1; 1.1` instead of `1,1; 1,1`.

**Comment by josephwright** [comment]
This is by-design: locale is not the same as language - locale is about the place where publishing is happening and typographic convention, not what language the document is written in.

**Comment by f380cedric** [comment]
I do not know any country with a french speaking community using dot as decimal delimiter (when writing in French).
The typographic convention comes most of the time with the language used (like space before '?' or ':').
Furthermore, Babel define language and (some?) locale. 

But it is a fair point, locale and language are 2 different things.
Adding stuff to detect the defined locale within Babel is not worth 'locale=FR'.

Closing.
