### ISSUE TITLE
retain-unity-mantissa not working

### ISSUE THREAD

**Issue by learex** [josephwright/siunitx#393]
```
\documentclass{article}
\usepackage{siunitx}
\begin{document}
	\num[retain-unity-mantissa = true, scientific-notation = true]{4.44e0}
\end{document}
```
produces `4.44` not `4.44 \cdot 10^{0}`

**Comment by bersbersbers** [comment]
Note that `retain-unity-mantissa` is `true` by default.

I wonder if you mean `\num[retain-zero-exponent = true, scientific-notation = true]{4.44e0}` - but that is not working, either.

**Comment by bersbersbers** [comment]
I do wonder whether this is expected, since the manual say
> Note that these options [`scientific-notation`, ...] apply after any removal of unit mantissa, zero exponent, etc

So it is intended that `scientific-notation` brings back what `retain-unity-mantissa = false` suppresses, and that it suppresses what  `retain-zero-exponent = true` retains?

**Comment by josephwright** [comment]
This is all sorted in the v3 work, which is now scheduled for release in the summer.
