### ISSUE TITLE
siunitx should not change header spacing in ieeecolor class

### ISSUE THREAD

**Issue by bersbersbers** [josephwright/siunitx#394]
This MWE shows how simply including `siunitx` changes the spacing in the header:

```
\documentclass[journal,twoside,web]{ieeecolor}
\usepackage{tmi}
\usepackage{graphicx}
% \usepackage{siunitx}
\begin{document}
\title{X}
\author{Y \thanks{Z}}
\maketitle
\end{document}
```

Without `siunitx`:
![image](https://user-images.githubusercontent.com/12128514/93868537-db3ca700-fcca-11ea-92cd-cf864810d1ab.png)

With `siunitx`, blue line in header is *lower*:
![image](https://user-images.githubusercontent.com/12128514/93868542-ded02e00-fcca-11ea-8e0d-d17bae3c6af9.png)

Get `ieeecolor.cls` here:
https://www.embs.org/wp-content/uploads/2020/04/TMI-Template-LaTeX-2020.zip

**Comment by josephwright** [comment]
This is not due to `siunitx` but due to the `array` package, which is loads. The `array` package is part of the core of LaTeX, so the issue here is that `ieeecolor` is not compatible with `array`, not the other way around.

**Comment by bersbersbers** [comment]
Thanks for the explanation, I can confirm this. From a user perspective, that difference is marginal, unfortunately.

It is possible to disable loading of the `array` package (https://tex.stackexchange.com/a/39418), but then one would need to disable a few more lines in `siunitx.sty` - any idea?

**Comment by josephwright** [comment]
The bottom line is `array` is _standard_ and may well be built into LaTeX soon. If a class fails with `array`, then the class is faulty.

**Comment by bersbersbers** [comment]
Understood. I'll try to get hold of someone at IEEE, but so far this seems difficult.
