### ISSUE TITLE
Uncertainty in parenthesis with decimal point

### ISSUE THREAD

**Issue by klicperajo** [josephwright/siunitx#395]
For uncertainties in parenthesis siunitx never uses a decimal point, e.g. `13.2(12)` for `13.2 +/- 1.2`. In this case a decimal point (i.e. `13.2(1.2)`) would be less ambiguous and easier to read and understand. It would therefore be very useful to have this option.

See e.g. https://physics.stackexchange.com/questions/378194/writing-an-uncertainty-of-the-form-8-3-pm1-2-using-parenthesis-notation-simi

**Comment by josephwright** [comment]
This has come up before :)

The guidelines on which is correct are ambiguous to say the least. I do plan to extend for this, although personally I prefer the idea that the parenthetic part is strictly numerical.

**Comment by klicperajo** [comment]
Yes, I just found the old issue. :-/

For me it would be great to have the current version as a default but provide an option.
