### ISSUE TITLE
passing numbers via macro to \num

### ISSUE THREAD

**Issue by matthias-k** [josephwright/siunitx#398]
Hi,

I'm trying to format numbers in my paper. The numbers come from a json file, that I converted into latex code with [json2latex](https://pypi.org/project/json2latex/). json2latex makes the content of the json file available as a latex macro, e.g. as `\myjsoncontent[key1][42][key2]`. However, I don't manage to pass these numbers to sunitx' `\num` command. I'm always getting weird error messages. Here is a minimal example:

```latex
\documentclass{article}
\usepackage{siunitx}

% output of json2latex.dumps('test', {'a': 1, 'b': 2.4})
\makeatletter\newcommand\test[1][all]{\ifnum\pdfstrcmp{#1}{all}=0\def\test@out{\{"a": 1, "b": 2.4\}}\else\ifnum\pdfstrcmp{#1}{a}=0\def\test@out{1}\else\ifnum\pdfstrcmp{#1}{b}=0\def\test@out{2.4}\else\def\test@out{??}\fi\fi\fi\test@out}\makeatother
\begin{document}

\test[b]  % works, prints 2.4
\num{\test[b]}  % fails

\end{document}
```
The call to `\num` fails with `Argument of \reserved@a has an extra }.`. In the case of more nested json data, I also often had error messages about `\test doesn't match its definition`. All of this doesn't seem special to json2latex, I had similar problems when trying datatools `\DTLfetch` command to read numbers from a csv file.

Is there anything I have to keep in mind when trying to pass numbers from macros to sunitx?

**Comment by josephwright** [comment]
`siunitx` can work with stored _numbers_, but you have instructions to _typeset_ numbers. You need to do the 'work' and store the _result_ in a macro, which `siunitx` can then expand.

**Comment by matthias-k** [comment]
@josephwright thanks! after some more research, it appears the main problem is that a macro is defined within the argument to `\num`.  The problem here can be boiled down to a simple

```latex
\num{\def\test{3.3}\test}
```
This fails with
```
! Undefined control sequence.
<argument> ...set_catcode_other:N \.}}{\def \test 
                                                  {3.3}\test }
l.5 \num{\def\test{3.3}\test}
```
Can you specify a bit more what "store the result in a macro" means in this context? From what I'm seeing, this is exactly what is done here.

**Comment by josephwright** [comment]
@matthias-k Without getting too technical: you can't have anything that performs an assignment inside the argument to `\num`. So you can have `\def\test{3.3}\num{\test}` but no have the `\def` inside the argument.
