### ISSUE TITLE
Rounding numbers with num results in error "Number too big"

### ISSUE THREAD

**Issue by tro100** [josephwright/siunitx#400]
Using \num to round numbers sometimes results in the error "Number too big", but still produces the right output.
Here is an example, with slightly different numbers:

\documentclass{scrartcl}
\usepackage{siunitx}
\begin{document}
\num[round-half=even,round-mode=places,round-precision=2,scientific-notation = fixed,fixed-exponent=0]{2.93215569770292 e2} -> error
\num[round-half=even,round-mode=places,round-precision=2,scientific-notation = fixed,fixed-exponent=0]{2.93215569770291 e2} -> no error	
\num[round-half=even,round-mode=places,round-precision=2,scientific-notation = fixed,fixed-exponent=0]{2.93215569770292 e3} -> no error	
\num[round-half=even,round-mode=places,round-precision=2,scientific-notation = fixed,fixed-exponent=0]{2.93215569770302 e2} -> no error
\end{document}

**Comment by josephwright** [comment]
Er, yes, I'll see if that's easily fixed.

**Comment by josephwright** [comment]
This is fixed in v3, which I'm now working hard to finalise: really hope to have it out by the summer.
