### ISSUE TITLE
What about K, M, B, T suffixes

### ISSUE THREAD

**Issue by dbogatov** [josephwright/siunitx#401]
Hi,

I sit possible to use `K`, `M`, `B` and `T` suffixes to denote thousands, millions, billions and trillions respectively?
For example, 2.1B means 2,100,000,000 .

It is used sometimes to denote currency, like $2.1B and I would like to use in a research paper talking about data size in experiments.
`2.1*10^9` does not look as good...

**Comment by josephwright** [comment]
At present no, as for quantities this would be part of the unit. One could create a 'no-op' unit and put the information there.

**Comment by dbogatov** [comment]
Alright!
I looked through documentation PDF and google...
How do I create a `no-op` unit?

**Comment by josephwright** [comment]
Something like
```latex
\documentclass{article}
\usepackage{siunitx}
\DeclareSIUnit\noop{\kern 0pt\relax}
\begin{document}

\SI{10}{\kilo\noop}

\end{document}
```

**Comment by dbogatov** [comment]
Ha, thanks!
