### ISSUE TITLE
Problem with \SI & friends when used with ulem

### ISSUE THREAD

**Issue by lhy7889678** [josephwright/siunitx#404]
When using `\SI`, `\SIrange` and `\SIlist` inside `\uline` defined in the `ulem` package, LaTeX will complain `! Extra }, or forgotten \endgroup.` then `! Missing } inserted.`. However, if we ignore the error and continue compiling, the resulting PDF file looks fine as desired.

Here is the MWE:

```
\documentclass{article}
\usepackage{siunitx}
\usepackage[normalem]{ulem}

\begin{document}
  % \num, \si & friends work perfectly with \uline
  \uline{\num{1}}
  \uline{\si{\meter}}
  \uline{\numrange{1}{2}}
  \uline{\numlist{1; 2; 3}}
  
  % \SI & friends will raise an error 
  \uline{\SI{1}{\meter}}
  \uline{\SIrange{1}{2}{\meter}}
  \uline{\SIlist{1; 2; 3}{\meter}}
  
  % Other commands defined in ulem will also raise an error
  \uuline{\SI{1}{\meter}}
  \uwave{\SI{1}{\meter}}
  \sout{\SI{1}{\meter}}
  
  % \underline works fine
  \underline{\SI{1}{\meter}}
  \underline{\SIrange{1}{2}{\meter}}
  \underline{\SIlist{1; 2; 3}{\meter}}
\end{document}
```

I don't know whether this is a bug related to `siunitx` or `ulem`. However, I can't find a public issue tracker of `ulem` on CTAN, so I post it here.

**Comment by josephwright** [comment]
The issue is that `ulem` 'takes things to pieces', and here it splits the two arguments of `\SI`. You likely need to wrap material inside an `\mbox` inside `\uline`, etc., to avoid the issue.

**Comment by lhy7889678** [comment]
Yes, it worked. However, `\mbox` will prevent linebreak inside `\uline` (especially a problem when using `\SIlist`), which is one of the main reasons why I use `ulem` for breakable underlines. Fortunately, the actual document I am typesetting doesn't have any `\SIlist` across lines.
