### ISSUE TITLE
Cancel doesn't work if non-unit text is present

### ISSUE THREAD

**Issue by Canageek** [josephwright/siunitx#405]
I was trying to write out a series of equations where I specify what the grams are of (ie O2), but noticed if I put the non-unit text inside with the units, cancel stops working at all, as shown below. Ideally I'd like to be able to cancel the unit and the associated descriptor with a single stroke, which is why I tried that in the first place. 

```
\documentclass{article}
\usepackage{siunitx}
\usepackage{cancel}

\begin{document}
\SI{1}{\cancel\gram}

\SI{1}{\cancel\gram\ text}

\SI{1}{\cancel{\gram}\ text}

\SI{1}{\cancel{\gram\ text}}

\end{document}
```

**Comment by josephwright** [comment]
You'll need to declare a 'unit' for cancelling
```latex
\documentclass{article}
\usepackage{siunitx}
\usepackage{cancel}
\DeclareSIUnit{\gramtest}{\gram\ text}
\begin{document}
\SI{1}{\cancel\gram}

\SI{1}{\cancel\gramtest}

\end{document}
```
