### ISSUE TITLE
Per-unit "product-units=single" does not overwrite global "product-units=power"

### ISSUE THREAD

**Issue by bersbersbers** [josephwright/siunitx#406]
```latex
\documentclass{article}
\usepackage[product-units=power]{siunitx}
\DeclareSIUnit[product-units=single]{\bucket}{buckets}
\begin{document}
    \SI{3 x 4}{\meter}
    
    \SI{3 x 4}{\bucket}
\end{document}
```

gives

> 3×4 m^2
> 3×4 buckets^2

while I would expect

> 3×4 m^2
> 3×4 buckets

In fact, 
```latex
\documentclass{article}
\usepackage{siunitx}
\DeclareSIUnit[product-units=single]{\bucket}{buckets}
\begin{document}
    \SI{3 x 4}{\meter}

    \SI{3 x 4}{\bucket}
\end{document}
```

correctly gives

> 3 m×4 m
> 3×4 buckets

**Comment by josephwright** [comment]
Per-unit settings are about individual unit use (`\SI`): a range is _not_ a single unit use.

**Comment by bersbersbers** [comment]
As a workaround, one can use
```latex
\documentclass{article}
\usepackage[product-units=power]{siunitx}
\DeclareSIUnit{\bucket}{buckets}
\begin{document}
    \SI{3 x 4}{\meter}

    \SI[product-units=single]{3 x 4}{\bucket}
\end{document}
```

but that should not be necessary in my opinion.

**Comment by bersbersbers** [comment]
> Per-unit settings are about individual unit use (`\SI`): a range is _not_ a single unit use.

That was quick :) However, if that is true, why is
```
\documentclass{article}
\usepackage{siunitx}
\DeclareSIUnit[product-units=single]{\bucket}{buckets}
\begin{document}
    \SI{3 x 4}{\meter}

    \SI{3 x 4}{\bucket}
\end{document}
```
different from
```
\documentclass{article}
\usepackage{siunitx}
\DeclareSIUnit{\bucket}{buckets}
\begin{document}
    \SI{3 x 4}{\meter}

    \SI{3 x 4}{\bucket}
\end{document}
```
?

Something appears inconsistent to me (or I have misguided expectations).

**Comment by josephwright** [comment]
I'm back on v3 at the moment: this looks like one to think about there (I'm about to tackle this area, so the timing is good). Fingers crossed this time I can get done ...

**Comment by josephwright** [comment]
Fixed in v3

**Comment by bersbersbers** [comment]
This is working great, thanks!
