### ISSUE TITLE
token_get_prefix_spec deprecation

### ISSUE THREAD

**Issue by denniswork** [josephwright/siunitx#407]
Recently, just adding
`\usepackage{siunitx}`
to a document, started resulting in a number of build errors, like this.
```
! Undefined control sequence.
<argument> \LaTeX3 error: 
                           Use \cs_prefix_spec:N not \token_get_prefix_spec:...
```
The document still seems to build fine, even when using siunitx commands in the document.
I'm assuming this is caused by latex3 deprecation warnings that took effect at the beginning of 2021.

Indeed, simply replacing the two instances of **\token_get_prefix_spec:N** by **\cs_prefix_spec:N** in _siunit.sty_ makes the build errors go away.

**Comment by denniswork** [comment]
_siunitx_: **2.8b** (2020-02-26)
_l3kernel_: (2021-02-19); this package supplies _l3deprecation.def_

**Comment by josephwright** [comment]
I'm going to need to see a log file: I have this fixed a year ago in the log.

**Comment by denniswork** [comment]
I'm sorry, Joseph. The issue is _not_ with your package.

Upon inspection of the log file, I noticed that siunitx **2.7m** was being used!
Something must've gone horribly wrong with a miktex update, because it was reporting the latest version.
Upon reinstalling the package, miktex picked up 2.8b and all is well.
