### ISSUE TITLE
Patch \addtocontents

### ISSUE THREAD

**Issue by moewew** [josephwright/siunitx#408]
Via https://tex.stackexchange.com/q/588479/35864

In the following MWE the citations are not resolved correctly in the LoF.

```latex
\documentclass[12pt, a4paper]{article}
\usepackage{graphicx}
\usepackage{lipsum}
\usepackage{siunitx}
\usepackage{biblatex}
\usepackage{hyperref}

\addbibresource{biblatex-examples.bib}

\begin{document}
\listoffigures

\begin{refsection}
\begin{figure}[htbp]
\centering
\includegraphics[width=0.2\textwidth]{example-image}
\caption{The is the first caption \autocite{bertram}}
\end{figure}

\printbibliography
\end{refsection}

\begin{refsection}
\lipsum[2] \autocite{doody}

\begin{figure}[htbp]
\centering
\includegraphics[width=0.2\textwidth]{example-image}
\caption{The is the second caption \autocite{aristotle:anima, doody}}
\end{figure}

\printbibliography
\end{refsection}
\end{document}
```

The problem is that `biblatex` patches `\addtocontents` (in `\AtEndPreamble`), but `siunitx` redefines `\addtocontents` (in `\AtBeginDocument`), which overwrites `biblatex`'s changes.

Would it be possibly to patch `\addtocontents` also in `siunitx` to avoid this situation?

**Comment by josephwright** [comment]
I wonder if the `biblatex` patch could go in slightly differently, leading to something like
```latex
    \def \addtocontents #1#2
      {
        \protected@write \@auxout { }
          {
            \string \@writefile {#1}
              { \defcounter {refsection} { \the \c@refsection }\relax }
          }
        \protected@write \@auxout
          {
            \let \label    \@gobble
            \let \index    \@gobble
            \let \glossary \@gobble
            \seq_map_inline:Nn \l_siunitx_unit_symbolic_seq
              { \__siunitx_contents_add:N ##1 }
          }
          { \string \@writefile {#1} {#2} }
      }
```
The reason is that this then makes it a bit easier if we imagine two 'hooks'

- One `addcontents/altered-cmds`
- One `addcontents/addition-data`

or similar. I think I need to talk to the team about whether we can add hooks here in the kernel, which could then be simply used by both `siunitx` and `biblatex`.

**Comment by moewew** [comment]
That would be fine as well as far as I can see. The only important thing is that we write the current counter value of `refsection` to the file before the actual contents line is written. Since we know which code the counter line contains we can *probably* be quite sure that we won't need the initialisation code of `\protected@write` (unless of course someone does weird things to `\defcounter` and would normally add a restore to `addcontents/altered-cmds`).

**Comment by u-fischer** [comment]
@moewew on the whole I think \addtocontents is the wrong command for biblatex. It doesn't want to sprinkle lots of `\defcounter {refsection}{2}\relax` into the lof and the toc, it wants to add this setting once to the lof or toc when a new refsection starts or one ends.

Which imho means that you need a list of relevant toc-like extensions. LaTeX could probably provide it by storing the extension when \addtocontents and \@starttoc is used and at the end of the compilation write the list to the aux.

**Comment by josephwright** [comment]
Looking back, I'm not sure the patch is needed at all: could people check this code?

**Comment by moewew** [comment]
Yeah, I think `biblatex` could go about this more elegantly. I was thinking maybe something like the following might be more to the point. (But experience has shown that I usually overlook something when it comes to ideas like that, so comments would be appreciated.)

```latex
\documentclass[12pt, a4paper]{article}
\usepackage{graphicx}
\usepackage{lipsum}
\usepackage{siunitx}
\usepackage{biblatex}
\usepackage{hyperref}

\makeatletter
\def\blx@citecmds{}
\listadd\blx@citecmds{autocite}
\listadd\blx@citecmds{autocites}

\newcommand*{\blx@contentscitecmds}{%
  \forlistloop{\blx@makecitecmd@contentssafe}{\blx@citecmds}}

\def\blx@makecitecmd@contentssafe#1{%
  \csdef{#1}{\defcounter{refsection}{\the\c@refsection}\noexpand\csuse{#1}}}

\AtBeginDocument{%
  \long\def\addtocontents#1#2{%
    \protected@write\@auxout
      {\let\label\@gobble
       \let\index\@gobble
       \let\glossary\@gobble
       \blx@contentscitecmds}
      {\string\@writefile{#1}{#2}}}}
\makeatother

\addbibresource{biblatex-examples.bib}

\begin{document}
\listoffigures

\begin{refsection}
\begin{figure}[htbp]
\centering
\includegraphics[width=0.2\textwidth]{example-image}
\caption{The is the first caption \autocite{bertram}}
\end{figure}

\printbibliography
\end{refsection}

\begin{refsection}
\lipsum[2] \autocite{doody}

\begin{figure}[htbp]
\centering
\includegraphics[width=0.2\textwidth]{example-image}
\caption{The is the second caption \autocite{aristotle:anima, doody}}
\end{figure}

\printbibliography
\end{refsection}
\end{document}
```

**Comment by moewew** [comment]
The above idea in slightly more polished (i.e. usable) form is at https://github.com/moewew/biblatex/commit/a14a14ecb9b85a8893c7a99c04c4f800d1764c55 and discussed in https://github.com/plk/biblatex/issues/1116. Comments welcome!
