### ISSUE TITLE
Missing } error when inter-unit-product set as a package option

### ISSUE THREAD

**Issue by ysalmon** [josephwright/siunitx#414]
The following code causes a ``Missing } inserted`` error, but this goes away when setting the inter-unit-product through ``\sisetup`` instead of the package options.

```latex
\documentclass{standalone}
%\RequirePackage{siunitx}
%\sisetup{inter-unit-product={\ensuremath{{}\cdot{}}}}
\RequirePackage[inter-unit-product={\ensuremath{{}\cdot{}}}]{siunitx}
\begin{document}
\si{\metre\per\second}
\end{document}
```

I have a freshly updated TeXlive 2021 (siunitx 2.8e).

**Comment by josephwright** [comment]
This is a 'feature' of the way the LaTeX kernel expands options _before_ they are passed to packages. It's the reason I recommend setting everything other than load-only options using `\sisetup`.
