### ISSUE TITLE
Documentation issues in "Upgrading from version 2"

### ISSUE THREAD

**Issue by bersbersbers** [josephwright/siunitx#416]
1. Where you say that the `\SI...` commands are not recommended any more, saying that the new commands are *now* (edited) `\qty...` would save some time when upgrading.

2. It wasn't clear to me, but `\usepackage{siunitx}[=v2]` can also be used with v2. This means this can be used not only "for documents that cannot be successfully processed using version 3", but also to remain compatible with outdated server-based TeX installations. Maybe worth a note.

2. Typo
> The method used **in** entirely different from version 2.

**Comment by josephwright** [comment]
I'm not quite sure what you want for point 1 - could you expand a bit?

**Comment by bersbersbers** [comment]
Write "Use the new `\qty...` commands instead." ("not" should read "now" in the original post.)

**Comment by josephwright** [comment]
See the commits I've added: do these cover it?

**Comment by bersbersbers** [comment]
Yes :)
