### ISSUE TITLE
v3 does not work well with package nicematrix 

### ISSUE THREAD

**Issue by dimakogan** [josephwright/siunitx#425]
The following used to work in previous versions, but no longer works:
```
\documentclass[11pt]{article}
\usepackage{nicematrix}
\usepackage{siunitx}
\begin{document}
 \begin{NiceTabular}{S}
1
\end{NiceTabular}
\end{document}
```

It gives: 
```! Missing } inserted.
<inserted text>
                }
l.12 \end{NiceTabular}
```
Thanks!

**Comment by josephwright** [comment]
Taking a quick look, `nicematrix` doesn't use the standard LaTeX kernel set up for tabulars - I'll probably need to work on this for a little while to be sure if it's an `siunitx` issue or a `nicematrix` one (the v2 code didn't have a documented API for third parties, which means that such use cases are not really supported).

**Comment by josephwright** [comment]
I've now had a chance to analyse this properly. The issue arises fundamentally as v2 didn't have a documented code API, which means that making anything built on top tricky. What `nicematrix` tries to do is avoid assuming a particular set of function names by extracting them from the `array` command `\NC@rewrite@S`. That's a perfectly reasonable plan but if falls down as in creating a documented API, I've also adjusted how some setup is done. Thus `nicematrix` breaks as it assumes a particular _form_ of the internal `siunitx` API.

You can fix this for the present using
```latex
\documentclass{article}
\usepackage{nicematrix}
\usepackage{siunitx}
\ExplSyntaxOn
\makeatletter
\AtBeginDocument
  {
    \cs_gset_protected:Npn \__nicematrix_renew_NC@rewrite@S:
      {
        \renewcommand*{\NC@rewrite@S}[1][]
          {
            \@temptokena \exp_after:wN
              {
                \tex_the:D \@temptokena
                  >
                    {
                      \__nicematrix_Cell: 
                      \keys_set:nn { siunitx } {##1}
                      \siunitx_cell_begin:w
                    }
                    \__nicematrix_true_c:
                    < { \siunitx_cell_end: \__nicematrix_end_Cell: }
                  }
                \NC@find
          }
      }
  }
\makeatother
\ExplSyntaxOff

\begin{document}

\begin{NiceTabular}{S}
1
\end{NiceTabular}
\end{document}
```
which can happily be used (with an appropriate conditional) by `nicematrix`. I'll raise it with the package author - what is true is that this isn't something I can fix from `siunitx` (at least not without having to enforce an older undocumented API structure.)

**Comment by dimakogan** [comment]
Thank you for looking into it!
