### ISSUE TITLE
User manual command definition is missing curly braces around second range argument

### ISSUE THREAD

**Issue by elfalko** [josephwright/siunitx#427]
p. 7 section 3.3 of the user manual available on CTAN currently reads:

```
\qtyrange[<options>]{<number1>}<number2>{<unit>}
```

The curly braces around `<number2>` are missing and it should really read

```
\qtyrange[<options>]{<number1>}{<number2>}{<unit>}
```

Thanks for the great package!

**Comment by josephwright** [comment]
Fixed by https://github.com/josephwright/siunitx/commit/b136a0791e28a89cc149b45e5f5728f57aa35f16
