### ISSUE TITLE
Add removal of `\celsius` to the "Upgrading from version 2" section

### ISSUE THREAD

**Issue by maxnoe** [josephwright/siunitx#428]
It seems `\celsius` was renamed to `\degreeCelsius` in version 3.

This is not mentionend in the "upgrading" section and results in compilation errors.

Maybe adding back the `\celsius` unit with a warning would also be an option, since it seems that you want to be backwards compatible with warnings everywhere else (e.g. SI / si)

**Comment by josephwright** [comment]
Already fixed in an upcoming hotfix: see https://github.com/josephwright/siunitx/issues/426.
