### ISSUE TITLE
Error when using DE locale in non-math mode [v3]

### ISSUE THREAD

**Issue by MaxSchambach** [josephwright/siunitx#430]
# Description
Since the recent update to v3, using the `DE` locale and exponential numbers results in an error in text mode using pdflatex.
Using lualatex, it works (even though the spacing between the number and the exponent is very small) [EDIT: this seems to be lualatex-specific as lualatex can deal with math symbols such as \cdot in regular text mode].
It seems more generally like there is some bug when using `\cdot` in options such as `exponent-product` in `sisetup`.
What works is using
```
\sisetup{exponent-product=\ensuremath{\cdot}}
```
however this incorrectly uses the math font for the cdot which is problematic when text and math fonts are different.

# Steps to reproduce
A minimal working example to reproduce the error:

```latex
\documentclass{article}
\usepackage{siunitx}
\sisetup{mode=match, locale = DE}
\begin{document}
\num{2.2e-25}
\end{document}
```
Tested with 
```
pdfTeX 3.141592653-2.6-1.40.22 (TeX Live 2021)
```

**Comment by MaxSchambach** [comment]
I think the best way to go is to use `\textperiodcentered` in text mode and `\cdot` in math mode.
However, `pdflatex` and `lualatex` seem to produce very different spacings.
While with `pdflatex` this results in a very narrow spacing, which could easily be resolved with `\,\textperiodcentered\,` it looks very spacy in lua...

**Comment by MaxSchambach** [comment]
Ok, I just fiddled around with the solution using `\textperiodcentered` and it has quite a lot of problems with different fonts, e.g. the standard font in LuaLatex (Latin Modern). 

The problem is, that `\textperiodcentered` has quite different spacings in different fonts, see the example below when compiled with pdflatex vs lualatex. This will result in weird behavior when switching from pdflatex to lualatex or when using non-default fonts, e.g. in Paper latex templates.
So actually, I think using `{\,\ensuremath{\cdot}\,}` is the most robust and visually pleasing way to go. Yes, it is in fact the wrong font, but it's not visually noticable because it's just a circle and the symbol is usually not used anywhere else with the same text font.

```latex
\documentclass{article}
\usepackage{siunitx}
\sisetup{mode=match, exponent-product=`\textperiodcentered`}
\begin{document}
\noindent
\num{2.2e-25} \\
$2.2 \cdot 10^{-25}$
\end{document}
```

**Comment by josephwright** [comment]
I think I'd like to canvas more widely on the spacing/'correctness' issue, but I'll log that separately as it's not quite as urgent.
