### ISSUE TITLE
Replacement for input-symbols?

### ISSUE THREAD

**Issue by josephwright** [josephwright/siunitx#431]
In v3 I've dropped `input-symbols` as it's not clear what happens with things like rounding or digit separation. However, that means something like
```latex
\num{4\pi e-7}
```
has to be done as 
```latex
\num[parse-numbers = false[{4\pi \times 10{-7}}
```
This may not be universally welcomed .... and should be documented at least.

**Comment by AndreaDiPietro92** [comment]
Hi. I've the same problem with a document.
In the older sections of this document i used (example)
```
\mu_0 =\SI{4\pi e-7}{\henry\per\meter}
```
but with the latest update nothing works.
Is this `\num[parse-numbers = false[{4\pi \times 10{-7}} ` the definetively solution?

Thanks

**Comment by josephwright** [comment]
One can use `input-digits` here
```latex
\documentclass{article}
\usepackage{siunitx}
\begin{document}
\sisetup{input-digits = 0123456789\pi}
\num{4\pi e-7}
\end{document}
```

**Comment by josephwright** [comment]
Fixed by 51592b88cc74f77d272cede2f0f742adee49cf2d

**Comment by hkiel** [comment]
I tried to use dots `$ A = \SI{0,4066\dots}{\meter^2} $` with this mechanism: `\sisetup{input-digits = 0123456789\dots}`, but it does not work. I get `Invalid number '0,4066\protect \dots'.`

Is there a defined way to specify a truncated value with trailing dots?

**Comment by josephwright** [comment]
@hkiel Try
```latex
\documentclass{article}
\usepackage{siunitx}
\usepackage{etoolbox}
\sisetup{input-digits = 01234567890\dots}
\robustify\dots
\begin{document}
$ A = \SI{0,4066\dots}{\meter^2} $
\end{document}
```

**Comment by hkiel** [comment]
This works. Would it be a good idea to include the example in the documentation?

**Comment by hkiel** [comment]
I applied the same mechanism for fractional numbers, but that fails if there is more than one digit in either the numerator or the denominator of `\dfrac`

```
\documentclass{article}
\usepackage{siunitx}
\usepackage{etoolbox}
\sisetup{input-digits = 01234567890\dfrac}
\robustify\dfrac
\begin{document}
$\SI{\dfrac{1}{4}}{\meter}$  % works fine
$\SI{\dfrac{1}{30}}{\meter}$ % fails with "Invalid number '\dfrac {1}{30}'. "
\end{document}
```

**Comment by josephwright** [comment]
@hkiel `input-digits` can be used to set up 'digit-like' tokens, but if you want something that involves more complex input, you'll need to turn off parsing with `parse-numbers = false`.

**Comment by Yery** [comment]
Adding the example of \dots to the documentation would be very good (it took me ages to find a solution, and finally found it here).

**Comment by dbitouze** [comment]
> Try
> 
> ```
> \documentclass{article}
> \usepackage{siunitx}
> \usepackage{etoolbox}
> \sisetup{input-digits = 01234567890\dots}
> \robustify\dots
> \begin{document}
> $ A = \SI{0,4066\dots}{\meter^2} $
> \end{document}
> ```

@josephwright Do you actually recommend `\meter^2` (in contrast to `\meter\squared`)?

**Comment by josephwright** [comment]
> > Try
> > ```
> > \documentclass{article}
> > \usepackage{siunitx}
> > \usepackage{etoolbox}
> > \sisetup{input-digits = 01234567890\dots}
> > \robustify\dots
> > \begin{document}
> > $ A = \SI{0,4066\dots}{\meter^2} $
> > \end{document}
> > ```
> 
> @josephwright Do you actually recommend `\meter^2` (in contrast to `\meter\squared`)?

Not really, but it was the in the example given.
