### ISSUE TITLE
prefixes-as-symbols is deprecated?

### ISSUE THREAD

**Issue by rafaelpap** [josephwright/siunitx#432]
I have been using prefixes-as-symbols=false to construct tables like:
```latex
\begin{tabular}{llllll}
\toprule
Factor & Nombre & Símbolo &Factor & Nombre & Símbolo\\
\midrule
\si[prefixes-as-symbols=false]{\yotta} &  yotta &  \si{\yotta}  & \si[prefixes-as-symbols=false]{\deci}   &  deci   & \si{\deci}  \\
\si[prefixes-as-symbols=false]{\zetta} &  zetta &  \si{\zetta}  & \si[prefixes-as-symbols=false]{\centi}  &  centi  & \si{\centi} \\\bottomrule
\end{tabular}
\end{table}
```
Now version 3 says 

! Package siunitx Error: Found prefix part with no unit.

**Comment by josephwright** [comment]
This is by-design: you can use a 'no op' unit:
```latex
\documentclass{article}
\usepackage{booktabs}
\usepackage{siunitx}
\DeclareSIUnit\noop{\relax}
\begin{document}
\begin{tabular}{llllll}
\toprule
Factor & Nombre & Símbolo &Factor & Nombre & Símbolo\\
\midrule
\si[prefixes-as-symbols=false]{\yotta\noop} &  yotta &  \si{\yotta\noop}  & \si[prefixes-as-symbols=false]{\deci\noop}   &  deci   & \si{\deci\noop}  \\
\si[prefixes-as-symbols=false]{\zetta\noop} &  zetta &  \si{\zetta\noop}  & \si[prefixes-as-symbols=false]{\centi\noop}  &  centi  & \si{\centi\noop} \\\bottomrule
\end{tabular}
\end{document}
```

**Comment by rafaelpap** [comment]
[kk.pdf](https://github.com/josephwright/siunitx/files/6513566/kk.pdf)
[kk2.pdf](https://github.com/josephwright/siunitx/files/6513567/kk2.pdf)

But using v3 produces de output in kk.pdf and adding [=v2] to \usepackage{siunitx} produces kk2.pdf which is different. I am using 3.0.0 should I update?

**Comment by rafaelpap** [comment]
I am not able to understand latex programming but looking at the definition of prefixes-as-symbols it seems it uses prefix-mode=extract-exponent. The Table 18 says prefix-mode is an option to qty. If \si is translated to \unit maybe this is the source of my problem. Excuse me if this is just rumbling. 
I have been able to reproduce the behavior of v2 doing:
\qty[prefix-mode=extract-exponent,print-unity-mantissa=false]{1}{\yotta\noop} &  yotta &  \si{\yotta\noop}  &
instead of
\si[prefixes-as-symbols=false]{\yotta\noop} &  yotta &  \si{\yotta\noop}  &

Not sure if it is overkill.

Thanks a lot for your continuing support.

**Comment by josephwright** [comment]
I'll add a short demo to the manual to cover this: a couple of custom commands make it a bit clearer.
