### ISSUE TITLE
Removed units not mentioned in the manual.

### ISSUE THREAD

**Issue by rafaelpap** [josephwright/siunitx#438]
The units:
atomicmassunit, bohr, clight, electronmass, elementarycharge, hartree, plackbar
were included under Non-SI units whose values in SI units must be obtained experimentally or Other non-SI units in version 2.
They are not defined in version 3 and there is no warning in the manual.
Is there a list of accepted non-SI units somewhere?

Thanks again,

**Comment by josephwright** [comment]
I covered this in the change log, although perhaps that's not obvious
```
- Update unit support to 9th edition of SI Brochure
```
where they've just gone.

I'll add something to the manual.
