### ISSUE TITLE
separate-uncertainty different behaviour with qtylist and qty.

### ISSUE THREAD

**Issue by rafaelpap** [josephwright/siunitx#441]
Using separate-uncertainty with `\SIlist` and `\SI` in version 2 put every number inside brackets.
In version 3 using `\qty` gives the same result than version 2 `\SI` but `\qtylist` does not use brackets.
[qtylist.pdf](https://github.com/josephwright/siunitx/files/6521964/qtylist.pdf)
```latex
\documentclass{article}
\usepackage{siunitx}
\begin{document}
\qty[separate-uncertainty]{5.4(3)}{\kilo\joule\per\mol} and
\qty[separate-uncertainty]{7.8(2)}{\kilo\joule\per\mol}.

\qtylist[separate-uncertainty]{5.4(3);7.8(2)}{\kilo\joule\per\mol}.
\end{document}
```
Am I doing something wrong?

BTW, in the description of bracket-ambiguous-numbers there is a typo: seperate-uncertainty-units instead of separate-...

**Comment by josephwright** [comment]
Typo sorted in d6340f9f7efcc3c66e6a77336e0b4b9a566e843a - I'll look at the main issue

**Comment by josephwright** [comment]
I see where this is coming from - working out the 'best' solution is tricky!

**Comment by rafaelpap** [comment]
No hurry on my part. Thanks,

**Comment by josephwright** [comment]
I thought this would be relatively easy, but looking in detail there are some harder aspects: I will need a little while to fix it (this whole area is super-tricky).
