### ISSUE TITLE
Missing coloring of negative numbers with table-format

### ISSUE THREAD

**Issue by bersbersbers** [josephwright/siunitx#444]
This is in v3.0.3:
![image](https://user-images.githubusercontent.com/12128514/119155082-173f2c00-ba53-11eb-9f6c-fa4363b9d332.png)

```latex
\documentclass{article}
\usepackage{siunitx}
\begin{document}
\tablenum[negative-color=red, table-format=3.1]{-1.0}
\end{document}
```

**Comment by josephwright** [comment]
The `table-format` doesn't include the sign, so all bets are off really.

**Comment by josephwright** [comment]
I've also adjusted one oddity about colour: with upcoming v3.0.4 you don't get any colour here at all (as I say, it's not part of the format).

**Comment by bersbersbers** [comment]
Alright, I agreed. I had noticed that `table-format` does not play nicely with the sign, as it is longer than a digit. Even `table-format=2.0` lead to box warnings for `-1`. I have removed `table-format` from my documents completely.

**Comment by josephwright** [comment]
@bersbersbers  `table-format` is much _better_ in most cases than the centre-the-decimal-marker plan - you are _supposed_ to reserve space for signs if they are in your input!

**Comment by josephwright** [comment]
Note that signs are wider than digits:
```latex
\documentclass{article}
\begin{document}
\setbox0=\hbox{$12$}\showthe\wd0
\setbox0=\hbox{$-1$}\showthe\wd0
\end{document}
```

**Comment by bersbersbers** [comment]
> Note that signs are wider than digits:
> 
> ```
> \documentclass{article}
> \begin{document}
> \setbox0=\hbox{$12$}\showthe\wd0
> \setbox0=\hbox{$-1$}\showthe\wd0
> \end{document}
> ```

Yes, I am aware ;) - see https://github.com/josephwright/siunitx/issues/444#issuecomment-846011982

> @bersbersbers `table-format` is much _better_ in most cases than the centre-the-decimal-marker plan - you are _supposed_ to reserve space for signs if they are in your input!

Hmm - how do you suggest I reserve that space? `table-format` is incompatible with `negative-color` as you say - and for `-1` I have to reserve 3 digits before the decimal character to avoid overfull box warnings. Or what am I missing? I am actually pretty happy without `table-format`, I think.

**Comment by josephwright** [comment]
> Hmm - how do you suggest I reserve that space? `table-format` is incompatible with `negative-color` as you say - and for `-1` I have to reserve 3 digits before the decimal character to avoid overfull box warnings. Or what am I missing? I am actually pretty happy without `table-format`, I think.

If you do not supply `table-format`, the only way to centre material is by putting the `.` in the middle of the cell. That's fine if you have roughly symmetrical values, but it looks bad if they are not. There's no incompatibility between `table-format` and colour: what is true is that something like `table-format = 3.1` simply doesn't allow for any sign at all. As such, if you then put a number with a sign in such a cell, the result is undefined. You need to allow for a sign: `table-format = +3.1` or similar.

**Comment by bersbersbers** [comment]
> You need to allow for a sign: `table-format = +3.1` or similar.

Thank you! I did not know I could include the sign in the `table-format`. Out of 33 examples showing `table-format = ` in the manual, exactly *one* is with `table-format = +`, so I must have overlooked that :)

**Comment by bersbersbers** [comment]
Alright, this is working now in v3.0.4:

```latex
\documentclass{article}
\usepackage{siunitx}
\begin{document}
\tablenum[table-format=-1.1, negative-color=red]{-1.0}
\end{document}
```

This is not (all black) - is this intended?

```latex
\documentclass{article}
\usepackage{siunitx}
\begin{document}
\tablenum[table-format=+1.1, negative-color=red]{-1.0}
\end{document}
```

I did not see any documentation about differences between `+` and `-` in the documentation of `table-format`.
