### ISSUE TITLE
\bar unit removed but still referenced as usable.

### ISSUE THREAD

**Issue by rafaelpap** [josephwright/siunitx#448]
It seems than the \bar unit has been removed. It does not appears in the non-si units at table 3. But in page 7 the following paragraph seems to imply otherwise

It is possible to set up the unit macros to be available outside of the \qty and
\unit functions. This is not the standard behaviour as there is the risk of name clashes
(for example, \bar is used by other packages, and several packages define \degree).
Full details of using ‘stand alone’ units are found in 4.9.

**Comment by josephwright** [comment]
Oops - thanks. I've adjusted the docs plus added it to the list of removed units.
