### ISSUE TITLE
Unit command superscript and subscript issues

### ISSUE THREAD

**Issue by wrfwerrr** [josephwright/siunitx#449]
I need 2 to be a superscript and b not to be a superscript, similar to the use of the inline math formula, b will automatically become a superscript if I use `\unit`:
```latex
\unit{a^{2}b}
```
Unless you add ~ between 2 and b, but that adds extra space:
```latex
\unit{a^{2}~b}
```
Or use two `\unit`s:
```latex
\unit{a^{2}}\unit{b}
```
Is there a good solution

**Comment by josephwright** [comment]
Something not right here: give me a few minutes!

**Comment by josephwright** [comment]
OK, what's going on it that I'd not expected at all that someone might have a superscript or subscript in the _middle_ of a unit. That means that I've set up such that `a^bc.de` will grab `bc` as the superscript (not deliberately - I was just working on units looking like `<name>^<power>`). I can see that this might be somewhat surprising if one does `a^{2}b`, but at the same time I'm wondering about the entire semantics here. What's the unit involved?
