### ISSUE TITLE
Can't use fractions like 1/2 in v3 but can in v2

### ISSUE THREAD

**Issue by syvshc** [josephwright/siunitx#450]
In v2 I could write
```latex
\documentclass{article}
\usepackage{siunitx}[=v2]
\begin{document}
    \si{1/3}
\end{document}
```
it will output an `1/3`. 

But in v3 I can't, if I write
```latex
\documentclass{article}
\usepackage{siunitx}
\begin{document}
    \num{1/3}
\end{document}
```
it will give an error
```
! Package siunitx Error: Invalid number '1/3'.

For immediate help type H <return>.
 ...

l.4     \num{1/3}
```

**Comment by josephwright** [comment]
This is one of the documented changes; on reflection, the `quotient` business didn't fit well with a lot of other stuff. You should be fine with `\num[parse-numbers = false]{\frac{1}{2}}`.
