### ISSUE TITLE
Global "forbid-literal-units" throws error at \begin{document}

### ISSUE THREAD

**Issue by Bosef1** [josephwright/siunitx#452]

**Comment by Bosef1** [comment]
I am using MiKTeX 21.3, with siunitx v3.0.2, and I think I have identified a bug where siunitx throws an error at \begin{document} if "forbid-literal-units=t" is set globally before \begin{document}.  I think this a problem with siunitx independent of the MiKTeX build.

Here is a very simple article that demonstrates the problem.
```
\documentclass{article}

%% Load siunitx, and set forbid-literal-units=true before \begin{document}
\usepackage{siunitx}

\sisetup{
  forbid-literal-units = true,
}

%% siunitx throws an error when \begin{document} is called.
\begin{document}
Hello world
\end{document}
```
I have attached a copy of the LaTeX log illustrating the error here:
[forbid-literal.log](https://github.com/josephwright/siunitx/files/6535761/forbid-literal.log)

I took a look at my version of `siunitx.sty`, 2021-05-19, 3.0.2.  The problem seems to be occuring in this block of code between lines 6092-5:
```      \tl_set:Nn \l__siunitx_symbol_tmpa_tl { \mathrm { m } \cdot \mathrm { s } }
      \tl_set:Nn \l_siunitx_unit_font_tl { \mathrm }
      \siunitx_unit_format:nN { m . s } \l__siunitx_symbol_tmpb_tl
      \tl_if_eq:NNTF \l__siunitx_symbol_tmpa_tl \l__siunitx_symbol_tmpb_tl
```
This block is part of an \AtBeginDocument macro.  It appears the command on line 6094, `\siunitx_unit_format:nN { m . s }`, is what is causing the problem, and when the \AtBeginDocument  macro is called, that is when it is evaluated, which is why the document throws an error at that point.

I edited my siunitx.sty file, to read `\siunitx_unit_format:nN { \meter \second }`; that is, I replaced the literals with units, and that seemed to eliminate the crash.  I don't know if this a good solution, as it may break something else that is looking for literals at that point.

Let me know if you need any further information, or if this is not a problem, and there is a preferred workaround on the user side.

**Comment by josephwright** [comment]
Thanks - will be fixed in an update later today.

**Comment by Bosef1** [comment]
Thanks much.  I pulled siunitx.sty 3.0.6, and ran some quick tests.  It appears your fix solved the problem.
