### ISSUE TITLE
Error when changing language settings on-the-fly in non-math mode [v3]

### ISSUE THREAD

**Issue by MaxSchambach** [josephwright/siunitx#457]
# Description
We have come across a bug quite similar to the resolved #430 .
When using `babel` and the `locale` setting of `siunitx` the behavior of #430 reappears when changing the language on-the-fly via `babel`'s `\selectlanguage` or the `otherlangauge` environment.

E.g. see this minimal non-working example:

```latex
\documentclass{article}
\usepackage[english]{babel}
\usepackage[mode=match]{siunitx}

\addto\extrasngerman{\sisetup{locale = DE}}
\addto\extrasenglish{\sisetup{locale = UK}}

\begin{document}
\selectlanguage{english}
$\num{2e-25}$ \num{2e-25}
\end{document}
```

Weirdly, this even fails, wenn the langauge is not even changed, as in the example above. All combinations of `english` and/or `ngerman` will lead to the same bug as in #430 , namely that in text mode `\times` resp. `\cdot` is not wrapped in math.

**Comment by josephwright** [comment]
OK, I see why this is happening - I need to think about the best fix
