### ISSUE TITLE
"output-exponent-marker" causes an error with newest update

### ISSUE THREAD

**Issue by juuf** [josephwright/siunitx#458]
Since the recent update, I am getting an error when compiling my script. This is the argument I use:
`\sisetup{output-exponent-marker=\ensuremath{\mathrm{e}}}`

And the is is the error mesage:
`LaTeX3 Error: The key 'siunitx/output-exponent-marker' is unknown and is(LaTeX3) being ignored. ...t-exponent-marker=\ensuremath{\mathrm{e}}}`

Do you know where the problem is?

**Comment by josephwright** [comment]
My fault - I simply forgot this option
