### ISSUE TITLE
Support for siunitx.cfg in v3

### ISSUE THREAD

**Issue by jpcirrus** [josephwright/siunitx#460]
Thanks for `siunitx`.

I see that `siunitx.cfg` is no longer supported in version 3. Is that intentional, as I have all my custom units and qualifiers configured there to save duplication in every source file?

**Comment by josephwright** [comment]
The reason I've removed this is that I'm concerned on balance that

**Comment by josephwright** [comment]
Oops - wrong issue closed!

**Comment by josephwright** [comment]
The background here is that I added `.cfg` files modelled on some LaTeX core ideas, but those are about 'system-dependent' stuff (mainly historical about different installations). Looking again at it, I realised that having a `.cfg` file loaded by `siunitx` means that apparently identical sources can give a different result on different systems - not ideal.

That of course doesn't mean you can't have a local file, it's just that I don't feel it should be auto-loaded. Something like
```latex
\input{local-siunitx-config.tex}
```
for a shared `local-siunitx-config` file in your `~/texmf` (or similar) is my suggestion.

I should explain this in the manual: I will add a section and note it in the v2 to v3 part.

**Comment by jpcirrus** [comment]
Yes, I used the `\input` macro to solve the issue in my currert document. I follow your thinking, and think a note in the manual would have clarified for me that this was intentional, instead of an ommission due to the significant restructuring you did for v3. Thanks, your work is much appreciated.
