### ISSUE TITLE
Symbol for litre

### ISSUE THREAD

**Issue by wehro** [josephwright/siunitx#462]
The SI brochure allows lower-case ‘l’ and upper-case ‘L’ as symbols for the litre unit. The current version of this package only allows ‘L’. It should be possible for the user to choose ‘l’.

**Comment by josephwright** [comment]
For v2, I made `\litre` and `\liter` work differently, but that wasn't the best idea in the world, so for v3 I've standardised on one format. However, that only means that the 'out of the box' symbols are the same. You can use
```latex
\DeclareSIUnit \litre { l }
```
to set up a lowercase value. That's always been possible - I'm not sure what else I can really do here.

**Comment by wehro** [comment]
I had in mind an option like `litre=lowercase`, but I can achieve what I want with `\DeclareSIUnit`, of course.
