### ISSUE TITLE
`\qtylist` breaks with `mode=text` and `output-decimal-marker={,}`

### ISSUE THREAD

**Issue by PhelypeOleinik** [josephwright/siunitx#463]
The example:
```latex
\documentclass{article}
\usepackage{siunitx}
\sisetup{
  mode = text,
  output-decimal-marker = {,},
}
\begin{document}
\qty{1.83}{\watt}
\qtylist{1.83}{\watt}
\end{document}
```
breaks with
```latex
! Missing $ inserted.
<inserted text> 
                $
l.10 \qtylist{1.83}{\watt}
                          
?
```

Note that `\qty` works fine, as does using `mode = math` or `output-decimal-marker = .`.

**Comment by PhelypeOleinik** [comment]
Probably too simplistic, but maybe it helps pinpoint the issue:  changing line 3141 here:
https://github.com/josephwright/siunitx/blob/2a6b04c7bcba42b61ce9c5203d8a3b6400be2184/siunitx-number.dtx#L3140-L3143
to:
```latex
        \str_if_eq:VnTF \l_siunitx_number_output_decimal_tl { , }
          { \mode_if_math:TF { \exp_not:N \mathord } { \use:n } } % changed
          { \use:n }
            { \exp_not:V \l_siunitx_number_output_decimal_tl }
```
seems to fix the problem.

**Comment by josephwright** [comment]
@PhelypeOleinik  That's in the 'wrong' place as the number formatter should return math-mode content ... I guess I've missed something in the `print` module.
