### ISSUE TITLE
\DeclareSIUnit\litre{\liter} causes document to never finish compiling

### ISSUE THREAD

**Issue by Canageek** [josephwright/siunitx#466]
The following document will not finish compiling in either lualatex or pdflatex:

```
\documentclass{article}
\usepackage{siunitx}
\DeclareSIUnit\litre{\liter}
%\DeclareSIUnit\angstrom{Å}

\begin{document}
%\SI{1}{\angstrom}
\SI{1}{\litre}
\end{document}
```

However, the following document works fine:
```
\documentclass{article}
\usepackage{siunitx}
%\DeclareSIUnit\litre{\liter}
\DeclareSIUnit\angstrom{Å}

\begin{document}
\SI{1}{\angstrom}
%\SI{1}{\litre}
\end{document}
```

**Comment by rafaelpap** [comment]
Maybe is a case of circular definition. In the sources:

\siunitx_declare_unit:Nn \litre            { L }
\siunitx_declare_unit:Nn \liter            { \litre }

**Comment by josephwright** [comment]
Hmm, yes, this is tricky. The `\metre` case has been there from at least v2.0, but I've adjusted `\litre`/`\liter` for v3 as the older approach felt rather arbitrary.

Picking up loops is hard-to-impossible in a macro language, so perhaps this is a job for documentation? I suppose the alternative is a one-level abstraction for both spelling variants, but I'm not sure about that either.

Thoughts welcome on the best way forward.

**Comment by Canageek** [comment]
Right now I've just replaced it with "\def\litre{\Liter}"

My obvious workaround would be don't force people to redefine litre/liter to pick between mL and ml. You should never be using ml and mL in the same document anyway, so have \litre and \liter be synonyms, then have an option:

    volume-base-unit-case = upper|lower

that you put inside a \sisetup at the start of your document. I always prefer using a clear setting to redefining things inside the document (my standard reaction to which is "oh god, I'm going to break something".

**Comment by josephwright** [comment]
I am going to document the link between `\liter` and `\litre`, and between `\meter` and `\metre`, more clearly. I hope this will address the confusion.

**Comment by josephwright** [comment]
I hope the notes I've added address this issue.
