### ISSUE TITLE
round-integer-to-decimal=false functionality in v3?

### ISSUE THREAD

**Issue by wahspilihp** [josephwright/siunitx#468]
Is there a way, other than manually turning rounding off for individual numbers/quantities, to get the same effect as the v2 default option `round-integer-to-decimal=false` in v3? There does not appear to be any reference to the removed option in the manual, but I'm not sure if this is a documentation bug or an enhancement request.

Essentially the desired behaviour is the reverse of #55, in that absence of decimal places is significant.

**Comment by josephwright** [comment]
You want `round-pad = false`, which isn't quite a straight replacement for the older setting
```
\documentclass{article}
\usepackage{siunitx}
\sisetup{round-mode = places}
\begin{document}

\num{12} \num{12.3} \num{12.34} \num{2.345}

\sisetup{round-pad = false}

\num{12} \num{12.3} \num{12.34} \num{2.345}

\end{document}
```

I'll look to make this clearer in the docs.

**Comment by josephwright** [comment]
Hopefully covered by 140c4dbc527eccd1f0f2e47403812da4c9c782b5

**Comment by wahspilihp** [comment]
Thanks, that achieves the desired effect and is more likely to "do what I mean" for decimals in general.
