### ISSUE TITLE
! LaTeX cmd Error: Command '\unit' already defined!

### ISSUE THREAD

**Issue by LuVo1924** [josephwright/siunitx#474]
Due to a computer crash I had to reinstall latex (full schema). Now the following error message appears for documents with siunitx: "! LaTeX cmd Error: Command '\ unit' already defined!" All other documents work. I tried it under Windows10, TeXLive, siunitx and Kile (each the latest version). Who has an idea?

**Comment by u-fischer** [comment]
well your document defines \unit somewhere, and as siunitx wants to define it too, this errors. You will have to identify which code in your document is responsable.

**Comment by josephwright** [comment]
As @u-fischer says, this is likely locally defined. I know that `\unit` is a reasonably generic name, but I didn't find a clash in testing, so I'd need to see your source.

**Comment by josephwright** [comment]
Without more information, this is not a valid bug report I'm afraid.
