### ISSUE TITLE
Support <length>:<angle> format for complex values

### ISSUE THREAD

**Issue by josephwright** [josephwright/siunitx#475]
The v3 split of `\complexqty` from `\qty` allows the possibility to support something like
```latex
\complexqty{1.23:30}{\metre}
```
I guess what I need to know is whether this 'works' for users, if they need radians, plus of course I have to think about internal storage. (I assume conversion between the two forms is desirable.)

**Comment by jmollera** [comment]
I use a lot of complex numbers in polar form, mainly in degrees but also in radians, so I have created the command:
```
% complex polar in degrees
\providecommand*{\qtypd}[3]{\ensuremath{\num{#1}_{\angle\ang{#2}}\,\unit{#3}}}

% complex polar in radians
\providecommand*{\qtypr}[3]{\ensuremath{\num{#1}_{\angle\SI{#2}{rad}}\,\unit{#3}}}
```

This renders the angle in subscript form, but of course no everybody might agree on this.

**Comment by josephwright** [comment]
@jmollera Thanks: can you point me to where this form is used in publication?

**Comment by jmollera** [comment]
> @jmollera Thanks: can you point me to where this form is used in publication?

I use it in electrical engineering documents. AC voltages, impedances, currents  and powers are complex numbers, usually expressed in polar form.

**Comment by josephwright** [comment]
Wasn't quite what I meant ;) I was looking for examples in professionally-typeset material, so journals or textbooks.

**Comment by jmollera** [comment]
See the following links:

Pages 1.18 to 1.30, 5.6, 6.4 to 6.11, 10.9 to 10.26 [HANDBOOK OF ELECTRIC POWER CALCULATIONS](https://www.mz3r.com/fa/wp-content/uploads/2012/02/books/ebooks/%5BMcGraw%20Hill%5D%20-%20Handbook%20of%20Electric%20Power%20Calculations.pdf)

Pages 238, 239, ... [Problems and Solution](https://onlinelibrary.wiley.com/doi/pdf/10.1002/9781118029008.app3)

Pages 13, 26 to 36, 39 ... [ANALYSIS OF POWER SYSTEMS UNDER FAULT CONDITIONS](http://csus-dspace.calstate.edu/bitstream/handle/10211.9/1369/PDF.pdf)

Pages 5, 6, ...  [Tutorial on Symmetrical Components](https://cms-cdn.selinc.com/assets/Literature/Publications/White%20Papers/LWP0010-02_TutorialSymmetrical-Pt2_AH_20201019.pdf?v=20201020-155433)

**Comment by josephwright** [comment]
Taking a random example from those, something like
```latex
$2030.8\angle\mathord{-}167.7^{\circ}\,\mathrm{A}$
```
seems to be the desired output, whereas others seem to omit the `^{\circ}` part. I'll probably start with the version that includes it.

**Comment by jmollera** [comment]
> Taking a random example from those, something like
> 
> ```
> $2030.8\angle\mathord{-}167.7^{\circ}\,\mathrm{A}$
> ```
> 
> seems to be the desired output, whereas others seem to omit the `^{\circ}` part. I'll probably start with the version that includes it.

Looks fine!
The examples without the `^{\circ}` part are probably expressing the angle in radians instead of degrees.

**Comment by josephwright** [comment]
@jmollera OK, I'm thinking of `complex-number-mode` to choose between something like `real-imaginary` and `magnitude-angle`, with then the possibility to fine-tune the latter with some additional option. For the angle, I think `complex-angle-input` and `complex-angle-output`, both taking `degree` and `radian`. The other obvious thing is dealing with the range for angles: if I'm taking input in `real-imaginary`, I'll have to know the desired output range for the angle. I can imagine doing that with an 'offset' or having one or more choices of range - thoughts?

**Comment by jmollera** [comment]
I like your proposed strategy, except for the part regarding ranges. 
Complex number are like 2D-vectors represented in a plane with two axes, so the concept of range is a little fuzzy. In the Cartesian representation you could have a rage for the real part, a range for the imaginary part, or a range for both parts, and in the polar representation you could have a range for the magnitude, a range for the angle, or also a range for both. For this reason,  I don't see  the need for an angle rage; for example, in my professional work as an electrical engineer, I've never seen or had the need to express a voltage as: 240 ∠ 5º to 6 º V.

Thanks for your excellent work!

**Comment by josephwright** [comment]
@jmollera I meant a different kind of range! Given input in Cartesian form, conversion to polar form requires a decision about what angle range to map to: typically either 0 to 360 or -180 to 180, but could be something else. (And of course could be in radians or degrees.) I'm sure I'll come up with something vaguely sensible.

**Comment by jmollera** [comment]
@josephwright Sorry, I misunderstood you. The two ranges you mention are two only sensible options that come to my mind. I understand that you are not considering mapping to grads (0 to 400), does anyone use them?

**Comment by jmollera** [comment]
I think computer languages favor the mapping -180 to 180.

The FORTRAN  `ATAN2(Y, X)` function and the Python `math.atan2(y, x)` function, both return an angle in the range: -π < angle ≤ π.

C and C++ `atan2(y,x)` function also return the angle in that range.

**Comment by Rmano** [comment]
I agree about the range, for computed/converted values, but give an option to not normalize. Sometime I have to write "notice that \qtycomplez{1:390} is the same as \qtycomplex{1:30}".... You know, students.... ;-P
