### ISSUE TITLE
Rounding of mantissa containing only zeros

### ISSUE THREAD

**Issue by FloDX** [josephwright/siunitx#477]
In version 2, I used the round feature for rounding mantissas containing only zeros to a standard format, for example for values obtained by an automated output with a given format. Version 2 gave me the expected result, when rounding as in the following example

```
\documentclass {article}
\usepackage{siunitx}

\begin{document}
  \SI[round-mode=places,round-precision=2]{0.000000}{\percent}
\end{document}
```

which led to "0.00 %". Unfortunately, version 3 seems not to deal with a zero mantissa and gives the non-rounded result "0.000 000 %", instead.

Of course, no real rounding has to be done here, but I liked the possibility of formatting to a fixed number of decimal places regardless of the input number. Therefore, it would be great if version 3 could also handle this case.

**Comment by josephwright** [comment]
As this is places not figures, I feel it's a bug - fix hopefully today.
