### ISSUE TITLE
Error using \DeclareSIPrefix on \micro in v3.0.11

### ISSUE THREAD

**Issue by JoeHannes90** [josephwright/siunitx#478]
Hello and thank you for siunitx.

In our template we use different fonts for text and math. In v2 we used the math-micro option to ensure the correct font in math mode.

In v3 we redefined \micro:
```

\documentclass{article}
\usepackage{palatino}
\usepackage[mode=match]{siunitx}
\DeclareSIPrefix{\micro}{\ifmmode{\text{\fontencoding{TS1}\fontfamily{cmr}\selectfont{\textmu}}}\else{\textmu}\fi}{-6}

\begin{document}
$\qty{2e-25}{\micro\metre}$\\
\qty{2e-25}{\micro\metre}
\end{document} 
```

The example above worked before, but breaks in v 3.0.11.
Note: This example already considers the swap of the 2nd and the 3rd argument of  \DeclareSIPrefix, that was fixed in v3.0.11.

Edit: I just realized that the example still works if \DeclareSIPrefix is used with \AtBeginDocument.

**Comment by josephwright** [comment]
Hmm, I think I see where the issue might lie. I might need some more info - give me a bit of time to investigate.

**Comment by josephwright** [comment]
Phew, just some stray debug code: fix out today

**Comment by josephwright** [comment]
BTW, is there a reason for your rather complex setup rather than just
```latex
\documentclass{article}
\usepackage{palatino}
\usepackage[mode=match]{siunitx}
\DeclareSIPrefix{\micro}{\text{\textmu}}{-6}

\begin{document}
$\qty{2e-25}{\micro\metre}$\\
\qty{2e-25}{\micro\metre}
\end{document}
```

**Comment by JoeHannes90** [comment]
The reason for our complex setup is that we want siunitx to use the math font in math mode (e.g. Computer Modern) and the text font in text mode (e.g. Palatino). This works great with mode=match, with the exception of the micro symbol ( the code docu says: "Only a text mode command is available for \micro in the standard set up"). 

With \DeclareSIPrefix{\micro}{\text{\textmu}}{-6} text font is used for the micro symbol in both, math and text mode.
