### ISSUE TITLE
\qty errors 'Missing $ inserted'

### ISSUE THREAD

**Issue by jvdoorn** [josephwright/siunitx#479]
Using version`3.0.11` I get an error whenever I use `\qty`. Par example writing `\qty{10}{\volt}` errors saying `Missing $ inserted.`. I am not specifying any options (so just `\usepackage{siunitx}`). Could you help me out here?

**Comment by jvdoorn** [comment]
Weirdly enough it does work when using `\num{10}\unit{\volt}`.

**Comment by josephwright** [comment]
Can you post your log?

**Comment by jvdoorn** [comment]
I figured out the issue. I was also using the `physics` package, which also defines a `qty`.

**Comment by josephwright** [comment]
Links to https://github.com/josephwright/siunitx/issues/447 but at present invalid (it's documented behaviour).
