### ISSUE TITLE
Spurious show in \__siunitx_symbol_if_replace:NnTF

### ISSUE THREAD

**Issue by callegar** [josephwright/siunitx#480]
The definition of `\__siunitx_symbol_if_replace:NnTF` does not match that in the code documentation and contains a
`\show\l__siunitx_symbol_tmpa_tl \show\l__siunitx_symbol_tmpb_tl` in the false path that causes the LaTeX compilation to hang.

**Comment by callegar** [comment]
I see it is probably already fixed in git, sorry for the noise.

**Comment by josephwright** [comment]
Duplicate of https://github.com/josephwright/siunitx/issues/478
