### ISSUE TITLE
The units package cannot be loaded with v3

### ISSUE THREAD

**Issue by josephwright** [josephwright/siunitx#482]
As they both define `\unit` - links to https://github.com/josephwright/siunitx/issues/447.

**Comment by josephwright** [comment]
Technically a bug, but I think has to wait for some interface and so at present hold for v3.1.

**Comment by Rmano** [comment]
maybe it's a feature. Why load `units` together with `siunitx`?

**Comment by josephwright** [comment]
@Rmano  Well yes, it's borderline (hence not rushing to fix): I guess what I mean is that really I should fix the whole interface selection idea, then people can mix whatever they want to. Just because I think it's a daft idea, that's not my decision in a sense.

**Comment by josephwright** [comment]
Using a temporary fix until I have a final idea about this and related areas.
