### ISSUE TITLE
Character problem with fourier in text mode

### ISSUE THREAD

**Issue by Lionel-dS** [josephwright/siunitx#486]
I'm using siunitx 3.0.12 along with fourier.

- _without_ fourier, the `\ohm` unit is displayed correctly in both math and text mode
- _with_ fourier, the `\ohm` unit is displayed correctly in math mode, but is replaced by a black square in text mode.

Paradoxically, there is no problem with the `\micro` prefix.

Thanks again for this great work!

**Comment by josephwright** [comment]
The issue seems to be that `\textohm` doesn't work with `fourier`: it's the 'standard' text mode setting in v3. Looking back at the v2 code, I think the only solution I can offer is to force use of the math-mode Omega in text mode: would that work?

**Comment by Lionel-dS** [comment]
I like fourier because the text and math fonts are very close. Then this may work.

The remaining issue will be to follow the text shape...

**Comment by josephwright** [comment]
@Lionel-dS Like I said, it's a question of what's _available_ as much as anything.

**Comment by Lionel-dS** [comment]
OK, thx!
