### ISSUE TITLE
Endless compilation when suffixing unit with {}

### ISSUE THREAD

**Issue by bersbersbers** [josephwright/siunitx#487]
This MWE causes compilation to go on forever with siunitx 3.0.12:

```latex
\documentclass{article}
\usepackage{siunitx}
\begin{document}
    \qty{1}{\second{}} % note the extra {}!
\end{document}
```

This was working with ~3.0.5 IIRC. Even if it's invalid syntax, it should not lead to such drastic, hard-to-trace errors.

**Comment by josephwright** [comment]
Fix coming up: for the present, use
```latex
\documentclass{article}
\usepackage{siunitx}
\ExplSyntaxOn
\cs_gset_protected:Npn \__siunitx_unit_format_literal_auxvii:nN #1#2
  {
    \str_if_eq:nnTF {#2} { \protect }
      { \__siunitx_unit_format_literal_auxviii:nN {#1} }
      { \__siunitx_unit_format_literal_auxv:nw {#1#2} }
  }
\ExplSyntaxOff
\begin{document}
  
    \qty{1}{\second{}}
\end{document}
```

**Comment by josephwright** [comment]
BTW, for me compilation hits an error well before it loops.

**Comment by bersbersbers** [comment]
Thanks!

> BTW, for me compilation hits an error well before it loops.

Interesting - I am using TeX Live on Linux, if that matters. Anyway, just making it work is perfect :)
