### ISSUE TITLE
Option [separate-uncertainty-units = repeat] misplaces exponents

### ISSUE THREAD

**Issue by jmollera** [josephwright/siunitx#490]
In **siunitx** version 2021-06-14, the following commands:
```
\qty{12.3(4)e-5}{\kilo\gram} \\
\sisetup{separate-uncertainty}
\qty[separate-uncertainty-units = bracket]{12.3(4)e-5}{\kilo\gram} \\
\qty[separate-uncertainty-units = single]{12.3(4)e-5}{\kilo\gram} \\
\qty[separate-uncertainty-units = repeat]{12.3(4)e-5}{\kilo\gram}
```
Print incorrectly the last line:
![Captura de pantalla 2021-06-16 210321](https://user-images.githubusercontent.com/77206640/122277572-53e13480-cee6-11eb-86a8-b5b6faba75bd.jpg)

**Comment by josephwright** [comment]
This one is also wrong in v2, it's just wrong in a different way. I think the issue really is I don't know what to do for a separate uncertainty where there is an exponent too: it's simply going to be ambiguous whatever I do with repeated units. The current outcome is at least mathematically sound.

**Comment by jmollera** [comment]
In my opinion, the output should be:
![Captura de pantalla 2021-06-16 224928](https://user-images.githubusercontent.com/77206640/122291503-2e0f5c00-cef5-11eb-80a2-3aac55c49ab7.jpg)

**Comment by josephwright** [comment]
OK, it's probably the best that can be done, although it does raise an issue that it means the _exponent_ printing is changed by a _unit_ setting.
