### ISSUE TITLE
Brackets around complex numbers with units

### ISSUE THREAD

**Issue by jmollera** [josephwright/siunitx#491]
In version 2, the command `\SI{2+j3}{\ohm}` printed: (2 + j3) Ω
While in version 3, the equivalent command `\qty{2+j3}{\ohm}` prints: 2 + j3 Ω

This looks OK when the quantity is isolated, but when the quantity is part of an equation, the new way of printing might be confusing. For example:

The v 2 command  `\SI{2+j3}{\ohm} \times \SI{5+j4}{\volt}` printed: (2 + j3) Ω × (5 + j4) V
The v 3 command  `\qty{2+j3}{\ohm} \times \qty{5+j4}{\volt}` prints: 2 + j3 Ω × 5 + j4 V

I think that the version with brackets is more clear.  Without brackets, you don't know whether the volt unit applies to 5 + j4, or applies only to j4 and 5 is a unitless number that multiplies  j3 Ω . Of course, you always can write `\(qty{2+j3}{\ohm}) \times (\qty{5+j4}{\volt})`, that prints:
(2 + j3 Ω) × (5 + j4 V), improving the output.

Was this removal of brackets in version 3 something intended?

**Comment by josephwright** [comment]
Must have missed that one - I'll look at it.
