### ISSUE TITLE
\Omega not rendered

### ISSUE THREAD

**Issue by tc-faid** [josephwright/siunitx#492]
Hello,

This bug appeared recently (a few weeks ago at most) with an up-to-date TeX Live 2021 distro on macOS 11.4.

In a command like \qty{1}{\ohm}, the number is rendered correctly but I only get a blank character instead of the unit. If I replace \ohm with \Omega, the same problem occurs.

What I can tell you:

- The command \Omega works correclty in math mode, outside of \qty.
- I'm using lualatex with fontspec loaded, but only with the default font.
- I reproduced the bug with a minimal file with only fontspec, mathtools and siunitx loaded, and siunitx is loaded without any option.
- If I type the greek character Ω directly inside the source code, then it's rendered correctly.
- If there are additional characters inside the unit, like \qty{1}{m\ohm}, those other characters are rendered correctly, only \ohm is missing. 
- The bug seems to occur only with \ohm and \Omega, no other character than I could find.

I attached the source example below, but had to rename it with a .txt extension otherwise it was rejected as unsupported by Github.

[test_siunitx_ohm.txt](https://github.com/josephwright/siunitx/files/6686108/test_siunitx_ohm.txt)

Thanks for your attention.

**Comment by josephwright** [comment]
Hmm, odd - I'll take a look at that

**Comment by josephwright** [comment]
Ah, I see the issue - links to #435 - I'll fix for the present and raise again with the team
