### ISSUE TITLE
retain-explicit-plus does not apply to the exponent in scientifc notation, print-implicit-plus does

### ISSUE THREAD

**Issue by gvdeynde** [josephwright/siunitx#493]
LuaLaTeX, siuntix 3.0.14

```
\documentclass{minimal}

\usepackage{siunitx}
\sisetup{
  exponent-mode=scientific,
  group-digits=false,
}

\begin{document}

\num[print-unity-mantissa=false, print-zero-exponent=true, retain-explicit-plus=true]{e+01},
\num[print-unity-mantissa=false, print-zero-exponent=true, retain-explicit-plus=true]{e+00},
\num[print-unity-mantissa=false, print-zero-exponent=true, retain-explicit-plus=true]{e-00},
\num[print-unity-mantissa=false, print-zero-exponent=true, retain-explicit-plus=true]{e-01}

\num[print-unity-mantissa=false, print-zero-exponent=true, print-implicit-plus=true]{e+01},
\num[print-unity-mantissa=false, print-zero-exponent=true, print-implicit-plus=true]{e+00},
\num[print-unity-mantissa=false, print-zero-exponent=true, print-implicit-plus=true]{e-00},
\num[print-unity-mantissa=false, print-zero-exponent=true, print-implicit-plus=true]{e-01}

\end{document}

```
![image](https://user-images.githubusercontent.com/5218893/122778123-fade1b80-d2ac-11eb-900f-c5638af74607.png)

Note that in the first line, the zero exponent (although there is an explicit '+' or '-' in the number in the input) has no sign in the output. In the second line, all four numbers have a sign in the exponent (the '-' does get converted to a '+', though). 

It feels a bit "inconsistent". Is this expected behaviour? 

How can I have always a sign in the exponent but not in the mantissa?

**Comment by josephwright** [comment]
I'll suppress the `+`  for a zero exponent. I'm not sure what to do about your second question - I've never provided a way to print a sign only for the exponent. Can you provide a bit of context?

**Comment by gvdeynde** [comment]
It's linked to [my question on tex.SE](https://tex.stackexchange.com/questions/599773/comparing-floating-point-numbers-and-indicate-common-digits). I want to compare the outcome of the calculation of a set of coefficients by a certain algorithm to a reference solution. I want to put the digits in common in green, digits that differ in red. Since I'm totally not used to programming in LaTeX, I resorted to Python. So I'm calculating the number of correct digits, splitting the number accordingly and Python spews out LaTeX code to format these numbers. But to get a nice alignment in a table, I would like to have a) always a sign for the mantissa and b) always a sign for the exponent. 

Screenshot in attachment. On the left side, since those are the reference values, I don't need to "split up" the number and both mantissa and exponent have a sign. On the right side, the newly (and badly for what it's worth) calculated values. I split up mantissa in correct digits that I wrap with a `\color{ForestGreen}` and the wrong digits that I wrap with `\color{OrangeRed}`. But then I need to "manually" put the `$\times$` and the exponent. And in this last part, it goes "wrong". I cannot force the exponent to have a sign in the exponent but not in the "faked" mantissa of the exponent (which I suppress using `[print-unity-mantissa=false]`. 

Hope this makes the use-case a bit more clear. 

Thanks for your support, btw. 

![image](https://user-images.githubusercontent.com/5218893/122884560-910e5200-d33e-11eb-9cc6-dc3595efa77e.png)

**Comment by josephwright** [comment]
The remaining part of this issue is at the enhancement side.
