### ISSUE TITLE
engineering option produces wrong result if input's exponent multiple of 3 and mantissa begining with zero

### ISSUE THREAD

**Issue by AntoineLatex** [josephwright/siunitx#494]
Hi,
I get a strange behavior since the V3 (all minor updates concerned)
When using option "exponent-mode = scientific" or none, my output is good.
But with "exponent-mode=engineering" I get the following issue

INPUT
\num[exponent-mode=engineering]{0.35e9}
\num[exponent-mode=engineering]{0.35e8}

FIRST OUTPUT: WRONG, 
350 :nnw x 10 6 
SECOND OUTPUT: OK
35 x 10 6

Is the error on my side or not?
[TestSIUNITXengineering.zip](https://github.com/josephwright/siunitx/files/6687312/TestSIUNITXengineering.zip)

**Comment by josephwright** [comment]
OK, I see where this comes from: I'd assumed that engineering notation would have positive exponents, basically

**Comment by josephwright** [comment]
Fix will go to CTAN tomorrow

**Comment by AntoineLatex** [comment]
Ok, It's all right, thank you for the reactivity ... and for this very helpfull package.Antoine Bosenvoyé : 21 juin 2021 à 23:59de : Joseph Wright ***@***.***>à : josephwright/siunitx ***@***.***>cc : AntoineLatex ***@***.***>, Author ***@***.***>objet : Re: [josephwright/siunitx] engineering option produces wrong result if input's exponent multiple of 3 and mantissa begining with zero (#494) Fix will go to CTAN tomorrow—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
