### ISSUE TITLE
\per macro causes an infinite loop

### ISSUE THREAD

**Issue by kourosh2** [josephwright/siunitx#495]
Hi, 

Sorry if this question has already been responded, I could not find it. 

I have recently updated my TeX distribution to TeXLive 2021 and siunitx package to 3.0.15.  Since the update, I noticed that whenever I have `\per` in my units without the unit in the numerator defined as macro pdflatex stuck in an infinite loop.  For example,
`\SI{10}{m \per s^2} `causes the pdflatex to stuck in an infinite loop but
`\SI{10}{\meter \per s^2}` compile without problem

Am I missing something?

Thanks,
Kourosh

**Comment by josephwright** [comment]
I'll have the fix to CTAN later today.

**Comment by kourosh2** [comment]
Perfect, thank you.  It is resolved.
