### ISSUE TITLE
Package keyvalue Error: Unknown option 'per' for package siunitx. \ProcessKeysOptions { siunitx }

### ISSUE THREAD

**Issue by bartoloide** [josephwright/siunitx#499]
Hey there,

I'm trying to use the siunitx, but I can't with this error. I don't know how to handle with this. =(

[https://imgur.com/g9kS8c3](url)

[https://imgur.com/THvJ0CP](url)

**Comment by josephwright** [comment]
The option has been called `per-mode` not just `per` since I released v2 in 2009; if you need to use v1 options, you'll need to load v2 (which has code to use v1 options): I didn't roll v1 options into v3.
```latex
\usepackage{siunitx}[=v2]
```

**Comment by josephwright** [comment]
I think this is (essentially) works for me.
