### ISSUE TITLE
option [per-mode = symbol] prints an extra "1"

### ISSUE THREAD

**Issue by jmollera** [josephwright/siunitx#500]
In version 2, the command `\SI[per-mode = symbol]{1.99}{\per\kilogram}`  printed 1.99/kg 

But now in version 3.0.17, the command `\qty[per-mode = symbol]{1.99}{\per\kilogram}` prints  -->  1.99 1/kg

**Comment by josephwright** [comment]
Ah, yes - I did wonder about this. I'm going to have to think a little about it: I'm not actually that sure any more that `\unit[per-mode = symbol]{\per\second}` should give `1/s` rather than `/s` anyway.

**Comment by josephwright** [comment]
But then I need to think about how to handle spacing with the 'proper' separation I've set up in v3. I'm away for a few days - this might take a week or so.

**Comment by josephwright** [comment]
OK, I have an idea - may be  day or two to upload.

**Comment by jmollera** [comment]
> OK, I have an idea - may be day or two to upload.

Thanks! There's no rush. In the meantime, I'm using a workaround; something like: `$\num{1.99}/\unit{\kilogram}$`
