### ISSUE TITLE
Endless compilation when using siunitx with kotex-utf

### ISSUE THREAD

**Issue by foci00** [josephwright/siunitx#502]
`siunitx` has stopped working with [`kotex-utf` ](https://ctan.org/pkg/kotex-utf) since v3.0.7.

MWE:
```latex
\documentclass{minimal}
\usepackage{siunitx}
\usepackage[utf]{kotex}
\begin{document}
\end{document}
```
Running with pdflatex, the compile takes forever regardless of the order the packages are loaded.

**Comment by josephwright** [comment]
OK, I see where this comes from. `kotex` handles UTF-8 in pdfTeX by using a single `\protected` macro then a catcode-12 token, not two catcode-13 tokens as is done with standard `inputenc`. What happens then is that I've set up symbols using catcode-13 tokens, and the two end up in conflict. I need to think of an elegant way out: hopefully won't take too long.

**Comment by josephwright** [comment]
First shows up with 71b78b89

**Comment by josephwright** [comment]
So it seems that this and https://github.com/josephwright/siunitx/issues/503 are related - I need to re-write the code there anyway, so I guess I'll do that for the other issue (which is clear-cut) and see what the impact is here!
