### ISSUE TITLE
Option `no-math` of package fontspec causes `\degree` to print nothing

### ISSUE THREAD

**Issue by mrpiggi** [josephwright/siunitx#505]
`\degree` prints nothing with v3 and `no-math` passed to `fontspec` (new issue from https://github.com/josephwright/siunitx/issues/351#issuecomment-880233006)
```latex
\documentclass{article}
\usepackage[no-math]{fontspec}
\usepackage{siunitx}
\begin{document}
ang: \ang{180}
degree: \SI{180}{\degree}?
Celsius: \SI{180}{\celsius}?
\end{document}
```

**Comment by josephwright** [comment]
This is happening as I've tried as far as possible to leave unit definitions with 'just the characters'. For the degree symbol, I know that doesn't work for classical LaTeX, so I swap out for `\text{\textdegree}`, which does work in all cases. However, I'd left the `fontspec` case alone as usually it can print a math mode degree symbol. I'll go with the easiest fix: just use the same setup for `fontspec` as without it (there's currently no public test for the `no-math` option, and it doesn't really seem worth asking for one here as it's something that can be fixed another way).

**Comment by josephwright** [comment]
Is a fix urgent, BTW? You should be fine with
```latex
\DeclareSIUnit[quantity-product = ]\degree{\text{\textdegree}}
\DeclareSIUnit\degreeCelsius{\text{\textdegree}C}
```
until I do the next release.

**Comment by mrpiggi** [comment]
Since a workaround exists, there is no urgency.

**Comment by josephwright** [comment]
@mrpiggi  OK, I'll wait a few days to see if there is anything else at the moment
