### ISSUE TITLE
Uncertainties with more digits only work in compact format

### ISSUE THREAD

**Issue by taaem** [josephwright/siunitx#506]
Hello,

In Siunitx V3 I have an issue, where `\num{-1.2 \pm 11.1}` throws an error, because it is not a valid number (I can provide the concrete error message if needed).
But `\num{-1.2(111)}` formats correctly as -1.2±11.1.
I think this might be a new bug because on V2 I didn't had this issue.

Regards

**Comment by josephwright** [comment]
Well something is not right ... but `1.2\pm11.1` isn't valid, so I think it's that `1.2(111)` should also lead to an error.

**Comment by taaem** [comment]
Why would `1.2\pm11.1` not be valid for specifying the uncertainty/error? 
Sorry if this is a stupid question.

**Comment by josephwright** [comment]
The uncertainty in a value has to be at most of the same order of magnitude as the value itself, otherwise the reading is meaningless.

**Comment by taaem** [comment]
For measurements yes, but in this case the uncertainty is a standard deviation of the mean, which can be of a different magnitude as the mean value itself.
