### ISSUE TITLE
Dimensions with "x" or "\times" throws an error: Invalid number 

### ISSUE THREAD

**Issue by jankokert** [josephwright/siunitx#509]
Since my last update on SIunitx using times symbol in \SI environment throws an error

e.g.:
\SI{1 x 1}{\meter}
or
\SI{1 \times 1}{\meter}

Error:
Package siunitx Error: Invalid number '1 x 1'. \SI{1 x 1}{\meter}
File ended while scanning use of __siunitx_quantity_parsed_aux:w.

**Comment by josephwright** [comment]
Duplicate of https://github.com/josephwright/siunitx/issues/504
