### ISSUE TITLE
Option table-text-alignment=none?

### ISSUE THREAD

**Issue by lvjr** [josephwright/siunitx#510]
`Tabularray` pacakge recently added support for `S` column of `siunitx` package using `\tablenum` command. But from the bug here (https://github.com/lvjr/tabularray/issues/40), it seems text alignments of `siunitx` conflict with those provided by `tabularray` package. It would be nice if `siunitx` could provide a `table-text-alignment=none` option and let `tabularray` do text alignments all by itself.

**Comment by josephwright** [comment]
Well with hindsight I have wondered if one should just `\multicolumn` in all 'non-numeric' cases ....

**Comment by lvjr** [comment]
Well, `\multicolumn{1}` is one of many LaTeX tricks users had to use before. One aim of `tabularray` package is to reduce the uses of these tricks when typesetting tables. In `tabularray`, `\multicolumn{1}` is treated as a normal `\SetCell`, and doesn't guard the cell from `siunitx`.

**Comment by josephwright** [comment]
@lvjr My point is `\multicolumn` entirely omits the template, so there is nothing to 'guard against'
