### ISSUE TITLE
Add Brazilian localization

### ISSUE THREAD

**Issue by gusbrs** [josephwright/siunitx#514]
Hi Joseph,

if you'd like to include localization for Brazilian Portuguese for `siunitx`, I can provide the translation for it, namely:

```latex
\DeclareTranslation{Brazilian}{to (numerical range)}{a}
```
The `and` key is already provided by `translations.sty` and is working fine.

This translation could also be used for Portuguese but, in this case, the `and` is not available.  Both of them would be:

```latex
\DeclareTranslation{Portuguese}{and}{e}
\DeclareTranslation{Portuguese}{to (numerical range)}{a}
```

**Comment by josephwright** [comment]
I'm happy to add: can you provide a PR?

**Comment by gusbrs** [comment]
@josephwright Done!

I took the liberty of including the respective languages to `siunitx-locale.lvt`. I hope I haven't overstepped my assignment in so doing. I made sure tests passed locally, and added `babel-portuges` to `tl_packages` (and hopefully there's no other package missing for the GitHub action).

**Comment by josephwright** [comment]
Closed by https://github.com/josephwright/siunitx/pull/599.
