### ISSUE TITLE
Incorrect exponent in uncertainty rounding

### ISSUE THREAD

**Issue by AxelKrypton** [josephwright/siunitx#524]
This is a follow up of #523, because, while using `v3.0.24`, I noticed there is still some corner case that is not yet correctly handled.

```latex
\listfiles
\documentclass[border=1mm]{standalone}
\usepackage{siunitx,booktabs,array,pifont}

\newcommand{\yes}{\ding{51}}
\newcommand{\noo}{\textcolor{red}{\ding{55}}}
\newcolumntype{L}{>{$}l<{$}}
\newcommand{\numberInCommand}{13646.0 +- 6.6}

\begin{document}
  \begin{tabular}{c
    S[table-format=1.5]
    @{${}\pm{}$}
    S[table-format=1.5]
    @{$\quad\to\quad$}
    S[table-format=1(1)e1, exponent-mode = scientific, round-mode = uncertainty, round-precision = 1]
    @{\quad}LL}
    \toprule
    & \multicolumn{2}{c}{Number} & {\texttt{siunitx v3.0.24}} & \text{Expected} & \text{Alternatively}\\
    \midrule
    \noo &   0.07724  &   0.09778  &    0.07724 +- 0.09778  &  0(1)  \times 10^{-1}  & 8(10)  \times 10^{-2} \\
    \bottomrule
  \end{tabular}
\end{document}
```
![test-1](https://user-images.githubusercontent.com/13135070/128323711-0bcd0acf-916b-4086-92fc-380dc121a1b8.png)

If I am not somehow mistaken, the exponent is wrong. About the alternative last column when keeping two figures, well, I am not completely sure about parentheses notation. I guess what I did is reasonable, but maybe I would prefer to write `0.08 \pm 0.10` just to be clear.

As side remark, I believe the implementation of such a rounding mode is much less trivial one might think. I implemented once this with a colleague in python and we also found corner cases over and over again. Actually it has not been easy at all to come up with a complete test suite for this (if at all we have one). And, actually, at some point we decided to completely change approach, from dealing with numbers to dealing with strings... :upside_down_face:  This just to thank you once again for your effort and give you lots of credit!

**Comment by josephwright** [comment]
I've been tracing through, and this comes about due to at least two factors. There is a bug in rounding the integer part of numbers. You can see it with
```latex
  \sisetup{round-mode = places, round-precision = -1}
  \num{7.724}
```
Then there's the face I haven't allowed for an exponent adjustment for the change-of-digit count in rounding here.

I'll fix the two parts and then we should be OK.
