### ISSUE TITLE
What caused this change of the uncertainty from what was expected? 

### ISSUE THREAD

**Issue by JHonal** [josephwright/siunitx#529]
`$L=\SI{1,0+-0,025}{mH}$` became
> L= (1,000±0,025) mH

while

`$L=\SI{1+-0,025}{mH}$` became
> L= (1,00±0,25) mH

What do I have to do to be able to believe that the system prints out what I want in such a case?

**Comment by josephwright** [comment]
This is working for me with v3.0.24.
