### ISSUE TITLE
Is there some way to type parenthesis () in \num?

### ISSUE THREAD

**Issue by syvshc** [josephwright/siunitx#531]
Here I have two demands about this question
1. when negetive number in `\numproduct`:
```latex
\documentclass{article}
\usepackage{siunitx}
\begin{document}
    \numproduct{-4d-2 x (-3)}
\end{document}
```
2. when I don't want to give the answer straightly:
```latex
\documentclass{article}
\usepackage{siunitx}
\begin{document}
    \num{(40-10)d-3}
\end{document}
```
They raise the same error:
```
./main.tex:4: Package siunitx Error: Invalid number `()'.

For immediate help type H <return>.
 ...

l.4     \num{(40-10)d-3}
```

**Comment by josephwright** [comment]
The first part can be handled by `input-ignore`, except it turned out there's a bug there: I'll fix shortly, and you'll be able to use
```latex
\documentclass{article}
\usepackage{siunitx}
\begin{document}
    \numproduct[input-ignore = (),input-open-uncertainty=,input-close-uncertainty=]
      {-4d-2 x (-3)}
\end{document}
```

**Comment by josephwright** [comment]
On the second part, `siunitx` does not attempt to parse full math mode expressions. Assuming you don't want to treat as an equation, set `parse-numbers = false`.

**Comment by syvshc** [comment]
> On the second part, `siunitx` does not attempt to parse full math mode expressions. Assuming you don't want to treat as an equation, set `parse-numbers = false`.

Sorry I didn't describe my demand clearly, the second part I wang to output 
![image](https://user-images.githubusercontent.com/38098591/129503914-0a952a37-29a2-4bc0-aac4-a98c40195262.png)
`parse-numbers = false` will give 
![image](https://user-images.githubusercontent.com/38098591/129504018-b6bea636-f5ea-4faf-aa6c-4f7c36cc5e25.png)
It's still not what I want.
