### ISSUE TITLE
Feature request: group separators a variable number of digits apart

### ISSUE THREAD

**Issue by fmitha** [josephwright/siunitx#533]
The `group-minimum-digits` option in `siunitx`, along with the `group-separator` option, does not seem to allow for the possibility that one may want to group a variable number of digits.

In India, it's common to express numbers between 10^5 and 10^6 with the following comma separation convention: `1,23,456`. This is because the `10^5` place is called a "lakh" in India, and it's a "distinguished" value, for lack of a better term.

Having such a separator currently does not appear possible with `siunitx`, because the grouping if fixed. If one is using `group-minimum-digits={3}`, one would see a comma after the `10^4` place, but not after the `10^5` place.

**Comment by Rmano** [comment]
https://en.m.wikipedia.org/wiki/Decimal_separator is a nice entry for this. Under "digit grouping" you can find the Indian style too (although it states that the SI way is separating groups of three digits with spaces)

**Comment by fmitha** [comment]
@Rmano I looked at that page. If one was adding a feature for variable group lengths, it would make sense to also add one for using multiple separators for one number. I.e. comma and period.

**Comment by josephwright** [comment]
I guess one aspect that worries me here is the didactic aspect: there is an aspect to `siunitx` which is about promoting international standard practice. I would really like examples of the use of this grouping _in scientific literature_. (I'm not questioning that it is used in day-to-day work, but I wonder if that carries through to formal publication.)

**Comment by josephwright** [comment]
The other thing is of course option naming. I could go with something like `grouping-mode` or `digit-group-mode`, but that means using a pre-defined list of outcomes: names for them? I'm not sure about an open-ended interface: something like `grouping-pattern`? That then needs a way to describe the grouping.

**Comment by fmitha** [comment]
I tried to find examples of this usage in (a) Indian publicly traded corporate account statements and yearly reports and (b) Indian socio-economic journals like Economic and Political Weekly, but was unable to. In all cases the figures are rounded off to the nearest large number, for some choice of large number. Crores or billions may be used, for example. And then the figures are presented in terms of that number. The outcome is that the numbers used typically do not cross the 10,000 mark, so such  issues do not arise.

This is probably a decision to avoid cluttering tables with very large numbers. Such numbers might be presented in individual income tax calculations. But those things are typically not public.

`integer-grouping` might work as a description. An ordered tuple would suffice. Like `(2,2,2,3)` for an example like `12,34,56,789`. If one needed to handle more integers, one would simply extend the tuple on the left. I do not know if such notation would work with your system.

**Comment by samcarter** [comment]
> I've been thinking about an interface. I wonder if we need to get as complicated as suggested, or if it could be `<m>:<n>` where `<m>` is the count of digits in the repeating grouping, and `<n>` is the count of digits in the final grouping. Or is that going to be too restrictive?
> 
> Whichever way it's done, I think what I'll do is set up a generic separator (slow) and special case the current case (`3:3` under my suggestion) and the requested one (`2:3`).

What about cases where the first group should be different and the following groups the same? This would be useful for e.g. phone numbers like `1234 56 78 90`

**Comment by josephwright** [comment]
@samcarter That's really out-of-scope

**Comment by krishnakumarg1984** [comment]
@josephwright This system of numbering absolutely carries through all the way to the government's official publication. For example, the biggest annual documents from the finance ministry viz the economic survey and the country's Annual budget!

I do believe that it promotes inclusivity if we support localisation (especially in deep-rooted cultural contexts). An example of TeX supporting such culture-specific localisation, is the North American `letter` size. This size does not conform to ISO paper standards, and yet, various fundamental classes and packages have no problems supporting it.

**Comment by josephwright** [comment]
@krishnakumarg1984  I've never said no to the request here: the fact that the use cases seem to be primarily financial has always been a bit of a concern, but I can live with that.

**Comment by krishnakumarg1984** [comment]
@josephwright What is the status of this?

**Comment by josephwright** [comment]
@krishnakumarg1984  As noted in the above comments, I implemented this for v3.1 using two options, `digit-group-first-size` and `digit-group-other-size`

**Comment by krishnakumarg1984** [comment]
@josephwright Thank you for implementing the feature, and for confirming this!
