### ISSUE TITLE
Missing "0" before C for \celsius inside Beamer document

### ISSUE THREAD

**Issue by rafaelpap** [josephwright/siunitx#536]
Version 3.0.26 does not print the "0" in front of the C for the \celsius command inside a Beamer document with sans-serif font.

```
\documentclass{beamer}
\usepackage[T1]{fontenc}      % european characters
\usepackage[utf8]{inputenc}
\usepackage{siunitx}
\begin{document}
\begin{frame}[shrink=5]
\begin{block}{Celsius not using =v2 with siunitx v3.0.26}
\begin{itemize}
\item Missing 0: $T=\SI{100}{\celsius}$ 
%\item Missing 0: $T=\qty{100}{\celsius}$ 
\end{itemize}
\end{block}
\end{frame}
\end{document}
```
[test_celsius.pdf](https://github.com/josephwright/siunitx/files/7033845/test_celsius.pdf)

Using [=v2] produces the right symbol.

**Comment by josephwright** [comment]
Working for me with the latest release (v3.0.27): could you test with that?

**Comment by rafaelpap** [comment]
Sorry about that. v3.0.27 works.

**Comment by josephwright** [comment]
@rafaelpap It's OK: just wanted to be sure I'd sorted it
