### ISSUE TITLE
Briefly document the localization possibility in the introduction

### ISSUE THREAD

**Issue by jlaurens** [josephwright/siunitx#543]
- localization is a key feature of siunitx
- the examples given in the doc are typeset with an EN locale, which may be misleading for people trying to reproduce them while using a different locale

**Comment by josephwright** [comment]
Do you mean in the 'for the impatient' part? If so, my concerns are

- That there's never a perfect balance to this section: different people feel different things are important
- That like it or not the language of scientific publication today is (US) English, and that means that localisation is always a bit risky

**Comment by josephwright** [comment]
Not just 'language', BTW, also 'idiom and typographic conventions'.
