### ISSUE TITLE
siunitx v3 and newtxtext and xelatex will output \micro incorrectly

### ISSUE THREAD

**Issue by syvshc** [josephwright/siunitx#547]
Here is MWE:
```
\documentclass{article}
\usepackage{siunitx}
\usepackage{newtxtext}
\begin{document}
    \unit{\micro\meter}
\end{document}
```
After compiling with xelatex, it will output `ţm`, but will ouput `μm` correctly with pdflatex. 

Also, if I use siunitx v2:
```
\documentclass{article}
\usepackage{siunitx}[=v2]
\usepackage{newtxtext}
\begin{document}
    \si{\micro\meter}
\end{document}
```
it will output both `μm` with xelatex or pdflatex.

**Comment by josephwright** [comment]
There seems to be a problem with `newtxtext` as 
```latex
\documentclass{article}
\usepackage{newtxtext}
\begin{document}
µ
\end{document}
```
fails with Unicode engines. I'm going to report that.

**Comment by josephwright** [comment]
Ah, I see: `newtxtext` forces T1 encoding (it's not Unicode-engine aware).

**Comment by syvshc** [comment]
> Ah, I see: `newtxtext` forces T1 encoding (it's not Unicode-engine aware).

Sorry, I don't know character encoding's  knowledge well... You mean that if I don't use `newtxtext`, when I use `pdflatex`, it will consider the character as T! encoding, and when I use `xelatex`, the character will be considered as Unicode encoding? However `newtxtext` forces T1 encoding even in `xelatex` mode?

**Comment by josephwright** [comment]
With pdfTeX, the 'out of the box' encoding is OT1, but almost always it's best to use T1 either explicitly or (as with `newtxtext`) as it's forced by a package. With XeTeX/LuaTeX, using T1 is problematic for a number of reasons and one should be using TU, which means an OpenType font. Personally, for something Times-like I would use
```latex
\usepacakge{fontspec}
\setmainfont{TeX Gyre Termes}
```
However, I can see that there is an issue for people updating here: basically I've taken a harder line on the font setup expectations. I'm working out whether this is a question of documentation or whether I can adjust the code subtly: I'll think about it a bit and also see what some people on the LaTeX team feel.

**Comment by syvshc** [comment]
I understand what you mean. Thanks for your reply :+1:

**Comment by josephwright** [comment]
I think this is covered by details in the docs now.
