### ISSUE TITLE
stix2 seems to confuse `\ang`

### ISSUE THREAD

**Issue by nxg** [josephwright/siunitx#550]
Consider the input file:

    \documentclass{article}
    \usepackage{stix2}
    
    \usepackage{siunitx}
    
    \begin{document}
    This is some text, with \ang{45} or $45^\circ$.
    \end{document}

When processed with `xelatex` or `lualatex` the `\ang{45}` produces ‘45ř’ (that is, not including a degrees sign of any type), though the `\circ` works as expected.

Interestingly, when I process this with `pdflatex` it does work as expected (I thought stix2 _required_ `xelatex` or `lualatex`, but perhaps I'm out of date there...)

Versions, all from TeXLive 2021 on macOS:

  * LaTeX2e <2021-06-01> patch level 1
  * L3 programming layer <2021-08-27>
  * stix2 2021/01/14 v2.0.2-latex
  * siunitx 2021-09-22 v3.0.31

**Comment by nxg** [comment]
I've just noticed that `\usepackage{siunitx}[=v2]` works as expected, so this appears to be a problem with the v3 changes.

**Comment by nxg** [comment]
...and I forgot to add the `\listfiles` output:

     article.cls    2021/02/12 v1.4n Standard LaTeX document class
      size10.clo    2021/02/12 v1.4n Standard LaTeX file (size option)
       stix2.sty    2021/01/14 v2.0.2-latex STIX Two fonts support package
    textcomp.sty    2020/02/02 v2.0n Standard LaTeX package
     siunitx.sty    2021-04-17 v2.8e A comprehensive (SI) units package
       expl3.sty    2021-08-27 L3 programming layer (loader) 
    l3backend-xetex.def    2021-08-04 L3 backend support: XeTeX
      xparse.sty    2021-08-27 L3 Experimental document command parser
     amstext.sty    2000/06/29 v2.01 AMS text
      amsgen.sty    1999/11/30 v2.0 generic functions
       array.sty    2021/04/20 v2.5e Tabular extension package (FMi)
    l3keys2e.sty    2021-08-27 LaTeX2e option processing using LaTeX3 keys
    translator.sty    2021-05-31 v1.12d Easy translation of strings in LaTeX
      keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
     t1stix2.fd    2018/04/02 v2.0.0-latex stix2 T1 font definitions
      ts1cmr.fd    2019/12/16 v2.5j Standard LaTeX font definitions
    ls1stix2.fd    2018/04/02 v2.0.0-latex stix2 LS1 font definitions
    ls2stix2.fd    2018/04/02 v2.0.0-latex stix2 LS2 font definitions
    siunitx-abbreviations.cfg    2021-04-17 v2.8e siunitx: Abbreviated units
    translator-basic-dictionary-English.dict    
    ls1stix2scr.fd    2018/04/02 v2.0.0-latex stix2 script LS1 font definitions
    ls2stix2ex.fd    2018/04/02 v2.0.0-latex stix2 extentions LS2 font definitions
    ls1stix2frak.fd    2018/04/02 v2.0.0-latex stix2 fraktur LS1 font definitions
    ls1stix2bb.fd    2018/04/02 v2.0.0-latex stix2 blackboard LS1 font definitions
    ls2stix2cal.fd    2018/04/02 v2.0.0-latex stix2 calligraphic LS2 font definitio
    ns
    ls1stix2sf.fd    2018/04/02 v2.0.0-latex stix2 sans-serif LS1 font definitions
    ls2stix2tt.fd    2018/04/02 v2.0.0-latex stix2 typewriter LS2 font definitions
    ts1stix2.fd    2018/04/02 v2.0.0-latex stix2 TS1 font definitions

**Comment by josephwright** [comment]
Related is https://github.com/josephwright/siunitx/issues/547.

**Comment by nxg** [comment]
Thanks for the explanation, and it does sound as if a hint on usage is a reasonable thing to do here.  However, it might be worth being a little more directive about what actions to take to fix this.

I've spent many years with LaTeX but I treasure my ignorance when it comes to the details of font encodings, crossing my fingers and hoping that package authors will field the curve-balls here, better than I can.  That means that I can look at commit c0147dd and broadly understand the issue, but still remain unclear what I should do, or even whether there's anything I _can_ do, to fix things in practical terms.  Thinking it through, it sounds like this is simply a `stix2` bug (I see it mentions support for only T1, OT1, OT2 and TS1), which I can do nothing about other than wait for an update.  Re-encoding the STIX2 fonts does not sound like a project for an amateur.

encguide.pdf Sect.5 (from `texdoc fontenc`) mentions the `TU` encoding, but says ‘[i]t is rare to need to specify the TU encoding a document as the fontspec package sets up the correct encoding when loaded.’  That seems to suggest that some magic with the fontspec package can fix things with respect to `stix2`'s interaction with `siunitx`.  I see that the `unicode-math` package mentions STIX (should I worry that it mentions STIX rather than STIX2?), but gives the impression that support for it is rather partial.  And... at this point I'm in grave danger of learning a non-trivial amount about TeX font encodings, and ending up in a rabbit-hole I can't get out of.

Naïve use of the `stix2` package's `[not1]` option does make my test file magically work, but I don't really follow _why_ the `stix2` package wants to change the input encoding (is it just so I can type an ⍺ and get an `\alpha`?), so I'm not sure what _else_ this is doing, which means that I don't know if this will quietly bite me later.

    \usepackage[not1]{stix2}
    \usepackage{siunitx}

Some don't-bother-your-pretty-little-head advice for the hard-of-thinking might therefore be not inappropriate in the `siunitx` docs.

**Comment by josephwright** [comment]
@nxg The problem is that each font package has it's own setup, so general advice is hard. As I've tried to indicate in the hint, you are best simply setting up the unit(s) with 'something that works' in the document you are working with.
