### ISSUE TITLE
\qtyrange with range-units=repeat and different prefixes

### ISSUE THREAD

**Issue by kjshen** [josephwright/siunitx#554]
Hello,

I used to be able to use
```
\SIrange[%
    exponent-to-prefix=true
    ,scientific-notation=engineering
    ,zero-decimal-to-integer=true
    ,range-units=repeat
]{100}{10000000}{\W}
```
and produce
![grafik](https://user-images.githubusercontent.com/45091615/138549941-c46d68f3-b6af-4235-bb4e-554ded650197.png)

However, I'm unable to reproduce this with the new options and commands. The following
```
\qty[exponent-mode=engineering,prefix-mode=combine-exponent]{100}{\W}

\qty[exponent-mode=engineering,prefix-mode=combine-exponent,drop-zero-decimal]{10000000}{\W}

\qtyrange[%
    range-units=repeat
    ,exponent-mode=engineering
    ,prefix-mode=combine-exponent
    ,drop-zero-decimal
]{1e2}{1e7}{\W}
```
results in
![grafik](https://user-images.githubusercontent.com/45091615/138550065-1150ee71-6c6a-4413-b009-8cc21cdc2095.png)

Is there anyway to reproduce this old behavior?

**Comment by s163555** [comment]
I also miss this feature. It used to be possible but at one point ceased to function.

**Comment by Rmano** [comment]
Ranges like 20 Hz ­— 20 kHz are really quite common, especially in electronics. So yes, at least the SI multipliers should be allowed to be different...

**Comment by josephwright** [comment]
> Ranges like 20 Hz ­— 20 kHz are really quite common, especially in electronics. So yes, at least the SI multipliers should be allowed to be different...

Now that suggests a potential name: `range-prefix-variation` as a boolean.

**Comment by josephwright** [comment]
(Could be `range-allow-prefix-variation` or `prefix-unit-prefix-variation`)

**Comment by Rmano** [comment]
`range-independent-prefix`?
