### ISSUE TITLE
Error with siunitx and sfrac as fraction-command

### ISSUE THREAD

**Issue by snobis** [josephwright/siunitx#558]
I like to combine `siunitx` with `xfrac` (see example below). This worked really well for years but yesterday (after a fresh update to my TeX Live 2021 installation) it stopped working.

Here's a short example:
```
\documentclass[border=2pt]{standalone}
\usepackage{xfrac}
\usepackage{siunitx}
\sisetup{%
  per-mode=fraction,%
  fraction-command=\sfrac%
}
\begin{document}
My unit: \unit{\m\per\s}.
\end{document}
```

This used to work (do not remember exactly when) but now I get an error:

```
./mwe.tex:9: Undefined control sequence.
<argument> ...sh_box -\box_dp:N \l__xfrac_slash_box -\height 
                                                  
l.9 My unit: \unit{\m\per\s}
                          .
```

If I omit the `\per` or comment out the `fraction-command` line, everything works.
Therefore it seems that the current definition of `\sfrac` is not compatible with how `siunitx` wants to use the command (I assume).

Any ideas on how to get `\sfrac` working nice with `siunitx` again?

Many thanks in advance!

**Comment by snobis** [comment]
An additional data point: I found a TeXLive 2021 installation of a friend on which the above example works. That installation has `siunitx` version 3.0.27 (date: 2021-08-22). My version that produces the error message is version 3.0.35 (date: 2021-11-03). Hope this helps.

**Comment by josephwright** [comment]
I see where the issue is (it relates to `\text` and search-and-replace inside braces): I'm puzzling out the best fix.

**Comment by damoclessb** [comment]
Hey, 

this issue still exists for me. Recently, I needed to update MikTex. Now, with everything updated, ``\sfrac`` does not work together with ``siunitx`` package.

When I try to compile
``$m_{a} = \SIrange[parse-numbers=false]{0.5}{\frac{2}{\sqrt{3}}}{}$``

I receive the following error message
```
Undefined control sequence.
<argument> ...x_dp:N \l__xfrac_slash_box -\height 
```

Can somebody help me how I can compile that correctly?

Regards, 
Stefan

**Comment by josephwright** [comment]
@damoclessb Without an example I'm afraid I can't say much: you don't have `\sfrac` in your code line, which has number-parsing turned off anyway.

**Comment by josephwright** [comment]
@damoclessb I'm still looking for a way to support this without breaking other stuff (where handling is improved): for the present using `\text{\ensuremath{\sfrac{...}{...}}}` (where `...` is your content) will work

**Comment by damoclessb** [comment]
@josephwright thank you very much, I was not aware that I need ``\ensuremath`` in addition to ``\text``.
