### ISSUE TITLE
[v3] Use of combined \decibel units leads to latex error

### ISSUE THREAD

**Issue by MisterFiLou** [josephwright/siunitx#561]
`\decibel` unit is often used in electronics combined with a reference unit.
E.g. dBW is a value referenced to 1W
In v2 it worked fine declare following units:
```latex
\DeclareSIUnit\dbm{\decibel \milli W}
\DeclareSIUnit\dbw{\decibel W}
```
or even: 
```latex
\DeclareSIUnit\dbw{\decibel \watt}
```
but this gives some space between dB and W, which is not really correct.

This does not work anymore in v3.
However following still works:
```
\DeclareSIUnit\dbuv{\decibel\micro\volt}
```
Thanks for considering this.

**Comment by josephwright** [comment]
v2 was a bit looser about 'mixed' cases with symbolic and literal units. For v3, things are more separate for internal reason: either all-symbolic or not. Here, you are not really adding a unit, rather a qualifier, so you'll need to set that up with `\DeclareSIQualifier`.

**Comment by MisterFiLou** [comment]
Thanks. 
Following works

```
\DeclareSIQualifier\milliwattref{m}
\DeclareSIQualifier\wattref{W}
\DeclareSIUnit\dbm{\decibel\milliwattref}
\DeclareSIUnit\dbw{\decibel\wattref}
```

BTW, Great package. I love it.
