### ISSUE TITLE
Undefined control sequence. 

### ISSUE THREAD

**Issue by some0nenew** [josephwright/siunitx#562]
I don't know if i should call this a bug or a question but whatever i try i cant get the package to work correctly. 

I tried to get it to run in the smallest possible setup, all of the Examples are copied from the documentation.

```
\documentclass{article}

\usepackage{siunitx} 

\begin{document}
	\num{12345,67890} \\
	\num{.3e45} \\
	\complexnum{1+-2i} \\ %fails
	\ang{10} \\
	\unit{\henry\second} \\ %fails
	\qty{.23e7}{\candela} \\ %fails
\end{document}
```

but i get the following Error/Warning

> Undefined control sequence. \complexnum
> Undefined control sequence. \unit
> Undefined control sequence. \unit{\henry
> Undefined control sequence. \unit{\henry\second
> Undefined control sequence. \qty
> Undefined control sequence. \qty{.23e7}{\candela
> Underfull \hbox (badness 10000) in paragraph
> Underfull \hbox (badness 10000) in paragraph

And the following [Output](https://i.imgur.com/CCg0Q8l.png).

At first i got the Error "File `siunitx.sty' not found." but i could solve that by installing "texlive-science 2021.58667-1" from the Manjaro Package Manager. I use TexStudio 4.1.1-1 as editor. 

The only possible solution i could find would be [this](https://tex.stackexchange.com/questions/429746/package-siunitx-gives-undefined-control-sequence). But this is a 3y/o error and should be fixed by now?

Maybe I'm overlooking something obvious but i just don't know what else i could do anymore.

**Comment by josephwright** [comment]
You are using version 2 of `siunitx`, not version 3; you'll need to use the appropriate commands.
