### ISSUE TITLE
small caps for scientific units and prefixes

### ISSUE THREAD

**Issue by MisterFiLou** [josephwright/siunitx#563]
Double question on using small caps in text mode for scientific units named after individuals (e.g. J, W, A, ...) and prefixes
The style gyde of the Economist proposes this approach (https://cdn.static-economist.com/sites/default/files/store/Style_Guide_2015.pdf , page 9)

1. would it be possible to set this with siunitx?

2. How is your feeling about this approach?

**Comment by josephwright** [comment]
It's up to the style guide, but these are _not_ abbreviations: they are (mathematical) symbols, so I would not routinely do this. (As a chemist, `\textsc{m}` is a common unit, molar, which is not 'official).

In terms of 'How to', just `\DeclareSIUnit` with the right setup for example
```latex
\DeclareSIUnit\watt{\text{\textsc{w}}}
```
