### ISSUE TITLE
Undefined control sequence on Texpad

### ISSUE THREAD

**Issue by Liuxiaodong-ioe** [josephwright/siunitx#564]
When I use siunitx package in Texpad, it went wrong.
```
\documentclass{article}
\usepackage{siunitx}
\begin{document}
	This is a test file for siunitx on Texpad.
	
	The unit of weight is \unit{\kg};
	
	The unit of length is \unit{\m}.
\end{document}

```
It shows that undefined control sequence. But I have loaded the package. I don't know why.

**Comment by josephwright** [comment]
I suspect you are using v2 of `siunitx`: if that's the case, you want `\si`.

**Comment by Liuxiaodong-ioe** [comment]
Thank you! Problem solved.
By the way, I also want to know how to use version 3 compulsorily. I have tried `\usepackage{siunitx}[=v3]`; it didn't work.

**Comment by josephwright** [comment]
@Liuxiaodong-ioe You can't force the version _up_ if the code is not installed! I'd have to see details, but I think you _only_ have v2 available.

**Comment by Liuxiaodong-ioe** [comment]
I checked the version up, which is  2017/11/26 v2.7k. I use `tlmgr install siunitx` to install the package. Maybe Texpad uses their own package manager instead of my local Mactex. My latex project works well on Overleaf, so it should be the software issue. Thank you!

**Comment by josephwright** [comment]
Texpad uses I think a self-contained TeX system
