### ISSUE TITLE
Version 3: Ranges with empty entries not supported anymore

### ISSUE THREAD

**Issue by FriedrichFroebel** [josephwright/siunitx#566]
I just tried to upgrade from version 2 to version 3 and stumbled upon some issues with my old approach of formatting some ranges where one value is empty due to unsupported fractions.

Example: I have used expressions like

```latex
1 \nicefrac{1}{2}\,\numrange{}{2}
```

in the past as these fractions are not supported for the actual value. After updating to version 3, this approach will fail:

> Package siunitx Error: Invalid number ''.

I am aware that `\numrange[parse-numbers=false]{}{2}` works and that these empty arguments are not perfect, but for me it seems like it has been the best way to re-use the existing `range-phrase=--,range-units=single` definition.

Ideally there would be a way to enable the old parsing functionality in version 3 which seems to support empty arguments, elimating the need to turn the number parser off manually as some numbers might require actual parsing/reformatting.

**Comment by josephwright** [comment]
For v3, I've tried to tighten up the semantics of the document commands. Here, I could allow empty values _but_ I don't think it would do what you want. In the same way that `\qty{}{\m}` is the same as `\unit{\m}`, something like `\numproduct{}{2}` would if it doesn't error yield the same as `\num{2}`, which I don't think would really help at all. The v2 code doesn't take quite as much care as it should have to avoid adding in extra material to the output: mea cupla.
