### ISSUE TITLE
Rounding adds trailing Zeros to uncertainty

### ISSUE THREAD

**Issue by Jackd4w** [josephwright/siunitx#568]
I have just noticed it with integers so far, the number of zeros appended seems to depend on the rounding  precission.

This should be a minimal working example:

```latex
\documentclass{report}
\usepackage{siunitx}
\sisetup{
    locale = US ,
    uncertainty-mode = separate,
    round-mode = uncertainty,
    round-precision = 2,
}

\begin{document}
\mbox{}\\\\
    Round-precision 2:\\\\
    9:\qty{1677(9)}{\joule}\\\\
    90:\qty{1677(90)}{\joule}\\\\
    900:\qty{1677(900)}{\joule}\\\\
    9000:\qty{1677(9000)}{\joule}\\\\
    \\\\
    Round-precision 3: \\\\
    9:\qty[round-precision = 3]{1677(9)}{\joule}\\\\
    90:\qty[round-precision = 3]{1677(90)}{\joule}\\\\
    900:\qty[round-precision = 3]{1677(900)}{\joule}\\\\
    9000:\qty[round-precision = 3]{1677(9000)}{\joule}\\\\
    \\\\
    Round-precision 4: \\\\
    9:\qty[round-precision = 4]{1677(9)}{\joule}\\\\
    90:\qty[round-precision = 4]{1677(90)}{\joule}\\\\
    900:\qty[round-precision = 4]{1677(900)}{\joule}\\\\
    9000:\qty[round-precision = 4]{1677(9000)}{\joule}\\\\
\end{document}
```

The code above produces the following output on my machine:

![image](https://user-images.githubusercontent.com/38991231/149223019-34d1bfcd-e2e2-4111-8287-dcca1dd0b228.png)

I hope this helps :) 
Also really nice package!

-Jackd4w

**Comment by josephwright** [comment]
Could you check your `siunitx` version: I get 'sensible' output with the latest release.

**Comment by Jackd4w** [comment]
I should be using siunitx 2022-01-05 v3.0.39

**Comment by josephwright** [comment]
OK, I'll look into this: I have a feeling I know where the issue might be.

**Comment by Jackd4w** [comment]
Very nice, thank you so much for your work on these LaTeX packages! :)
