### ISSUE TITLE
Wishlist: option to favor the unicode Ohm symbol over Omega with suitable engines

### ISSUE THREAD

**Issue by callegar** [josephwright/siunitx#569]
If I understand correctly, `siunitx` has recently removed the option to configure the math Ohm and text Ohm symbols and now uses the Greek letter Omega with `unicode-math` (codepoint 03A9). However, some fonts include a dedicated symbol for the Ohm (codepoint 2126) that can be slightly different from the regular Omega and that matches the *inverted Ohm symbol" (2127). Thus, I wonder if it could be sensible to maintain the possibility to fine tune the symbols used for the Ohm.

**Comment by josephwright** [comment]
The idea with the current code is that almost always it's best to re-declare units if you need to adjust how they act: the intermediate symbol code didn't really add clarity. I think it is worth bearing in mind that U+2126 normalises to U+03A9, so really they should be the same glyph. One could use for example
```
\documentclass{article}
\usepackage{siunitx}
\usepackage{fontspec}
\ExplSyntaxOn
\cs_gset:Npn \__siunitx_symbol_non_latin:nnnn #1#2#3#4
  {
    \__siunitx_symbol_deal_with_utf:
    \exp_after:wN \exp_after:wN \exp_after:wN
      \exp_not:N \char_generate:nn {#1} { 13 }
    \char_generate:nn {#2} { 12 }
    \tl_if_blank:nF {#3}
      { \char_generate:nn {#3} { 12 } }
  }
\siunitx_declare_unit:Nx \ohm
  {
    \__siunitx_symbol_non_latin:n { "2126 }
  }
\ExplSyntaxOff
\begin{document}
\qty{10}{\ohm}
\end{document}
```
to re-declare the symbol in a similar way to the `siunitx` internal definition. I will think about whether a change here makes sense: it's not immediately clear to me.

**Comment by Bosef1** [comment]
Understood that some font packages use slightly different glyphs for letters and mathematical symbols, such that letter Capital-Omega and Ohm-symbol are different, and Ohm-symbol and Inverted-Ohm-Symbol are rotations of each other.  Therefore concur with making the change to using U+2126 for Ohm and letting the normalization engines an font mappers sort it out.

For anyone else interested, the Unicode standard does indeed state that the Ohm-symbol U+2126 does normalize to the Capital-Omega U+03A9, and discourages the use of the Ohm-symbol.  When I am writing this comment, the most recent version of the Unicode standard is 14.0.0.  See Ch 7 at this link
https://www.unicode.org/versions/Unicode14.0.0/ch07.pdf

Pg 308, "Greek Letters as Symbols", for more information.  As noted in the same place, the Micro-symbol and the lowercase-mu letter maintain a distinction.

**Comment by callegar** [comment]
> Understood that some font packages use slightly different glyphs for letters and mathematical symbols, such that letter Capital-Omega and Ohm-symbol are different.

This is indeed the reason why, unaware of the standard prescriptions, I opened the original enhancement request.

Thanks for pointing to the standard.  Wonder what fonts that lack Greek altogether do. Using `albatross` on my system I see many more fonts providing the Ohm symbol than fonts providing the Greek Capital Omega.  The other way round, I also wonder if the normalization happens unconditionally, i.e. if all fonts that have the Greek Capital Omega do print the Ohm glyph.

The fact that there are more fonts providing the Ohm symbol than fonts providing the Greek Capital Omega suggests usage of the former. But if it is not the case that all fonts that have the Greek Capital Omega do print the Ohm glyph by practicing the normalization, then I suspect that users should get some indication on how to reconfigure the glyph to use in the documentation. In fact, the code snippet above for reconfiguring the \ohm unit seems a bit complex and hard to discover should one ever need it.
