### ISSUE TITLE
Link repository in the manual

### ISSUE THREAD

**Issue by wehro** [josephwright/siunitx#573]
The siunitx manual lacks a link to this repository, which however would be useful.

**Comment by josephwright** [comment]
There's a link in the Section 'Making suggestions and reporting bugs': `\href{https://github.com/josephwright/siunitx/}{GitHub}`. I guess you mean you'd like the link to be in the text itself rather than just hyperlinked from running text?

**Comment by daleif** [comment]
Personally I think it is always a good idea to write links like this out in full.

**Comment by josephwright** [comment]
I've adjusted the source for the next release.
