### ISSUE TITLE
Litres and liters in the manual

### ISSUE THREAD

**Issue by wehro** [josephwright/siunitx#574]
The litre part of table 5 seems to be a relic of version 2. The litre/liter spelling is now independent of the capitalization.

**Comment by josephwright** [comment]
The table shows both `\litre` and `\liter` with the symbol `L`: that as-intended. What would you expect to see?

**Comment by wehro** [comment]
The third column of that table is as expected, but the first and second are strange: `\l` is introduced as an abbreviation of *litre* and `\L` as an abbreviation of *liter*. In fact, both are abbreviations of both. The same for `\ul` and the like.

**Comment by josephwright** [comment]
I see what you mean, but I'm not at the moment minded to change.
