### ISSUE TITLE
LaTeX symbol for c_0

### ISSUE THREAD

**Issue by VintageRoses** [josephwright/siunitx#576]
There has been a [lengthy discussion on SE](https://tex.stackexchange.com/questions/630798/latex-symbol-for-c-0?noredirect=1#comment1573105_630798) that may be relevant for the siunitx package here on GitHub. 

The issue has to do with how to properly represent the _**speed of light**_ (typically represented by an italic 'c') _**in a vacuum**_ (which according to the accepted answer provided on SE) _could_ be represented by `c_{\scriptscriptstyle 0}`. 

The SE discussion includes a graphic from '[The International System of Units (SI)](https://www.bipm.org/documents/20126/41483022/si_brochure_8.pdf)'. The graphic shows how the SI portrays the '_**speed of light in a vacuum**_' symbol, but the OP is not convinced that the LaTeX solutions presented on SE, although **_very_** close to the symbol that appears in the graphic, are the most appropriate solution. 

Given the unique significance of the '_**speed of light in a vacuum**_' and how the meter itself is _defined_ relative to the '_**speed of light in a vacuum**_' as:

[The metre is the length of the path travelled by light in vacuum during a time interval of 1/299 792 458 of a second.](https://www.bipm.org/documents/20126/41483022/si_brochure_8.pdf)

Would it be appropriate for the siunitx package to include a proper LaTeX symbol to represent the '_**speed of light in a vacuum**_'? 

The image presented for what appears in the SI as a ‘reference rendering’ is:

![](https://i.stack.imgur.com/FnZXN.png)

 Thanks for reading.

**Comment by josephwright** [comment]
The symbols I include in `siunitx` are those needed for units. In the latest edition of the SI, the speed of light does not feature as a unit, and therefore this is out-of-scope.

At the same time, I think one should be wary of reading too much in to the typography of the SI Brochure. It's focussed on the metrology, and it's not typeset to a particularly high standard. For example, typographic tradition is that a value and unit are separated by a thin space: this reflects the fact this is one mathematical entity. However, the Brochure simply uses a full-width space. I suspect this reflects the tools used to create the Brochure. I would look at the IUPAC Gold book: https://goldbook.iupac.org/terms/view/S05854. There they use the same sized subscript as I'd expect: `c_{0}`.

**Comment by josephwright** [comment]
You might also look at the Green Book: same situation - https://iupac.org/what-we-do/books/greenbook/.

**Comment by VintageRoses** [comment]
Thank you for the updated reference links. Very informative.
