### ISSUE TITLE
itshape not shown in v3

### ISSUE THREAD

**Issue by javierbg** [josephwright/siunitx#579]
I was trying to add bold style to some cells and italics style to others (using `S` type columns). Bold works fine (making sure to add the usual, see example below), but italics are not shown: the numbers just appear upright. I tried the example from [this TeX Stack Exchange answer to a similar problem](https://tex.stackexchange.com/a/331241/262365), but the result is the same. I have modified the example to include both bold and italic cells.

```latex
\documentclass{article}
\usepackage{booktabs}
\usepackage{etoolbox}
\robustify\bfseries
\robustify\itshape

\usepackage{siunitx}
\begin{document}
	\begin{table}
		\centering
		\sisetup{detect-all = true}
		\begin{tabular}{@{}
				c
				c
				S[table-format = 2.0]
				S[table-format = 2.2]
				@{}}
			\toprule
			A & B & {C} & {D} \\ \midrule
			1 & 24 & 12 & 50.00 \\ 
			3 & 85 & \bfseries 45 & \bfseries 52.94 \\ \midrule
			\emph{Total} & \itshape 131 & \itshape 61 &  \itshape 46.57\\

			\bottomrule
		\end{tabular}
	\end{table}
\end{document}
```

In my installation I'm using siunitx v3.0.37 (`pdfTeX, Version 3.141592653-2.6-1.40.23 (TeX Live 2021/Arch Linux) (preloaded format=pdflatex 2022.1.7)`). Bold cells in `S` columns are formatted correctly but italic cells are not.

![example: italics cells not correctly formatted, but bold cells are](https://user-images.githubusercontent.com/9165467/151335392-04c748e2-07d5-4294-bba6-a8d0e92463ff.png)

If I change from `\usepackage{siunitx}` to `\usepackage{siunitx-v2}` then v2.8e is loaded and cells are formatted correctly.

![example: with siunitx-v2 all cells are formatted correctly](https://user-images.githubusercontent.com/9165467/151335599-2fffa3a3-7764-4df1-ae21-7bcfcbc7c5c8.png)

Maybe related to #306.

**Comment by josephwright** [comment]
I was just editing my answer there. If you want to load v2, you should use
```latex
\usepackage{siunitx}[v2]
```
rather than changing the name of the package itself.

That said, the emulation of `detect-all` looks like I'm missing `reset-text-shape = false`, which I'll address and fix in the next release.

**Comment by javierbg** [comment]
Tried using `\usepackage{siunitx}[v2]` instead of `\usepackage{siunitx-v2}` as suggested but v3.0.37 is loaded and the result is the same as before, no italics. Maybe you meant `\usepackage{siunitx}[=v2]`? That does work, I found it in the docs once I knew what to look for.

Thanks for the quick response!

**Comment by josephwright** [comment]
> Tried using `\usepackage{siunitx}[v2]` instead of `\usepackage{siunitx-v2}` as suggested but v3.0.37 is loaded and the result is the same as before, no italics. Maybe you meant `\usepackage{siunitx}[=v2]`? That does work, I found it in the docs once I knew what to look for.

Yes, sorry: it's a relatively recent addition to the LaTeX kernel, and I got the syntax a bit wrong :)
