### ISSUE TITLE
Invalid number error when using greek letters

### ISSUE THREAD

**Issue by guger** [josephwright/siunitx#581]
I'm recently getting an error for using `\SI{2\pi/4000}{\radian}` in my `report` document, but it worked with previous versions of the package.

I've to add the `parse-numbers=false` argument. Is this intentional, since I cannot find any hint for this in the changelog?

**Comment by josephwright** [comment]
Yes, this is by-design: if you want to treat `\pi` as a digit, you have to register it as such. The option for `input-quotient` was also removed as it did not really work in terms of parsed values.

**Comment by guger** [comment]
Okay thank you!
So if I want to use the divider "/" as shown above, even if I register `\pi` as a number, I'll have to use the `parse-number=false` option?

**Comment by josephwright** [comment]
Yes that is correct

**Comment by guger** [comment]
Okay, thank you!
