### ISSUE TITLE
Spacing of \pm and \times is 'tight' in text mode

### ISSUE THREAD

**Issue by josephwright** [josephwright/siunitx#583]
As reported in https://tex.stackexchange.com/questions/632298/how-to-change-the-spacing-around-the-plus-or-minus-symbol-in-siunitx
```latex
\documentclass{article}
\usepackage{siunitx}
\sisetup{mode = match, separate-uncertainty = true}

\begin{document}
\qty{18.0+-0.2}{\kilo\gram} 

(18.0\:±\:0.2)%The spacing I would like to have around ±

$\qty{18.0+-0.2}{\kilo\gram}$%To compare with the math mode
\end{document}
```

**Comment by Rickythomas2008** [comment]
Hi Joseph,
The issue with spacing still persists when using calling the package on Overleaf.
![image](https://user-images.githubusercontent.com/50899848/179169503-d2f638a6-08d0-405e-8069-d7a247ef9587.png)
May this be related to a TexLive version issue (the current version on Overleaf is 2021)?

**Comment by josephwright** [comment]
Overleaf used a fixed TeX Live image and so do not get updates during the year. You'll need to upload a copy of the latest `siunitx.sty` as part of your project, or simply wait for Overleaf to update.
