### ISSUE TITLE
\SIrange or \SIlist causes an error with newest update

### ISSUE THREAD

**Issue by juuf** [josephwright/siunitx#585]
Siunitx was updated on the current tex live distribution, causing all my files to throw some errors when using `\SIrange` or `\SIlist`. Here is the ouput:

`Argument of \__siunitx_print_text_replace_first:N has an extra }. ... \SIrange{10}{30}{\hertz}`
`Argument of \__siunitx_print_text_replace_first:N has an extra }. ... \SIlist{10;20;30}{\hertz}`

Do you know what the cause of this error is?

**Comment by josephwright** [comment]
I will need to see a full example: the basic
```latex
\documentclass{article}
\usepackage{siunitx}
\begin{document}
\SIlist{10;20;30}{\hertz}
\end{document}
```
works fine for me.

**Comment by juuf** [comment]
Okay, compiling that throws the said error.

``` latex
\documentclass[11pt,a4paper]{scrartcl}
\usepackage[locale = US,separate-uncertainty = true,multi-part-units=single,range-units=single,list-units=single,detect-all]{siunitx} 
\sisetup{output-exponent-marker=\ensuremath{\mathrm{e}}, list-final-separator = {, and }}
\begin{document}
\SIrange{10}{30}{\hertz}
\end{document}
```
Is it the same for you?

**Comment by josephwright** [comment]
Minimising I have
```latex
\documentclass{article}
\usepackage{siunitx}
\sisetup{range-units = single, mode = text}
\begin{document}
\qtyrange{10}{30}{\hertz}
\end{document}
```
I'll look at it.
