### ISSUE TITLE
Please support the LaTeX style math mode delimiters `\(...\)`

### ISSUE THREAD

**Issue by eike-fokken** [josephwright/siunitx#586]
Hi!
Thanks for this great package!

I noticed that inside S columns of tabular environments I must use `$ ... $` instead of `\( ...\)`.

I'm not sure, whether thats much work, but I would like to be able to use the later ones.

**Comment by josephwright** [comment]
I am not sure what you mean - inside an `S` column there shouldn't be any math mode shift tokens. Note that `$ ... $` is 'LaTeX style' - these are documented in Lamport's book.

**Comment by eike-fokken** [comment]
Yeah, I just realized that I'm not supposed to put `S` columns in math mode. Sorry to have bothered you.
