### ISSUE TITLE
remove leading zero before decimal

### ISSUE THREAD

**Issue by ma-ji** [josephwright/siunitx#587]
Hi, I understand that this is not recommended in the new version, but can I still do that? I've tried this setup but doesn't work: `\sisetup{round-mode=figures,round-precision=2,add-integer-zero=false,table-format = -2.2}`

**Comment by josephwright** [comment]
This came up in https://chat.stackexchange.com/transcript/message/60390465#60390465 (and the following messages): I'd suggested I could add `print-zero-integer` as a replacement for the old `add-integer-zero=false` - would that work for you?

**Comment by ma-ji** [comment]
Unfortunately it does not work, showing `The key 'siunitx/print-zero-integer' is unknown and is being [...res,round-precision=2,table-format = -2.2}]`. (siunitx version 3.0.48)

Thank you very much for your prompt response!

**Comment by josephwright** [comment]
@ma-ji  I meant _would that work_ as in the option doesn't exist at the moment, I wonder about conceptually.

**Comment by ma-ji** [comment]
> @ma-ji I meant _would that work_ as in the option doesn't exist at the moment, I wonder about conceptually.

Absolutely yes!!! Sorry for the misunderstanding. 

I guess many people will welcome this addition. For my case, my regression coefficients are all below 1, it is not necessary to print out all zeros in the table, and this has been a convention for many social science journals.
