### ISSUE TITLE
\qty not recognizing any units

### ISSUE THREAD

**Issue by brandazzle** [josephwright/siunitx#588]
The `\qty` command is not recognizing any units. Compiling `$\qty{1}{\volt}$` fails with error "Undefined control sequence" pointing at the unit macro no matter what unit macro I use. I am using TeXShop v4.68 on Mac with up-to-date siunitx. This does not occur with `$\unit{\volt}$`.

**Comment by josephwright** [comment]
Without an example or log file, I can't be sure, but I suspect you have got v2 not v3 of `siunitx`, possibly with `units` loaded too.

**Comment by brandazzle** [comment]
I thought of that (and I had a bunch of other things to update) so I reinstalled TeX Live and updated all packages using the TeXLive Utility; however, I just checked the package and apparently it's still v2. How, then, do I install v3?

**Comment by josephwright** [comment]
@brandazzle Do you have a stray 'local' install? Can you show your `.log` for the simple example
```latex
\documentclass{article}
\usepackage{siunitx}
\begin{document}
Hello world
\end{document}
```

**Comment by brandazzle** [comment]
[test.log](https://github.com/josephwright/siunitx/files/8058960/test.log)
That's weird—TeXLive Utility points to the v2 docs in "more info," but the log file lists:
`Package: siunitx 2022-02-07 v3.0.48 A comprehensive (SI) units package`

**Comment by josephwright** [comment]
I'm going to need a full example and the matching log then.

**Comment by brandazzle** [comment]
I figured it out—`\qty` conflicts with the same command from package `physics`:
```
\documentclass{article}
\usepackage{physics,siunitx}

\begin{document}
$\qty{1}{\volt}$
\end{document}
```
[example.log](https://github.com/josephwright/siunitx/files/8085945/example.log)

**Comment by josephwright** [comment]
This is documented: as `physics` introduced `\qty` before `siunitx`, if `physics` is loaded, `siunitx` does not define it. I will be looking at this again for v3.1 but it is tricky.

**Comment by brandazzle** [comment]
Could you just change the command to `\qnt`? I can't find any other package that uses it.
