### ISSUE TITLE
error when using decimal exponents 

### ISSUE THREAD

**Issue by dinojr** [josephwright/siunitx#589]
I used to use decimal exponents in `\num`, mostly for the values of chemical constants. The recent versions of siunitx don't allow that anymore.

For instance 
```
\documentclass{article}
\usepackage{siunitx}
\begin{document}
\(\num{4.13e2.7}\)
\end{document}
```
throws the following error:

`Package siunitx Error: Invalid number '4.13e2.7'.`

If there isn't a reason to forbid decimal exponents, I think `\num` and `\SI` should allow it.

**Comment by josephwright** [comment]
The intention was always that exponents were meant to be integers: scientific notation. In particular, the internals need to be able to interconvert exponents and prefixes, and that means they have to be integers.

You can always use `parse-numbers = false` to put in arbitrary math mode material.
