### ISSUE TITLE
Behavior change on zero uncertainty.

### ISSUE THREAD

**Issue by Jorispilot** [josephwright/siunitx#591]
I noticed a change in the output between v2 and v3 when printing uncertainties in tables. In v2, an uncertainty of zero remain displayed: “1.1(0)”, but in v3 it does not appear anymore: “1.1”. Nothing changes when the uncertainty is not zero.

While the output is not wrong (an uncertainty of zero meaning all digits are exact), It would be nice to still be able to show it, with a switch option for instance.

Here is an example to reproduce the behavior:
* Zero uncertainty is printed in this case:
  ```latex
  \documentclass{standalone}
  \usepackage{siunitx}[=v2]
  \begin{document}
      \sisetup{table-format=1.1(1)}
      \begin{tabular}{S}
          3.2(0) \\
      \end{tabular}
  \end{document}
  ```
* Zero uncertainty is _not_ printed in this case:
  ```latex
  \documentclass{standalone}
  \usepackage{siunitx}
  \begin{document}
      \sisetup{table-format=1.1(1)}
      \begin{tabular}{S}
          3.2(0) \\
      \end{tabular}
  \end{document}
  ```

**Comment by josephwright** [comment]
In genreal, a zero-value uncertainty suggests that this is auto-generated value to be dropped. In v3, you can indicate it should be kept with `retain-zero-uncertainty`:
```latex
  \documentclass{standalone}
  \usepackage{siunitx}%[=v2]
  \sisetup{retain-zero-uncertainty}
  \begin{document}
      \sisetup{table-format=1.1(1)}
      \begin{tabular}{S}
          3.2(0) \\
      \end{tabular}
  \end{document}
```

**Comment by Jorispilot** [comment]
I didn't noticed this option… Now it works like I want in v3. Thank you.
