### ISSUE TITLE
Incoherent uncertainty error

### ISSUE THREAD

**Issue by FOCCOF** [josephwright/siunitx#592]
Compare
\num {41.23 (19965)}

with
\num {41.23 \pm 199.65}% => ERROR

why an error in the second case ?
why not an error in the first case ( uncertainty > value ) ?

%----------------------------------
\documentclass{article}
\usepackage {siunitx}
\begin{document}
\sisetup {group-digits
    ,uncertainty-mode=separate
    ,round-mode=places,round-precision=2
    ,exponent-mode=input}
\num {41.23 (19965)}% --> no error
\num {41.23 \pm 199.65}% --> ERROR OF THE PACKAGE
\end{document}
%---------------------------------

**Comment by josephwright** [comment]
With v3 both work, which is by design - it's almost impossible to guess what authors might mean here.

**Comment by josephwright** [comment]
Actually, I checked and these are parsed the same by v2 and v3: can you add your log showing an error?
