### ISSUE TITLE
Auto SI unit prefix

### ISSUE THREAD

**Issue by AndreaDiPietro92** [josephwright/siunitx#593]
Would be nice to be able to change automatically a number with the correct SI prefix.
Example:
```
\num{4e6} -> 4M
\qty{4E6}{\ohm} -> 4MΩ
```

Here there is something similar: https://tex.stackexchange.com/questions/497228/automatically-convert-a-number-to-use-the-correct-si-unit-prefix

**Comment by josephwright** [comment]
The unit case is covered by `prefix-mode = combine-exponent`.

**Comment by AndreaDiPietro92** [comment]
Thank you.
