### ISSUE TITLE
minus superscript issues in text mode with lualatex

### ISSUE THREAD

**Issue by Schimmelpilz** [josephwright/siunitx#595]
Hi there. Just found an issue with exponent superscript minusses in textmode when I compile LuaLaTeX.
Best,
SchiPi

```
\documentclass[]{scrreprt}

\usepackage{amsmath, amstext, amssymb}
\usepackage[no-math]{newpxtext}

\usepackage{siunitx} 
\sisetup{separate-uncertainty=true, detect-all}

\begin{document}
	foo!\\
	\SI{1(1)E-12}{\milli\watt\per\centi\meter\squared} \\
	$\SI{1(1)E-12}{\milli\watt\per\centi\meter\squared}$\\
	Uhaaa!
\end{document}
```

**Comment by josephwright** [comment]
Not my fault! If you trace through, in text mode `siunitx` is aiming to produce
```latex
\textsuperscript{\textminus <number>}
```
here, which usually works fine. However, `newpxtext` redefines `\textsuperscript` to attempt to use 'real' superscripts, but that doesn't work with `\textminus`.

**Comment by josephwright** [comment]
Hmm, I guess I could check for the existence of `\fakesuperscipt`/`\textsuperscript*`. Pondering a bit.

**Comment by josephwright** [comment]
This is essentially an enhancement: I'll target for v3.1
