### ISSUE TITLE
Unit abbreviation for Henry and Watt

### ISSUE THREAD

**Issue by Korstek** [josephwright/siunitx#596]
Similar to Coulomb 
There already are abbreviations for Henry, but only `\mH` and `\uH`. Currently, I'm working on a high current buck converter and I need to use nanohenry so `\nH` will be really useful.  I would also advise adding `\fH` and `\pH` (for high-frequency IC folks) although with the second one there can be some problems?
Maybe also abbreviations for watts? Down to nanowatts.
PS: I found out about this tool today AND I LOVE IT!

**Comment by josephwright** [comment]
`\H`, `\mH` and `\uH` were already present: I've added a few new ones for v3.1
