### ISSUE TITLE
Allow `×` as separator token for `\numproduct` and `\qtyproduct`

### ISSUE THREAD

**Issue by dbitouze** [josephwright/siunitx#603]
It would be nice to allow, not only `x`, but also `×`  (`U+00D7`) as separator token for `\numproduct` and `\qtyproduct`.

**Comment by josephwright** [comment]
It's doable, but I wonder about the likelihood of anyone using this as input: it's not exactly easy to type.

**Comment by dbitouze** [comment]
On my keyboard, with GNU/Linux as OS, it is reasonably easy to type: <kbd>AltGr</kbd>+<kbd>Shift</kbd>+<kbd>.</kbd>. And I asked because, people getting more and more accustomed to Unicode, they may find `×` more natural, or more close to the reality, than `x` . In addition, a tutorial about `siunitx` using a sans serif typewriter font could let the user think the symbol to use is `×`:

```latex
\documentclass{article}
\usepackage{inconsolata}
\begin{document}
\verb|\qtyproduct{10x30x45}{\metre}|
\end{document}
```
![image](https://user-images.githubusercontent.com/1032633/172066280-209c3a63-c913-4981-83a2-a5d4841a1810.png)


BTW, another quite natural input, and maybe more natural than `x`, could be `*`.

**Comment by boergens** [comment]
I think both would be helpful (× and *) when one converts existing text to use \qtyproduct

**Comment by josephwright** [comment]
I've put this down for v3.2: it's relatively easy to set up.

**Comment by josephwright** [comment]
Sorted in 1c5d746063df105f8e51e313fd2faf30e02af343
