### ISSUE TITLE
Microarcseconds written as μ" instead of μas

### ISSUE THREAD

**Issue by helasraizam** [josephwright/siunitx#605]
\qty{2.5}{\micro\arcsecond} outputs 2.5 μ" instead of μas.  I believe μas is the standard, but I haven't found the source for SI standards to check.

**Comment by josephwright** [comment]
You can always redefine `\arcsecond` - I'm not sure what exactly you are after here?

**Comment by septatrix** [comment]
> I'm not sure what exactly you are after here?

The expected default is to conform to the symbols used by SI

**Comment by josephwright** [comment]
The official symbol (https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf) is `"`, while using `as` is described in a footnote. The problem for me is that I can't know if a user is going to want `\micro\arcsecond` when they use `\arcsecond`, and I don't want to encourage using two different notations for the same unit in the same document. So the user needs to make the call: if they want `\arcsecond` as `as`, they need to set that up in the preamble.

**Comment by septatrix** [comment]
Hm yeah the only solution I can think of though I agree that it is not the prettiest would be to have alternative notations like `\microarcseconds` or `\micro\arcsecond vs \acrsecond*`.  There is functionality in expl3 for peeking at the next character though I have no clue if that with commands (apart from problems like mixed dimension where they do not directly follow each other)
