### ISSUE TITLE
round-precision and round-pad ignored when uncertainty is present

### ISSUE THREAD

**Issue by MaartenBransen** [josephwright/siunitx#606]
When parsing values with uncertainties, the round-mode and in particular round-pad seems to be ignored:

```
\documentclass{article}
\usepackage[separate-uncertainty=true,round-precision=5]{siunitx}
\begin{document}
\noindent%
\sisetup{round-mode=figures}
\num{104}\\
\num{104(1.1)}\\
\num{104(11)}\\\\
\sisetup{round-mode=uncertainty}
\num{104}\\
\num{104(1.1)}\\
\num{104(11)}\\\\
\sisetup{round-mode=none,round-pad=false}
\num{104}\\
\num{104(1.1)}\\
\num{104(11)}\\
\end{document}
```
![Untitled](https://user-images.githubusercontent.com/54527765/173559260-61ba439b-3c5f-4b98-927c-016d6f9a0c3d.png)

I would expect `\num[round-pad=false]{104(1.1)}` to give 104±1.1, instead a trailing 0 is added. Perhaps I am misunderstanding how uncertainties are (supposed to be) handled?

**Comment by josephwright** [comment]
```latex
\sisetup{round-mode = uncertainty, round-precision = 1}
```
