### ISSUE TITLE
siunitx conflicts with LaTeX2e <2022-06-01> patch level 1 (r63613)

### ISSUE THREAD

**Issue by akiyks** [josephwright/siunitx#607]
I'm seeing a new warning from LaTeX after updating tex-live.

MWE:
```
\documentclass[10pt,twocolumn,letterpaper]{article}
\usepackage{siunitx}

\begin{document}

\section{Hello}

Hello world!

\end{document}
```

New warning in .log:
```
LaTeX Warning: Unused global option(s):
    [10pt,twocolumn,letterpaper].
```

The warning can be silenced either by restoring previous latex (`tlmgr restore latex 63514`), or
by commenting out `\usepackage{siunitx}` with the latest latex (r63613).

I have no idea what is happening.
Can you please look into this?
I'll ignore the harmless warning for the moment.

Thanks!

**Comment by terhorstj** [comment]
I don't know if it helps but I can confirm this with MWE:

```
\documentclass[10pt]{article}
\usepackage{siunitx}
\begin{document}
test
\end{document}
```

Generates:

```
LaTeX Warning: Unused global option(s):
    [10pt].
```

**Comment by akiyks** [comment]
There is an issue reported and resolved at https://github.com/latex3/latex2e/issues/864.
So this is not an issue in siunitx.

Sorry for the noise.

Closing now.
