### ISSUE TITLE
Missing unit: U (literally "unit", used for enzymes, for example)

### ISSUE THREAD

**Issue by firinael** [josephwright/siunitx#610]
Pretty self-explanatory. There's no `\U` or `\u` or anything like that. It's pretty commonly used when dealing with enzymes, often you'll see "U/µL" or something like that.

Thank you for your work!

**Comment by josephwright** [comment]
I'm aware that activity is widely used, but it's not an SI unit (not in the BIPM Brochure), so it's not in the pre-defined set.

**Comment by firinael** [comment]
Fair enough! If you could add it anyways despite it not being standard, it'd be greatly appreciated. If not, that's okay too. 

Thanks!

**Comment by josephwright** [comment]
As a matter of policy, I don't add non-standard units - there's no way otherwise to make a call on what 'counts'.
