### ISSUE TITLE
`\microlitre` and `\microliter` both don't print anything

### ISSUE THREAD

**Issue by firinael** [josephwright/siunitx#611]
As the title states, both the `\microlitre` and `\microliter` commands don't print anything into the document, coming up as just blank. Using `\micro \liter` or `\micro \litre` does work, though.

**Comment by josephwright** [comment]
Neither `\microlitre` nor `\microliter` are pre-defined units, so you should be getting an error here.

**Comment by firinael** [comment]
The package manual states that it does load these abbreviated units, though, as per section `3.6`, page 12. I made sure to check there before posting!

**Comment by firinael** [comment]
Wait, I'm a dummy. The manual states that `mL` is specifically loaded as `\ml` and nothing else. My bad!
