### ISSUE TITLE
feature request: instead of s^{-3} allow s_3

### ISSUE THREAD

**Issue by PurdueThesis** [josephwright/siunitx#612]
I can type `\unit{\kg\meter\squared\per\second\cubed}`
or `\unit{kg.m^2.s^{-3))` to get the same output.

 I'd like to type `\unit{kg.m^2.s_3}` to get the same output
or (if you want to keep _ for subscripts) type
`\unit{kg.m^2.s!3}` to get same output.

**Comment by josephwright** [comment]
This is basically https://github.com/josephwright/siunitx/issues/496: parsing free-form rather than macro-based units. It's on the to-do list, probably late 2022.
