### ISSUE TITLE
The units package and siunitx are incompatible.

### ISSUE THREAD

**Issue by stegzzz** [josephwright/siunitx#613]
I have units 0.9b and siunitx 3.1.4 in a windows Miktex 22.3 installation and whenever I compile my tex file with pdflatex I get the error above if the two packages are used. I don't think I need both but...

**Comment by josephwright** [comment]
Er, yes, as they both define the same document command. You'll need to choose one.

**Comment by stegzzz** [comment]
Thanks for the reply. The error message could say -- incompatible, choose
one or the other

:-)

BW, Steve
