### ISSUE TITLE
Quantities as adjectives

### ISSUE THREAD

**Issue by hpretl** [josephwright/siunitx#614]
In IEEE papers, it is good practice to write quantities as adjectives, like “28-nm CMOS process” or “a 10-mA current loop”. To do this easily, the following macro `\qtya` would be a useful component of `siunitx`:

```
\newcommand{\qtya}[2]{\qty[quantity-product = - ]{#1}{#2}}
```

**Comment by josephwright** [comment]
I'm not sure what the issue here is _per se_, but this is _not_ best practice. BIPM are clear that unit symbols are not abbreviations: as such 'normal' rules do not apply, and quantities should never be formatted differently when they are grammatically abbreviations.

**Comment by josephwright** [comment]
Specifically, from the [SI Brochure](https://www.bipm.org/en/publications/si-brochure):
> Even when the value of a quantity is used as an adjective, a space is left between the
numerical value and the unit symbol. Only when the name of the unit is spelled out would
the ordinary rules of grammar apply, so that in English a hyphen would be used to separate
the number from the unit.

**Comment by hpretl** [comment]
Yes, but IEEE Std 260.1-2004 ("IEEE Standard Letter Symbols for Units of Measurement") spells out in sec. 4.4:

> In the complete expression for a quantity, a space should be left between the numerical value and the unit symbol. For example, write 35 mm, not 35mm, and 2.371 m, not 2.371m. When the quantity is used in an adjectival sense, a hyphen is often used in lieu of a space between the number and the unit name or between the number and the symbol.
> — Example: A 3-meter pole. The length is 3 meters.
> — Example: A 35-mm film. The width is 35 mm.

And this is quite custom in IEEE papers.

**Comment by josephwright** [comment]
> Yes, but IEEE Std 260.1-2004 ("IEEE Standard Letter Symbols for Units of Measurement") spells out in sec. 4.4:
> 
> > In the complete expression for a quantity, a space should be left between the numerical value and the unit symbol. For example, write 35 mm, not 35mm, and 2.371 m, not 2.371m. When the quantity is used in an adjectival sense, a hyphen is often used in lieu of a space between the number and the unit name or between the number and the symbol.
> > — Example: A 3-meter pole. The length is 3 meters.
> > — Example: A 35-mm film. The width is 35 mm.
> 
> And this is quite custom in IEEE papers.

I may raise this with the  IEEE office, but I am still not sure what the issue is: the author can always uses (as you do) `\qty[quantity-product = - ]{<num>}{<unit>}`.

**Comment by hpretl** [comment]
There is no issue as everyone can define the command as stated above, but I just thought it could be handy for others as well if it is directly available.

I'll close the issue, will go with `\qty[quantity-product = - ]{<num>}{<unit>}` then.
