### ISSUE TITLE
How to fix weirdly-rendered mu (for \micro) now that math-micro and text-micro parameters to \sisetup have been removed?

### ISSUE THREAD

**Issue by maspotts** [josephwright/siunitx#619]
I've had to switch from XeLaTeX to LuaLaTeX (in overleaf, to avoid an out of memory condition), and now all my units containing `\micro` are rendering with a strange symbol (looks like a t with a cedilla) instead of the micro symbol (mu).  I googled and found lots of people reporting that adding: `\sisetup{math-micro=\text{µ},text-micro=µ}` (to supply an explicit mu character) would solve this, but both `math-micro` and `text-micro` have been removed (as of version [v3.0.0](https://github.com/josephwright/siunitx/compare/v2.8e...v3.0.0) of siunitx).  So my question is: what's the recommended way to fix `\micro` in the absence of those parameters?  Thanks!

**Comment by maspotts** [comment]
<img width="35" alt="Screen Shot 2022-08-20 at 2 01 46 PM" src="https://user-images.githubusercontent.com/4096446/185765893-5e3d9f7f-8226-41bf-be6c-34fecb6258a0.png">

**Comment by maspotts** [comment]
Note: I found this workaround: `\DeclareSIPrefix\micro{\text{\textmu}}{-3}` which works, but produces a mu which is in a noticeably different font, compared to the one I was getting with XeLaTeX, so I'm still hoping there's a better solution which will give me back a more consistent-looking mu symbol...

**Comment by josephwright** [comment]
Almost certainly you have the wrong font encoding selected: do you have for example `\usepackage[T1]{fontenc}` in your preamble?

**Comment by maspotts** [comment]
You are so right!  I must have inherited that `\usepackage[T1]{fontenc}` from a template: took it out: nothing broke, and my `\micro` symbols work again: thanks!!

**Comment by maspotts** [comment]
I may have spoken a little too soon: I've got `\micro` working again, but now I have a (non-siunitx) font-related issue due to the removal of `\usepackage[T1]{fontenc}`.  It seems that the T1 font encoding is generally recommended: is there no way to use it AND have `\micro` working?

**Comment by josephwright** [comment]
The `T1` encoding is inappropriate with Unicode engines: it _is_ recommended with 8-bit ones (pdfTeX). You can adjust the behaviour of `\micro` using `\DeclareSIUnit` to use a definition which provides an appropriate appearance. If you _must_ use `T1` you are likely best reverting to v2 of `siunitx` with
```latex
\usepackage{siunitx}[=v2]
```
but this freezes your version at the last one in the v2 series.

**Comment by maspotts** [comment]
Thanks: that's useful; I'd obviously much rather not freeze my version: please forgive my ignorance, but is there an obvious choice of font encoding I *should* be using? (Compatible with siunitx but also with \texttt, for example)?  Or are you recommending *not* to specify a font encoding at all?  (Don't use \usepackage{fontenc} at all?)

**Comment by josephwright** [comment]
With XeTeX or LuaTeX, you should not load `fontenc`, and with a reasonably up-to-date LaTeX will get a warning if you do. The standard encoding with those engines today is `TU`, which means 'Unicode' and assumes you are using system-like fonts (which can include Latin Modern). This is the right choice for these engines and works fine with all font commands. I can only imagine you have some older font loading setup which is causing issues: it will be incorrect for a Unicode engine.

**Comment by maspotts** [comment]
Thanks!
