### ISSUE TITLE
font weight is inconsistant

### ISSUE THREAD

**Issue by PaulMndn** [josephwright/siunitx#620]
If I understand correctly, it is purposfully done so that the units (and numbers) are not bold. However this does at least not apply to `µ` correctly.

### Input
`\textbf{\qty{20}{\ul}`

### expected
everything in normal weight, not bold.

### actual result
Only the micro symbol `µ` is bold. Everything else is the normal font weight.

**Comment by josephwright** [comment]
I will need an example showing your setup: for me
```latex
\documentclass{article}
\usepackage{siunitx}

\begin{document}

\textbf{\qty{20}{\ul}}

\end{document}
```
gives the expected output.
