### ISSUE TITLE
Scientific notation breaks when rounding up to next power of 10

### ISSUE THREAD

**Issue by neil-lindquist** [josephwright/siunitx#622]
Rounding seems to be applied after the exponent for scientific notation, so the number is incorrectly formatted when 9.xxx is rounded up.

```latex
\documentclass{minimal}
\usepackage{siunitx}
\begin{document}
\num[exponent-mode=scientific,round-mode=figures,round-precision=1]{9.99e5}
\end{document}
```
gives 10x10^5 not 1x10^6.

This occurs with MikTex 22.8.28 and the latest release of siunitx.

**Comment by josephwright** [comment]
Fixed by 1c0c63fc25513bdd3c422abc9681596225bdb956
