### ISSUE TITLE
Missing \mF

### ISSUE THREAD

**Issue by judober** [josephwright/siunitx#624]
Is there a reason that `\mF` is not an abbreviation for `\milli\farad`?

Thanks for this nice package!

**Comment by josephwright** [comment]
It's never been asked for: I suspect it's quite a large unit ...

**Comment by judober** [comment]
You are right uF is far mor common. However there are big capacitors, e.g. [this one](https://www.mouser.de/ProductDetail/KEMET/FR0H223ZF?qs=BenOyfdfArq0Z6pH0sKNnA%3D%3D).
So I would suggest to add this abbreviation .
