### ISSUE TITLE
Issue with \complexqty{}{}

### ISSUE THREAD

**Issue by jotagah** [josephwright/siunitx#625]
Greetings,

I am not sure I am doing something wrong here, but I am looking to write \complexqty{j1}{\ohm}, but I get only "j \ohm", not "j1 \ohm". I have to use $j\qty{1}{\ohm}$ ou "force" like \complexqty{j1.0}{\ohm} to get it, but I deslike "j1.0 \ohm". I am loosing something?

[ ]',

J.

**Comment by josephwright** [comment]
I think this is one I forgot how it worked in v2 when I wrote v3 :) I want to offer the possibly to make this behaviour controllable, but as this is technically a bug (as it is a non-deliberate change from v2), I will hotfix either today or tomorrow.

**Comment by josephwright** [comment]
I have added a control option here: I am not changing the v3 behaviour but this allows you do to do the same as v2.

**Comment by jotagah** [comment]
Thanks Indeed.
