### ISSUE TITLE
After updating to the most recent l3 packages, the siunitx stopped working

### ISSUE THREAD

**Issue by StoneboyCZ** [josephwright/siunitx#626]
Hi, 

after updating packages to the newest version yesterday, the siunitx stopped working with the following error (there are hundreds of them and it is independent of the content of the document itself):

! Missing number, treated as zero.
<to be read again> 
                   \protect 
l.6779 ... \__siunitx_unit_non_latin:n { "03BC } }

the line in siunitx.sty (the file packaged with MikTex) looks like

\siunitx_declare_prefix:Nnx \micro { -6 } { \__siunitx_unit_non_latin:n { "03BC } }

Further errors are on the lines 

\siunitx_declare_unit:Nx \degreeCelsius { \__siunitx_unit_non_latin:n { "00B0 } C }
\siunitx_declare_unit:Nx \ohm       { \__siunitx_unit_non_latin:n { "2126 } }
\siunitx_declare_unit:Nx \arcminute { \__siunitx_unit_non_latin:n { "02B9 } }

I´ve tried downgrading the siunitx package itself (I have a working install on other PC) and it didn´t work. So my guess is that the most recent l3packages have broken something. But I can´t directly test it, MikTex doesn´t support downgrading.

The complete log file and the version of the package is attached.

[projekt.log](https://github.com/josephwright/siunitx/files/9943449/projekt.log)
[siunitx.zip](https://github.com/josephwright/siunitx/files/9943450/siunitx.zip)

**Comment by josephwright** [comment]
I see quite a few packages being loaded and the use of a non-standard class (`fitthesis`). Could you minimise your input to trigger the error, and include the demo file here? With the standard 
```latex
\documentclass{article}
\usepackage{siunitx}
\begin{document}
\qty{10}{\micro\metre}
\end{document}
```
all is fine as far as I know.

**Comment by StoneboyCZ** [comment]
Hi, thank you SO much. The basic document works. The fitthesis is the custom class file I have to use, but it doesn´t use anything too crazy as far as I know. 

And it works perfectly fine here (without the update I mentioned) and on overleaf. 

Do you have any idea how to figure out where the problem might be?

**Comment by StoneboyCZ** [comment]
Hello again, I don´t know why it worked, but I managed to fix the problem by loading the package as the first one in the class file. The document now compiles everywhere.

**Comment by josephwright** [comment]
I'm pleased it's sorted, but without a clear example I can't say what is going on. So I'll close the issue.

**Comment by StoneboyCZ** [comment]
If you ever have a little time, the complete (non-working) example is attached. 
[template.zip](https://github.com/josephwright/siunitx/files/9945704/template.zip)
