### ISSUE TITLE
New SI prefixes added (27th meeting of the General Conference on Weights and Measures)

### ISSUE THREAD

**Issue by quark67** [josephwright/siunitx#629]
New prefixes are added to the Système International (resolution of the 27th meeting, 15-18 november 2022).

Source : https://www.bipm.org/documents/20126/77765681/Resolutions-2022.pdf/281f3160-fc56-3e63-dbf7-77b76500990f (see the page 22)

| Multiplying factor | Name | Symbol |
| ------ | -----| ----- |
| 10^27 | ronna | R |
| 10^{-27} | ronto | r |
| 10^30 | quetta | Q |
| 10^{-30} | quecto | q |

After updating the code, table 4 on page 9 of siunitx.pdf need also to be updated.

**Comment by josephwright** [comment]
> quetta
