### ISSUE TITLE
\unit[per-mode = symbol] outputs 1 numerator

### ISSUE THREAD

**Issue by Bosef1** [josephwright/siunitx#631]
When using the \unit command with per-mode=symbol , the unit is it output with a 1 numerator.  This was observed in siunitx version 3.1.10.  Is this the expected output?  I was expecting only the per-symbol "/" and the unit abbreviation.  If there is a style guide used for determining this output, if possible, would you please provide a reference?

Here is a code snippet, I have attached a small example file for reference.

```
\unit{\per\kg}   %% outputs "kg-1" as expected

\unit[per-mode = symbol]{\per\kg}  %% outputs "1/kg"; the 1 is unexpected, expected output was "/kg"
```

If this is expected behavior, no worries, I can work around it.  It was just unexpected to me.  Thank you for the help.

[unit-per.log](https://github.com/josephwright/siunitx/files/10095246/unit-per.log)
[unit-per.tex.txt](https://github.com/josephwright/siunitx/files/10095248/unit-per.tex.txt)

**Comment by josephwright** [comment]
The `/kg` form is a type of fraction, so we need a numerator. The code therefore adds the `1` by design here.

**Comment by Bosef1** [comment]
Understood.  I think I have a work-around.  I will close this ticket.  I just wanted to confirm.

**Comment by josephwright** [comment]
Could you show me your use case? I wonder if there's a feature here I'm missing.
