### ISSUE TITLE
Option "negative-color" does not color the unit

### ISSUE THREAD

**Issue by Vinpasso** [josephwright/siunitx#635]
Occurs on: siunitx 3.2.0

| Behavior |  |
| - | - |
| Expected: | When using `\qty[negative-color=red]{<negative number>}{\second}` the number and the unit should be colored if the value is negative. |
| Actual: | Only the number is colored if the value is negative, the prefix and the unit is in the default color. |

Example output:
![image](https://user-images.githubusercontent.com/9805224/212038081-ca1ed326-cda3-4fb1-ac19-bbb9d04d60d0.png)

Thank you for your work on this package and have a nice day

**Comment by Vinpasso** [comment]
PS: The problem becomes more obvious when trying to combine `negative-color` with the regular `color` option to format positive numbers, e.g. `\qty[negative-color=red, color=green]{<num>}{<unit>}`.

Example output:
![image](https://user-images.githubusercontent.com/9805224/212040694-1d2d1621-926c-4ea5-a081-3ecbd8bb36c9.png)

**Comment by josephwright** [comment]
Er, no, this is a feature of the value: units are still the same (they are not after all negative units!)

**Comment by Vinpasso** [comment]
Ok I see, it just looks a little off and I'm not sure there is an easy way to typeset that correctly. As a workaround: it is possible to combine `negative-color` with `number-color` and leave the unit color untouched:

![image](https://user-images.githubusercontent.com/9805224/212658234-65c0977f-2c92-4b88-a51c-063e3d33ad2a.png)

That may or may not be suitable depending on the use case.
