### ISSUE TITLE
per-mode=power not working

### ISSUE THREAD

**Issue by sprague252** [josephwright/siunitx#638]
When I enter a unit with the `per-mode=power` option set, the result is displayed with the `per-mode=symbol` setting. For example, I enter `\qty[per-mode=power]{1.25}{\kilo\gram.\meter\per\second\squared}` and get 1.25 kg m/s<sup>2</sup> instead of 1.25 kg m s<sup>-2</sup>. This happens whether I set `per-mode=power` explicitly or not (it is supposed to be the default). I am using siunitx version 3.1.11.

**Comment by sprague252** [comment]
I just upgraded to version 3.2.0, and I have the same issue.

**Comment by josephwright** [comment]
You have put a `.` in your units. This is 'literal' formatting, and means that `siunitx` does not attempt to interpret your units. Under those conditions, `\per` always gives `/`. If you remove the `.`, `siunitx` will be able to parse your input and you should get the output you expect.

**Comment by sprague252** [comment]
Thanks for the clarification. I appreciate your response.
