### ISSUE TITLE
Error if \sim or other comparators are used in text or match mode

### ISSUE THREAD

**Issue by msommer24** [josephwright/siunitx#640]
Hi, 
I get following error if I use specific comparatos in text or match mode: Missing $ inserted.

Example:
```
\documentclass{article}
\usepackage[english]{babel}
\usepackage{siunitx}
\sisetup{mode=match}

\begin{document}
% producing errors
\qty{\sim 0.1}{\meter}
\qty{\approx 0.1}{\meter}
\qty{\leq 0.1}{\meter}
\qty{\geq 0.1}{\meter}
% here no erros but wrong resulting signs
\qty{< 0.1}{\meter}  % >> ¡0.1 m
\qty{> 0.1}{\meter}  % >> ¿0.1 m
\end{document}
```

(using PdfLaTeX with siunitx 2022-06-07 v3.1.3, TeX live 2022 in Overleaf)

**Comment by josephwright** [comment]
> \qty{< 0.1}{\meter}  % >> ¡0.1 m
> \qty{> 0.1}{\meter}  % >> ¿0.1 m

These are to-be-expected as you are using `OT1` font encoding: I _really_ don't recommend that. 

I'll give a bit of thought to the other part of the issue: I probably need to add a few more things to the text mode setup.

**Comment by msommer24** [comment]
Very good point. Thanks for your reply, the 'font encoding' I had not in mind.
