### ISSUE TITLE
include detection of braces for proper sizing of them

### ISSUE THREAD

**Issue by SReich-EMI** [josephwright/siunitx#642]
Hi,
I'm surching for the proper brace deinition so that even with higher units, e.g. exponents, the braces are scaled to fit around the unit. Typical usage I see in tables and labels of figures. In pure math environment this can be done by e.g. \left[ and \right]. But all comibnations I tried did not give the result I expected. If I figured out right, I have the version {2022-10-23} {3.1.9}

My tests were:
`(1) [$W/m^2$], 
(2) $[W/m^2]$, 
(3) $\left[W/m^2\right]$,\\
(4) [\unit{W/m^2}],
(5) \unit{[W/m^2]}, \\
(6) $\left[\unit{W/m^2}\right]$,
(7) $\unit{\left[W/m^2\right]}$,
(8) \unit{$\left[W/m^2\right]$},
(9) \unit{\left[W/m^2\right]}`

 and gave these results:
![grafik](https://user-images.githubusercontent.com/60341278/220586061-408ac9eb-805b-4daf-86dc-852a519e3e21.png)

(1) to (3) are all simply math environment, where only (3) scales the braces correctly to the size of the internal text. But, this is in math environment, hence the font and so on do change. 
(4) and (5) both set the braces in the right font, however they are to small.
(6) to (9) scale the braces corretly, but again the fonts are wrong. Additionall I get errors for (6)+(7) that "Math version `light' is not defined." and (8) "Missing $ inserted." And (9) again looks like (2) and is without errors.

So my wish is to get an appearance like (4) or (5) but with the scaled braces of (6) to (9). A work arround would be suitable, but a perfect implementation would facilitate the usage of a much larger community. By syntax I wouldd recommand (5) oder (9). Keeping in mind the behaviour of math environment (9) would fit better. 

Does anyone see the possibility to implement this? I'm not at all familiar with programming LaTeX packages.

**Comment by josephwright** [comment]
One can always force bracket size:
```latex
\documentclass{article}
\usepackage{siunitx}
\sisetup{per-mode = symbol, text-family-to-math}
\begin{document}
\sffamily
$[\unit{\watt\per\square\metre}]$ or $\left[\unit{\watt\per\square\metre}\right]$
\end{document}
```
However, most authorities on math typesetting would say that here the brackets should not grow. Moreover, I suspect you are using `[...]` as a way of 'removing' units from quantities: as detailed in the manual, this really should be done by division:
```latex
\documentclass{article}
\usepackage{siunitx}
\sisetup{per-mode = symbol, text-family-to-math}
\begin{document}
\sffamily
$X/(\unit{\watt\per\square\metre})$
\end{document}
```

**Comment by josephwright** [comment]
('d likely omit `per-mode = symbol` for that.)

**Comment by SReich-EMI** [comment]
Thanks for the fast reply. Yes, partly I want to use it ro "remove" the unit knowing, that this is not by SI definition. But it so very common. But ok, there I know, that I'm not by standard.
That math typesetting says that the braces should not grow with larger content I din't know. If this is the rule ok, although I do not consider it as beautiful.
As both points I mentioned are outside definitions, I'll close the Issue staying unsatisfied.
