### ISSUE TITLE
Uncertainty listed with too many digits (round-mode=uncertainty,round-precision=2)

### ISSUE THREAD

**Issue by nomeata** [josephwright/siunitx#643]
Some digit calculation seems to be off:

![siunitx-bug](https://user-images.githubusercontent.com/148037/221421520-3424a75f-16f1-497c-b5f0-4d8546457198.png)

Created with this file:
```
\documentclass{article}
\usepackage{expl3}
\usepackage{siunitx}
\begin{document}
\sisetup{round-mode=uncertainty,round-precision=2}

\verb|\num{1.23\pm0.1.1}|:
\num{1.23\pm0.11}

\verb|\num{1.23\pm0.109}|:
\num{1.23\pm0.109}

\end{document}
```

This is with version 3.0.49. I tried somewhat hard to install the latest version locally, but failed (it required a newer expl3, and then things got complicated). Hopefully this is not a useless report.

**Comment by josephwright** [comment]
Both of these come out correctly with v3.2.0.

**Comment by nomeata** [comment]
Sorry for the noise and thanks for checking!

(For those who can’t upgrade to the fixed version just yet and find this issue: my current work-around for now was to format the uncertainty numbers in the Python code that’s generating them using `{…|#.2g}`.)
