### ISSUE TITLE
Italian localisation

### ISSUE THREAD

**Issue by matteofg** [josephwright/siunitx#650]
Is it possible to have support for the Italian language?
Below are keys and translations:
```
- exponent-product = \times
- inter-unit-product = \,
- output-decimal-marker = { , }
```
```
- list-final-separator = { e }
- list-pair-separator = { e }
```
About `range-phrase` in Italian, two prepositions are used: **da** 1 **a** 3... **da** 10 kg **a** 12 kg...

Matteo

**Comment by josephwright** [comment]
I've added the code in a branch for the next feature release. The `da` part is not currently implemented as I don't include the 'from' phrase as standard. That's because it's not universally required: certainly in English I can say 'in the range X to Y' _or_ 'in the range from X to Y' and both are correct. So I'm wary of adding anything here: the 'from' feels to me like an optional part of the text not a required part of specifying a range.

**Comment by matteo339** [comment]
Thank you for your answer.
> So I'm wary of adding anything here: the 'from' feels to me like an optional part of the text not a required part of specifying a range.

Unfortunately, in Italian, it is a mandatory part: you cannot write/say "10 kg **a** 12 kg"...

Meanwhile thank you for the support!

Matteo

**Comment by josephwright** [comment]
> Unfortunately, in Italian, it is a mandatory part: you cannot write/say "10 kg **a** 12 kg"...

I suspected that, what I'm wondering is if you need it if you write the range without a word in it, _e.g._ do you write `da X-Y kg` or not? That affects whether `siunitx` should insert additional information.

**Comment by matteo339** [comment]
> what I'm wondering is if you need it if you write the range without a word in it, e.g. do you write da X-Y kg or not?

Even then, writing `da X-Y kg` makes no sense :-(
Currently the only solution is to change the form of the sentence, writing, for example: _"numbers in the range 5-9 are..."_ instead of _"numbers 5 to 9 are..."_.

Matteo

**Comment by josephwright** [comment]
I'll think a bit more about this and see if I can find a solution

**Comment by josephwright** [comment]
> Thank you very much.
> 
> Meanwhile, I would like to ask an off-topic question that perhaps does not need a separate discussion: why is it necessary to specify the `locale` option even if you use `babel/polyglossia`? Writing:
> 
> ```
> \usepackage{polyglossia}
>   \setmainlanguage{german}
> \usepackage[locale=DE]{siunitx}
> ```
> 
> seems to be a redundancy. If I needed to change some parameters that are set by language, it would seem more logical to me to change the parameter explicitly, for example:
> 
> ```
> \usepackage{polyglossia}
>   \setmainlanguage{german}
> \usepackage{siunitx}
>   \sisetup{output-decimal-marker={,}}
> ```
> 
> But surely I am missing something :-)

I point out in the manual that you can link the locale and the language. The split arises as the settings in `siunitx` are really about the typographic tradition wherever you do the typesetting, which I've called the locale. That's independent of the language the document happens to be written in. For example, in the UK we'd use `.` for the decimal marker, and that would remain true even if the _text_ is written in some other language (particularly say in a quote). So I leave the question of linking locale and language to the author.

**Comment by josephwright** [comment]
I'm looking back at this: I think I have a general plan, just implementing the specifics

**Comment by josephwright** [comment]
I've committed the partial fix I have plus a mechanism at 'my' end to do the 'from' part: I now need some changes in a support package to finalise a fix.

**Comment by josephwright** [comment]
Pushing any further change to v3.4

**Comment by josephwright** [comment]
I think looking back we are done here: anything additional can go down as a new issue.

**Comment by matteofg** [comment]
So does that mean you couldn't add full support for Italian? What a shame!

**Comment by josephwright** [comment]
@matteofg No, that I thought looking back at the issue that it's sorted at the `siunitx` end - if not, remind me what's missing :)

**Comment by matteofg** [comment]
The locale option `locale=IT` has been added, but support for `\SIrange` is missing.
```
\documentclass{article}
\usepackage[italian]{babel} 
\usepackage[locale=IT]{siunitx}

\begin{document}
\SIrange{0.001}{1}{\hertz}
\end{document}
```
Correct output is "**da** 0,001 Hz **a** 1 Hz", not "0,001 Hz **a** 1 Hz".
