### ISSUE TITLE
Singular Version 3 style file for the use in e.g. Scientific journals

### ISSUE THREAD

**Issue by EmCeBeh** [josephwright/siunitx#651]
Unfortunately, many scientific journals and arXiv.org still run on a <2021 Tex Live Version, not including v3 of Siunitx. They do, however, let you submit a `.sty` file. In this repository and on your website, I can only find the V2 and several packages for V3, but not a complete one for V3. Could you maybe, please help me out in compiling one myself or provide me with one?

**Comment by EmCeBeh** [comment]
Thanks for the quick reply! As far as I understand, the v2 does not support products like `\qtyproduct` and `\SIproduct` does not exist and would I just use` \SI{80x1.25}{\um}` and it should look equal?
I guess I just convert `\qty` and `\qtyrange` to `\SI` and `\SIrange` and do the product this way, then.

It's just sad, that someone (you) already made all the effort of programming these nice tools and now we can not use them, because the publisher are still stuck with a >2 year old tex installation.

Also I tried to use the `siunitx.sty`, but it failed due to the missing/outdated `expl3`.

**Comment by josephwright** [comment]
As `expl3` is nowadays baked into the kernel, it's rather tricky to update to an arbitrary version. I try not to step the requirements for `siunitx` too often, but it is sometimes required. 

Here, I would just stick with using v2 for the present: you can load that on a newer system with
```latex
\usepackage{siunitx}[=v2]
```
as you'll then get identical output all-round.
