### ISSUE TITLE
Rounding of uncertainty with leading zeros is erroneous

### ISSUE THREAD

**Issue by Gerald-Meyers** [josephwright/siunitx#652]
Perhaps this is an `Overleaf` problem, but I am running into a few issues with `siunitx`.

- First the requests

When a user is supplying numerical values via software, rounding is specified manually, e.g. either `\sisetup` must be called with the option `round-mode` set to `figures` or `uncertainty` (also `places` and `none`). At this same time, or when the number is provided, the option round-precision must also be provided with a set number of figures to be retained. Further, when the numerical value is provided, if it is a measurement it must come with an explicit uncertainty. If the quantity is not a measurement, an uncertainty will not be generally provided. 

Currently a user has to specify if they want the rounding to occur with uncertainty or figures. It would be very convenient if there was another rounding option `smart` that takes into consideration whether an uncertainty was provided. I could do something like:
`\sisetup{ uncertainty-mode = separate, exponent-mode = scientific, round-mode = smart, }`
`\SI[round-precision=4]{3031523.20585698(74336.4927580466)}{\meter\per\second}`
to get the equivalent of: $(3.0315 \pm 0.7434) \times 10^6 m/s$. Similarly 
`\SI{round-precision=3}{299 792 458 }{\meter\per\second}` yields $3.00 \times 10^8m/s$.
As it stands currently, if we use `\sisetup{round-mode=uncertainty}`, the second number fails to round to 3 significant digits and just prints out the same value.

Some applications benefit from relative uncertainty, where the first value is factored out to create the form 
`$val \times (1 \pm rel_uncertainty)$`, or with exponentials 
`$val.xxxx \times (1 \pm rel_uncertainty) \times 10^{exponent}$`.
If `uncertainty-mode` had another option `relative` that formatted in this manner, that would be nice!

- Second some issues ( also one issue noted above )

Additionally, 
`\SI[round-mode=uncertainty,round-precision=4]{.010112072952338846(0.00024795984947041796)}{\c}`
does not correctly round, and instead yields $(1.0 \pm 00 020.0) \times 10^{−2} c$. Manually modifying the input to 
`\SI[round-mode=uncertainty,round-precision=4]{1.0112072952338846(0.024795984947041796)e-2}{\c}`
yields the correct(ish) output of $(1.011 \pm 0.248) \times 10^{−2}c$. Of course this is still with `\sisetup{exponent-mode=scientific}`.
I also note that setting `round-precision=2` here yields $(1.0 \pm 0.2) \times 10^{−2} c$ which contradicts the manual which states "is used first to round the uncertainty itself (to a number of figures)" since the uncertainty is not rounded to 2 significant figures. Additionally the decimal is in the **wrong place**.

**Comment by josephwright** [comment]
I'm going to look at the bug in this issue, and will split out the two feature requests to separate issues shortly unless you beat me to it.

**Comment by josephwright** [comment]
The bug here isn't in the rounding code (I'm relieved, I've worked pretty hard on fixing issues there!). Rather, it's the parsing code for the 'full form' uncertainty, which isn't removing the leading `0` or getting the padding of the main part right. I'll see if I can track down why - I suspect this area has been less hard-pushed.

**Comment by josephwright** [comment]
@Gerald-Meyers  I've opened the two parallel issues for the feature requests
