### ISSUE TITLE
Wrong/missing product-symbol with mode=match

### ISSUE THREAD

**Issue by juhaszp95** [josephwright/siunitx#656]
Hello,

Thanks for maintaining siunitx. I'm using siunitx in with `mode=match`, but I'd like to ensure that for product the math-mode `\times` is used (I don't like the text-mode times symbol of my font - it's a bit too small). However, when I set `product-symbol=\ensuremath{\times}`, the separator is missing.

MWE:
```
\documentclass{article}
\usepackage{newtxtext,newtxmath} % just so that we can tell fonts more easily apart; could be anything
\usepackage[mode=match]{siunitx}

\begin{document}
	\numproduct{1 x 2} \ $\numproduct{1 x 2}$ \ \numproduct[product-symbol=\ensuremath{\times}]{1 x 2} \ $\numproduct[product-symbol=\ensuremath{\times}]{1 x 2}$
\end{document}
```

I get the following output:
![image](https://user-images.githubusercontent.com/36235630/234556234-578f8efd-76d1-423b-ad06-006725fa9ab2.png)

Note how the separator is missing in the third case. Any help would be greatly appreciated.

**Comment by josephwright** [comment]
Fixed by f5dd39f35155095d8f3c12a9a336937a6674ee2f

**Comment by juhaszp95** [comment]
Many thanks for fixing this. Is there any chance this could be issued as a new release of siunitx?

**Comment by juhaszp95** [comment]
Hello,

Sorry to reopen this, but I've just realised the symbol is now there, but the spacing is wrong. I wonder if we could do anything about this? The result I now get:

![image](https://github.com/josephwright/siunitx/assets/36235630/290b9cac-8e4f-41a1-add9-e0cc9cc151ae)
