### ISSUE TITLE
No font weight for percent values.

### ISSUE THREAD

**Issue by Zadagu** [josephwright/siunitx#660]
Hi,
thank you for your awesome package. It makes numbers and units always look nice.
However, I run into an issue, when i wanted to highlight the best values in a table.

I cut it down to the following example.
```
\documentclass[11pt]{article}

\usepackage{amsmath}
\usepackage{siunitx}

\begin{document}
    \textbf{\qty{76.4}{\percent}}
\end{document}
```

In that example, neither the number, nor the percent sign are rendered bold.
I used LuaHBTeX, Version 1.16.0 (TeX Live 2023/Arch Linux).

**Comment by josephwright** [comment]
This is by-design: quantities should be set in the standard body font normally. You can set `\sisetup{text-series-to-math}` to pass the text weight to the math mode font, or use `\sisetup{mode = text, reset-text-series = false}` to print in text mode with bold 'allowed'.

**Comment by Zadagu** [comment]
Thank you.
It works :+1:
