### ISSUE TITLE
There is no \textmp in Latex, replace it with a mirrored \textpm

### ISSUE THREAD

**Issue by fhaust** [josephwright/siunitx#662]
I just fought a bit with siunitx to get it to display nice minus/plus signs like this:

![image](https://github.com/josephwright/siunitx/assets/3219263/13a92feb-a494-4691-89d7-33cdde000df1)

My "fix" was to add a replacement entry in siunitx.sty like this:

```tex
\cs_new:Npn \__siunitx_print_text_replace_first:N #1
  {
    \str_case:nnF {#1}
      {
        { \cdot }  { \exp_not:N \textperiodcentered }
        { \pm }    { \exp_not:N \textpm }
        { \mp }    { \exp_not:N \reflectbox{\rotatebox[origin=c]{180}{\textpm}} }    % <--- this replaces \mp by a mirrored \textpm in text mode
        { \times } { \exp_not:N \texttimes }
      }
      {#1}
  }
```

Feels like a hack, but works like a charm.

**Comment by fhaust** [comment]
True, the issue is that this is typeset in math mode:

![image](https://github.com/josephwright/siunitx/assets/3219263/d27d84b0-2015-4f37-babe-8122a1116fb4)

vs.

![image](https://github.com/josephwright/siunitx/assets/3219263/5bc02074-e074-4622-96b6-f5f4fc566450)

**Comment by josephwright** [comment]
Other than `hyperref`, I can't find any LaTeX definition for `\textmp`: where did you pick up the idea it should work in text?

**Comment by josephwright** [comment]
I've discussed with the LaTeX team and we are all sure that `\textmp` is not a general text command; indeed, the only generally-available symbol here is definitely classed as a math mode one. So I don't think an _ad hoc_ addition to `siunitx` is appropriate.
