### ISSUE TITLE
per-mode=fraction with unit parsing

### ISSUE THREAD

**Issue by TheChilliPL** [josephwright/siunitx#663]
```latex
\sisetup{per-mode=fraction}
```
doesn't seem to work if units are parsed, instead of using built-in macros:
```latex
\SI{1.38e-23}{m^2.kg/s^2.K} \quad \SI{1.38e-23}{\meter\squared\kilo\gram\per\second\squared\kelvin}\\
```
(along with some more options) shows this:
![image](https://github.com/josephwright/siunitx/assets/18823939/7966b22f-fbba-4dd6-8a69-8e04930f0b71)

Is it possible to make parsed units automatically show up as fractions?

**Comment by josephwright** [comment]
No parsing takes place for literal units. There is an open feature request for parsing 'free text' units, but I am not sure I will try to parse arbitrary math mode. See https://github.com/josephwright/siunitx/issues/496
