### ISSUE TITLE
Error in exponent-mode = engineering, prefix-mode = combine-exponent

### ISSUE THREAD

**Issue by AndreaDiPietro92** [josephwright/siunitx#668]
MWE
Package: siunitx 2023-06-12 v3.2.6 A comprehensive (SI) units package

```
\documentclass{article}
\usepackage{siunitx}
\sisetup{
exponent-mode = engineering,
prefix-mode = combine-exponent
}%

\begin{document}
\qty{0.000001}{\ampere}\\
\qty{10000}{\V}
\end{document}
```

In the first case I should obtain `1 uA` (and it is what i obtain). In the second case I should obtain `10kV`, but i get `10.000 kV`. Is it a bug or am I using wrong settings?

**Comment by rafaelpap** [comment]
Why do you believe it's wrong? In the first case there is one significant figure and in the second case there are five significant figures.

**Comment by josephwright** [comment]
@AndreaDiPietro92 Well perhaps, but `siunitx` won't drop digits that may be significant unless you explicitly ask. Here, you likely want `drop-zero-decimal`.

**Comment by AndreaDiPietro92** [comment]
Yes, but even with `drop-zero-decimal`
```
\qty{12 120 000 000}{\V}
```
returns `12.120 000 000 GV` instead of `12.120 GV`, `\qty{12120e6}{\V}` works correctly.

**Comment by josephwright** [comment]
> Yes, but even with `drop-zero-decimal`
> 
> ```
> \qty{12 120 000 000}{\V}
> ```
> 
> returns `12.120 000 000 GV` instead of `12.120 GV`, `\qty{12120e6}{\V}` works correctly.

Yes, in that case you are rounding, so you'd need to activate that. We *cannot* assume that zeros in the integer part of a value are non-significant without additional information.

**Comment by AndreaDiPietro92** [comment]
So, it's better use the exponent notation to get the wanted behavior
```
qty{1212e6}{\V}
```
Is it right?
