### ISSUE TITLE
unit options when using pgfplots

### ISSUE THREAD

**Issue by rs7q5** [josephwright/siunitx#669]
I am probably do something wrong, but I can't seem to get my units formatted correctly with pgfplots

As per the pgfplots manual, I have the following in the preamble `\pgfplotsset{unit code/.code 2 args={\unit{#1#2}}}`, it does give the same results as `\si`, but how do I send in separate options to format, as even doing `\unit[inter-unit-product=\times{-}]{\watt\per\meter^2\per\kelvin}`, keeps giving me $W/m^2K$ or $W/m^2/K$ instead of $W/m^2-K$. Any idea why this may be happening or how I can force it to allow me to send in unit options or why those aren't working. 

putting the units in ylabel with pgfplots does not seem to fix the issue either. 

Any suggestions are greatly appreciated.

**Comment by josephwright** [comment]
This is nothing to do with `pgfplots`. You've used a mix of literal input (`^2`) and symbolic units (`\watt`). Under those circumstances, `siunitx` treats all of the input as pre-formatted literals and you get what you typed. If you want to allow the package to manage the appearance, you'd use `\watt\per\metre\squared\per\kelvin`. (I've use `\metre` as that's the official name of the unit: it will work with `\meter`, but that's a device for measuring things.)

**Comment by rs7q5** [comment]
Thanks for the quick response, but it still doesn't seem to work, at least putting it with using `y_unit` with pgfplots.... I'm guessing because the unit_code is not actually setting options... But it works when I put it in `ylabel=`. I guess I can use that for a work around though.

**Comment by rs7q5** [comment]
actually doing the following `\DeclareSIUnit[per-mode=symbol,inter-unit-product=\text{-}]{\hcunit}  {\watt\per\meter\squared\per\kelvin}` and doing the following `ylabel=\unit{\hcunit}`  gives the expected result, but doing `y_unit={}{\hcunit}` does not.
