### ISSUE TITLE
\sisetup{exponent-mode=threshold} generates LaTeX3 error

### ISSUE THREAD

**Issue by adam-neuro** [josephwright/siunitx#673]
\sisetup{exponent-mode=threshold} generates the LaTeX 3 error: "LaTeX3 Error: Key 'siunitx/exponent-mode' accepts only a fixed set of(LaTeX3) choices. \sisetup{exponent-mode=threshold}"

It seems like the "threshold" option is not supported/defined? Also the key "exponent-thresholds" is also not defined. I'm using siunitx v3.0.49 on my local machine, and I also get the same error in Overleaf, whatever versions they're using. I'm using pdfTeX 3.141592653-2.6-1.40.24 (TeX Live 2022). 

Did the syntax change? The documentation makes it seem like I should still be using exponent-mode=threshold. How should I be doing this to get the thresholded exponentiation behavior?

**Comment by adam-neuro** [comment]
I just typed "texdoc siunitx" in the terminal and the PDF that opened had that option described and the footnote on the bottom of the title page said "∗This file describes v3.0.49, last revised 2022-02-15."

**Comment by adam-neuro** [comment]
Actually, now I see that I have gotten mixed up between that PDF and the documentation online which I had open in the background also. Anyway, I am updating my packages now and will try again, thanks.

**Comment by josephwright** [comment]
I was just double-checking the log: I am confident I didn't accidentally document this early :)

**Comment by adam-neuro** [comment]
yes, old version was the problem. thanks
