### ISSUE TITLE
Unable to use `exponent-mode = threshold` in Overleaf

### ISSUE THREAD

**Issue by hunterbarber** [josephwright/siunitx#674]
Not sure if this is improper use or a bug, and I also don't know whether this is in Overleaf or siunitx. I'm trying to apply `exponent-mode = threshold` in Overleaf TeX Live 2022. I'm am seeing error
```
! LaTeX3 Error: Key 'siunitx/exponent-mode' accepts only a fixed set of
(LaTeX3)        choices.
```
when using 
```
\sisetup{
    ...
    exponent-mode = threshold,
    ...
}
```
I confirmed the other exponent-mode options work as intended.

**Comment by mrpiggi** [comment]
see #673

**Comment by josephwright** [comment]
This option was only added for v3.2.0 which was released in early January: as such it was not in TL'22.

**Comment by hunterbarber** [comment]
I ironically searched the current issues, but didn't remove the open filter. Thank you for the response.
