### ISSUE TITLE
Space between superscripts and `\per` symbol is too narrow

### ISSUE THREAD

**Issue by rlndksr** [josephwright/siunitx#676]
Starting with siunitx v3.1.0, there seems to have been a change in the spacing before `\per` (with `per-mode=symbol`) in cases where it is immediately preceded by a superscript. It's a lot tighter now compared to v3.0.50 and older. Here's an example document where the difference is visible:

```
\documentclass{article}
\usepackage{siunitx}
\begin{document}
\qty[mode = text, per-mode = symbol]{100}{\meter\squared\per\gram}
\end{document}
```

The output produced by the example code actually looks a bit more evenly spaced with v3.1.0+, which lead me to believe that maybe the change was intentional, but I couldn't find any documentation to confirm.

The problem with the new spacing is that when it is used in combination with OpenType superscript glyphs, it looks really cramped whereas it was fine before. Compare for example the output of the following code when using v3.0.50 (or older) vs. more recent versions:

```
\documentclass{article}
\usepackage{realscripts}
\usepackage{noto}  % Another example: \usepackage{xcharter-otf}
\usepackage{siunitx}
\begin{document}
\qty[mode = text, per-mode = symbol]{100}{\meter\squared\per\gram}
\end{document}
```

**Comment by josephwright** [comment]
In commit d46c8ecbaf5467c2f11a72a1cb98e309bb9f2ce1, I added the option `per-symbol-script-correction`, with standard setting `\!`. This is because with the standard LaTeX fonts, the space between text and a `/` is too large. I don;'t think in pdfTeX/LuaTeX there is a way to avoid needing some manual intervention here.
