### ISSUE TITLE
`complex-angle-unit` not recognized as a key in `\sisetup`

### ISSUE THREAD

**Issue by mbaz** [josephwright/siunitx#707]
I work with complex numbers expressed in polar form in radians. I tried to configure this behavior using:

```
\sisetup{complex-angle-unit = radians}
```
but that fails when compiling the document:
```
LaTeX3 Error: The key 'siunitx/complex-angle-unit' is unknown and is being
(LaTeX3)        ignored.
```

Other complex-related options such as `input-complex-root` and `output-complex-root` work fine.

**Comment by josephwright** [comment]
The option was added in v3.1.0, released  2022-04-25. I suspect you have an older version: can you add `\listfiles` to your input and report the version line for `siunitx` that then appears in the `.log`.

**Comment by mbaz** [comment]
Thank you. I'm using v3.0.49. I should have verified that before opening the issue. I switched to tectonic recently, which downloads packages on demand, and (wrongly) assumed that it downloaded the latest versions of all packages.
