### ISSUE TITLE
mode = text not working. Oldstyle numbers are not applied.

### ISSUE THREAD

**Issue by dflvunoooooo** [josephwright/siunitx#708]
The option `mode = text` does not work. In the below example you can see, that the oldstyle numbers don't get applied to the numbers in `\num[mode = text]{…}` nor in `\num[mode = match]{…}.` On the other hand the depreciated option `\num[detect-all]{…}` does work. 

```
\documentclass{scrreport}

\usepackage{fontspec}
\usepackage{siunitx}

\setmainfont{Libertinus Serif}	

\begin{document}
Normal
1234567890

\num[mode = text]{1234567890}

Oldstyle
\addfontfeature{Numbers=OldStyle}

1234567890

\num[mode = text]{1234567890}

\num[mode = match]{1234567890}

\num[detect-all]{1234567890}

\end{document}
```

![Screenshot_20231221_161625](https://github.com/josephwright/siunitx/assets/32816598/5c471b3c-00c3-4459-8a0a-1036d0311a08)

**Comment by josephwright** [comment]
`\addfontfeature` doesn't reset `\rmdefault` to apply old-style numbers, so `siunitx` doesn't either - you can set `reset-text-family = false` to leave the current family alone.

**Comment by dflvunoooooo** [comment]
Thank you for your answer. So `mode = text` does not apply the text settings? The option `reset-text-family = false` does unfortunately not work.

**Comment by josephwright** [comment]
You need _both_ `mode = text` and `reset-text-family = false`, as the latter only applies in text mode.

**Comment by josephwright** [comment]
> Thank you for your answer. So `mode = text` does not apply the text settings? 

It does - as standard the _default_ roman text - `\addfontfeature` doesn't change the defaults, only the current font.

**Comment by dflvunoooooo** [comment]
I see. Thank you for explaining.
