### ISSUE TITLE
How to get a range with a tilde, like "1~2 m"?

### ISSUE THREAD

**Issue by beijiguang94** [josephwright/siunitx#709]
In this version, is it possible to get a range "1~2 m" besides "1-2 m" using "\qtyrange"?
Ranges with a tilde are clearer than those with a dash, especially when involving negative numbers.

**Comment by josephwright** [comment]
```latex
\documentclass{article}
\usepackage{siunitx}
\sisetup{range-phrase = \textasciitilde, range-units = single}
\begin{document}
\qtyrange{1}{2}{\m}
\end{document}
```

**Comment by beijiguang94** [comment]
Thanks @josephwright . It's a quick reply.
