### ISSUE TITLE
Bug when combining \sqrt with scientific notation and number-mode=match, with workaround

### ISSUE THREAD

**Issue by bamford** [josephwright/siunitx#721]
I have been trying to typeset $\sqrt{3}\times10^{10}~m^{-1}$ using `\qty`, similar to `\qty{3e10}{m^{-1}}`, in a document that uses `\sisetup{number-mode=match}`.

Using `parse-numbers=false` almost works:
```latex
\sisetup{number-mode=match}
The number is not \qty{3e10}{m^{-1}}, but rather \qty[parse-numbers=false]{\sqrt{3}\times10^{10}}{m^{-1}}.
```
produces:
<img width="809" alt="Screenshot 2024-02-14 at 20 16 05" src="https://github.com/josephwright/siunitx/assets/219174/c2d7ab05-d30a-477c-bbc6-94df731ed14a">
which somehow typesets the $\sqrt{3}$ in the text font, but the $\times 10^{10}$ in the math font!

Presumably this is unintended behaviour, that someone with knowledge of the internals of siunitx may be able to fix.

After some experimentation I found that adding the `number-mode=math` option and wrapping the number in `\text{}` produes the desired output, although I’m not sure why! So, this is a workaround:
```latex
\sisetup{number-mode=match}
The number is not \qty{3e10}{m^{-1}}, but rather \qty[number-mode=math, parse-numbers=false]{\text{\sqrt{3}\times10^{10}}}{m^{-1}}.
```
which produces:
<img width="809" alt="Screenshot 2024-02-14 at 20 16 27" src="https://github.com/josephwright/siunitx/assets/219174/c634c88d-87cf-4cd0-9cb7-4e2f79a49812">

I'm using LuaLaTeX with TeX Live 2023 on Overleaf.

**Comment by josephwright** [comment]
I've corrected the behaviour here: you get everything in _math mode_ - that is the documented approach when not parsing numbers.

**Comment by bamford** [comment]
That was fast! Many thanks @josephwright.
