### ISSUE TITLE
local Per mode setting is ignored in align environment

### ISSUE THREAD

**Issue by dflvunoooooo** [josephwright/siunitx#722]
If I set the `per-mode` inside a `align` environment, it gets ignored, if the setting bevore was `symbol`. Here is an example

![Screenshot_20240306_215326](https://github.com/josephwright/siunitx/assets/32816598/bef75322-b2c3-46e8-a836-3bf0c009cc47)

Here is the code
```
\documentclass{scrartcl}

\usepackage{siunitx}
\usepackage{amsmath}	
\sisetup{
    per-mode = symbol,
}

\begin{document}
\qty{504.4667}{\per\second}
\begin{equation}
    \sisetup{per-mode=fraction}
    K_\mathrm{Zufällig} =\qty{504.4667}{\per\second}\\
     = \qty{1}{\volt\per\ampere}
\end{equation}

\begin{align}
    \sisetup{per-mode=fraction}
    K_\mathrm{Zufällig} &=\qty{504.4667}{\per\second}\\
     &= \qty{1}{\volt\per\ampere}
\end{align}

\end{document}
```

I don't know if it is related to #103.

**Comment by josephwright** [comment]
Table cells are groups in TeX: this is entirely normal behaviour.
