### ISSUE TITLE
Padding not correct / decimal point at wrong place

### ISSUE THREAD

**Issue by Splines** [josephwright/siunitx#725]
## Presumptions

I use the following sisetup:

```latex
\sisetup{
	locale=US,
	group-separator={,},
	group-digits=integer,
	per-mode=symbol,
	separate-uncertainty=true
}
```

## Description of problem
I'm wondering why this input:

```latex
$$\qty[minimum-decimal-digits=6]{5.407 \pm 0.04}{\m}$$
```
is printed as
<img src="https://github.com/josephwright/siunitx/assets/37160523/a8a6164e-595d-49cc-a0ff-4a766d44ff6f" width="450px"/>
`(5.407000 \pm 0.004000) m` in the LaTeX document. Note that siunitx altered the uncertainty from `0.04` to `0.004`.

---

The root cause for this is probably the same for the following confusing output:
```latex
\NewDocumentCommand{\UncertStat}{}{_{\text{stat}}}
\NewDocumentCommand{\UncertSys}{}{_{\text{sys}}}
\sisetup{input-digits=0123456789\UncertStat\UncertSys\UncertSystematic}

$$\qty{5.407 \pm 0.010\UncertSys \pm 0.04\UncertStat e-7}{\m}$$
```

will result in:

![image](https://github.com/josephwright/siunitx/assets/37160523/8da73600-f63b-498d-8416-17c28a85fea5)

note that the `0` is printed after the `\text{stat}`. Is there a way to get rid of this trailing `0` altogether?

## Efforts taken
- Searched in the [docs](https://texdoc.org/serve/siunitx/0) for "pad" and found: `round-mode` as well as `round-pad`, but these settings didn't help. Also found out about `minimum-decimal-digits`.
- Search in issues and found #652, that also complains about a misaligned decimal point. I hope this here is not a duplicate.
- Searched in the [changelog](https://github.com/josephwright/siunitx/blob/main/CHANGELOG.md). The only occurrence for "pad" is for the introduction of `round-pad` in version `v3.0.0`. Searched for "minimum" and found that #601 is fixed in `v3.0.50`. As I'm using `3.1.11`, I should have this fix available.

## Additional context

If you're wondering why we need this `\NewDocumentCommand` stuff. A friend of mine and me currently build a Python library called [`ResultWizard`](https://github.com/resultwizard/ResultWizard) as an interface between Python code and the siunitx LaTeX package. We're in the second alpha version right now and stumbled upon the described issue [here](https://github.com/resultwizard/ResultWizard/issues/31).

## System Information
I'm using TeX Live in WSL (Ubuntu 22.04 jammy). siunitx version: `3.1.11 (2022-12-05)`.

**Comment by josephwright** [comment]
Minimised example
```latex
\documentclass{article}
\usepackage{siunitx}
\sisetup{minimum-decimal-digits = 4}
\begin{document}
\qty{5.407 \pm 0.04}{\metre}
\end{document}
```d

**Comment by josephwright** [comment]
> The root cause for this is probably the same for the following confusing output:

Off-topic here, but you seem to have missed that `siunitx` has native support for multiple uncertainties from v3.1.0, released 2022-04-25.

**Comment by Splines** [comment]
Thanks a lot for your hot fix 🎉

Unfortunately, users of our library might not be easily able to use an updated version of siunitx. E.g. even for the current LTS Ubuntu (Ubuntu 22.04 jammy), the siunitx version that comes shipped with `sudo apt install texlive-science` is `3.0.4`. We do provide an update guide [here](https://github.com/resultwizard/ResultWizard?tab=readme-ov-file#troubleshooting-latex-doesnt-build), but only up to version `3.1.11 (2022-12-05)`, as this is the last one before we'd have to update other dependencies as well as you make use of the new LaTeX3 layer and `expl3` is breaking for us.

That's why I'm asking if there is a workaround when using version `3.1.11 (2022-12-05)` to still get this correctly output:
```latex
\NewDocumentCommand{\UncertStat}{}{_{\text{stat}}}
\NewDocumentCommand{\UncertSys}{}{_{\text{sys}}}
\sisetup{input-digits=0123456789\UncertStat\UncertSys\UncertSystematic}

$$\qty{5.407 \pm 0.010\UncertSys \pm 0.04\UncertStat e-7}{\m}$$
```

**Comment by josephwright** [comment]
@Splines The auxiliary hasn't changed name, so
```latex
\ExplSyntaxOn
\cs_gset:Npn \__siunitx_number_digits_uncert_aux:nn #1#2
  {
    \exp_not:n {#2}
    \int_compare:nNnT
      { \l__siunitx_number_min_decimal_int - \tl_count:n {#1} } > 0
      {
        \prg_replicate:nn
          { \l__siunitx_number_min_decimal_int - \tl_count:n {#1} } { 0 }
      }
  }
\ExplSyntaxOff
```
will locally adjust the code.

I'm still not clear why you are not using the built-in multi-uncertainty support in v3.1.

**Comment by Splines** [comment]
Thanks a lot! 

> I'm still not clear why you are not using the built-in multi-uncertainty support in v3.1.

I thought that multi-uncertainty support only referred to being able to add multiple `\pm`s to a number. Having looked through the docs again now, I found the `uncertainty-descriptors` key and that's exactly what I needed in the first place 🙌. The `\NewDocumentCommand` was just a workaround since we didn't know about the other option ;)
We will recommend our users to add this to their preamble:

```latex
\sisetup{uncertainty-descriptor-mode=subscript}
```

and then generate programatically the following output for quantities:
```latex
\qty[uncertainty-descriptors={customlabel1,customlabel2}]{1.2 \pm 0.1 \pm 0.05}{\m}
```

**Comment by Splines** [comment]
```latex
\qty{5.407 \pm 0.010 \pm 0.04}{\m}
```

Is there a way to print the `0.04` "as is", i.e. not `0.040`? With `round-pad=false` and `round-mode=none` and `minimum-decimal-digits=0`, we still get `0.040` in version `3.1.11 (2022-12-05)`. Even with you're hotfix (manually applied via your [workaround](https://github.com/josephwright/siunitx/issues/725#issuecomment-2051530043)) it's not working as expected. Maybe I have missed a crucial option in the docs?

**Comment by josephwright** [comment]
> \qty{5.407 \pm 0.010 \pm 0.04}{\m}
> 
> Is there a way to print the `0.04` "as is", i.e. not `0.040`? With `round-pad=false` and `round-mode=none` and `minimum-decimal-digits=0`, we still get `0.040` in version `3.1.11 (2022-12-05)`. Even with you're hotfix (manually applied via your [workaround](https://github.com/josephwright/siunitx/issues/725#issuecomment-2051530043)) it's not working as expected. Maybe I have missed a crucial option in the docs?

No, becaue the main value here has 3 decimal places, so the uncertainty _must_ also be specified to the same precision.

**Comment by josephwright** [comment]
(Or rather that's the internal model `siunitx` uses.)

**Comment by josephwright** [comment]
@Splines  I can imagine an approach but that's definitely a non-trivial feature request for the current release not something that can be shoehorned into a past release.

**Comment by Splines** [comment]
In the case you're willing to put your time and effort into such a feature (which would be much appreciated), we'd like to then also be able to make our users profit from it. That's why I've opened #726 to get to know how users can upgrade to the most recent version of siunitx without having to rethink their entire LaTeX setup.

**Comment by josephwright** [comment]
@Splines  Please open a separate issue - including supporting links/PDFs/whatever that show that this approach is used by professionally-typeset material (that's my usual requirement for feature requests).
