### ISSUE TITLE
ohm do not work when kmath package is loaded

### ISSUE THREAD

**Issue by JoseDanielMunozFrias** [josephwright/siunitx#728]
When using `kmath` package, the ohm symbol do not render inside equations. Is a bug or I'm doing something wrong?

```latex
\documentclass{article}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}

\usepackage{bookman}
\usepackage{kmath}
\usepackage{kerkis}
\usepackage{upgreek} 
\usepackage{siunitx}%[=v2]

\begin{document}

When using the package kmath, the ohm symbol does not work inside an equation: $R = \SI{10}{k\ohm}$

But works OK outside: \SI{10}{k\ohm}.

Using siunitx v2 works, but this version uses another font for the ohm symbol.

\end{document}
```

**Comment by josephwright** [comment]
I'm going to use the same approach as https://github.com/josephwright/siunitx/issues/572.

**Comment by JoseDanielMunozFrias** [comment]
¡Thank you for your promptly response! 

However, now the symbol used for the ohm inside the equations is different of the symbol used outside.

**Comment by josephwright** [comment]
@JoseDanielMunozFrias  OK, that's a separate issue and is not trivial - I need to think about what is 'supposed' to happen here!

**Comment by josephwright** [comment]
I have a plan - will sort in another issue.

**Comment by JoseDanielMunozFrias** [comment]
¡Thanks a lot! Now it works perfectly.
