### ISSUE TITLE
Add support or alternative for steinmetz

### ISSUE THREAD

**Issue by eclecticfluff** [josephwright/siunitx#732]
I wish to be able to typeset polar complex numbers in the style given by the `steinmetz` package, but unfortunately `complex-symbol-angle = \phase` does not work. I would appreciate it if the internal code could be changed for this to work, or alternatively another key be added explicitly for wrapping the phase component of polar complex numbers in an arbitrary macro.
Ideally, a new function could be created within `siunitx` to match this style of typesetting, adding options to better match font and scale in a smarter way than blindly enclosing the bounding box. This would likely take considerably more effort to implement, however, so I understand if contributor motivation isn't there for it.

**Comment by eg9** [comment]
The `steinmetz` package was written in order to implement a representation of complex numbers that's common in engineering fields, so I guess it would be good to allow using it with `siunitx`. 

I'm not sure, however, about how to integrate it with `siunitx`, because the single command `\phase` actually only typesets the measure of the angle.

**Comment by josephwright** [comment]
Would you say Steinmetz notation is a form of polar output, or an entirely independent format? Working out where the right options live.

**Comment by Rmano** [comment]
I would say that, basically, that is a form of polar output, yes, with or without a unit. It's quite common to write  "I = 30∠30° mA", or also "I = 30 ∠π/6 mA", etc. etc. It's a bit complex here, because you can have a quantity with two different units for the main value and for the angle...

**Comment by eg9** [comment]
@Rmano Would you please add a few printed examples?

**Comment by Rmano** [comment]
I'll try to see if I can find some. We use here quite extensively, but being my field electronics, not electricity, I tend not to use that notation... If I find something I'll post it here.

**Comment by Rmano** [comment]
I checked with an electric engineering / EMC expert here, and he sent me this (here the unit is `p.u.` which is a bit a no-unit..). He told me that he will try to check for papers with that notation, that seems "natural" to him...

![image](https://github.com/user-attachments/assets/7aecfd85-1bc9-4d0f-8e9e-331797dc386b)

From

![image](https://github.com/user-attachments/assets/50d19e04-1204-4131-a992-246c39897070)

**Comment by Rmano** [comment]
This is better

![image](https://github.com/user-attachments/assets/ed3bdf38-a5a5-4f63-a610-1a6acb7df915)

(Power System Analysis, by Hadi Saadat)

**Comment by josephwright** [comment]
Suggestion: `complex-phase-command` which is normally empty but can be `\phase` or whatever to adjust the formatting - thoughts?

**Comment by josephwright** [comment]
@eg9  Thoughts ^^^
