### ISSUE TITLE
table-format setting may cause "Overfull \hbox" since LaTeX 2024-06-01

### ISSUE THREAD

**Issue by muzimuzhi** [josephwright/siunitx#735]
Caught from `tabularray`'s regression test, see [this job run](https://github.com/lvjr/tabularray/actions/runs/9501508385/job/26187191270).

When a cell content has more digits than that specified in `table-format` (hence it's wider than permitted), beforehand no message is raised. Since LaTeX 2024-06-01 an "Overfull \hbox" is raised. I don't know if this difference is expected.

```tex
% \RequirePackage[2023-11-01]{latexrelease}
\documentclass{article}
\usepackage{siunitx}

\begin{document}

\begin{tabular}{|S[table-format=2.1]|}
  33.11
\end{tabular}

\end{document}
```
log
```
Overfull \hbox (5.00002pt too wide) detected at line 9
```

**Comment by muzimuzhi** [comment]
This is also caught by the test suite of `siunitx` itself: https://github.com/josephwright/siunitx/actions/runs/9507844311/job/26208088716.

**Comment by josephwright** [comment]
I'm happy we get a warning here: I never got round to making sure there was one. So I'll simply adjust the tests (but there is something else to check on first).

**Comment by muzimuzhi** [comment]
Surprisingly, now my initial example won't trigger "Overfull \hbox" any more, neither does the `library-003.tex` test in tabularray's repository.

But those "Overfull \hbox" messages added in https://github.com/josephwright/siunitx/commit/b25ee71439c185bc82cba09671714604912e5dab for  `table-emulation.lvt` test in this repository persist.

I tried with format built on LaTeX 2024-06-01, "Overfull \hbox" didn't come back.

**Comment by josephwright** [comment]
@muzimuzhi  It's changes in `array` I think (I didn't trace but I know Frank has tightened up as part of the tagging work)
