### ISSUE TITLE
Add documentation for `separate-uncertainty` option

### ISSUE THREAD

**Issue by zyoshoka** [josephwright/siunitx#739]
There is documentation for the `separate-uncertainty-units`, but not for the `separate-uncertainty` option, so it would be nice to have.

**Comment by josephwright** [comment]
`separate-uncertainty` was the name in v2; in v3 it's `uncertainty-mode = separate`

**Comment by zyoshoka** [comment]
Oh, I didn't realize the `separate-uncertainty` option was deprecated. The `separate-uncertainty` option is used in several places in the documentation, so it might be a good idea to replace them with `uncertainty-mode = separate`.
