### ISSUE TITLE
Asymmetric uncertainties in \qty

### ISSUE THREAD

**Issue by Hugo-Leung** [josephwright/siunitx#754]
I could not get the following code to compile

```
\documentclass{article}
\usepackage{siunitx}
\begin{document}
\qty{12.10(1:2)(3)}{\meter}
\end{document}
```

It can compile if I am using `\num{12.10(1:2)(3)}`, or `\qty{12.10(1)(2:3)}`. But it get stuck if I have an asymmetric uncertainties in the first brackets in `\qty`.

**Comment by josephwright** [comment]
OK, I see the issue here: for quantities, we need to split the formatted number up into parts, and that's going wrong due to the way that multiple uncertainties interact. I just need to think a little about how best to mark these things up internally, then I can make a change.
