### ISSUE TITLE
Changing output-complex-root turns to italic

### ISSUE THREAD

**Issue by csrabak** [josephwright/siunitx#762]
As per present manual, if the `output-complex-root` is changed, even to the default "i", instead of keeping the `\mathrm` format, it changes to _italic_. 

Is there a means of put a "j" and have it upright, perhaps `[output-complex-root = \mathrm{j}]` ?

**Comment by josephwright** [comment]
Er, yes, you get exactly the literal set here, so for upright-j you need `\mathrm{j}`: the standard value of `\mathrm{i}` hopefully shows the pattern.

**Comment by csrabak** [comment]
OK, I would not expect, but I understand the mechanics so OK.
I was educated that 'e', the imaginary 'i' or 'j', where always "upright" exactly to avoid confusion to with variables which are expected to be typeset in italic, as a rule.

Thanks.

**Comment by josephwright** [comment]
> OK, I would not expect, but I understand the mechanics so OK. I was educated that 'e', the imaginary 'i' or 'j', where always "upright" exactly to avoid confusion to with variables which are expected to be typeset in italic, as a rule.

There are different traditions here: pure mathematicians tend to use italic, physicists and engineers upright. There is no 'right' answer here, so `siunitx` simply users math mode and expects the user to make their own decision.
