### ISSUE TITLE
Have \complexnum in polar option use steinmetz package \phase in lieu of \angle

### ISSUE THREAD

**Issue by csrabak** [josephwright/siunitx#763]
Can we have a mean of changing `complex-symbol-angle` to the steinmetz package `\phase` macro?

**Comment by josephwright** [comment]
https://github.com/josephwright/siunitx/issues/732

**Comment by csrabak** [comment]
OK, since I got in the discussion later, and the decision for any change is not planned not "will not implement", I want to just advocate a single matter.

Since the SI package already has the polar form which is the so called Kennely or Steinmetz notation for complex numbers, the LaTeX steimetz package only make the angle symbol more capable of enclosing larger 'text', which in the sinunitx package means that a number with, say, like 29.7° would be all above the line of the angle symbol, wheres the default is just  a character.

The analogy I can draw here is the use of the square root symbol. The character is √, but in LaTeX when we typeset \sqrt{a² + b²} the whole sum gets under the upper bar of the square root symbol.

**Comment by josephwright** [comment]
@csrabak  It is implemented in v3.4, it's just that `\angle` is a _symbol_ so doesn't take an argument, so there is a new key setting - `complex-phase-command`. As shown in the manual
```latex
\complexqty[complex-phase-command = \phase]{1:1}{\ohm}
```
is what you want.

**Comment by csrabak** [comment]
Yes, it works like a charm!

We're simplifying our LaTeX sources with this implementation!

Thank you for the mod. 

When you have to meddle at it, please consider having the Portuguese and Brazilian locales added to the ones already available as per subsection 4.13 of present manual.

Again thanks.
