### ISSUE TITLE
\version{} cmd undefined in siunitx.dtx causes build failure  in 3.4.0

### ISSUE THREAD

**Issue by balducci** [josephwright/siunitx#764]
hello

during `latex siunitx.dtx`  while building `3.4.0` I get:
```
    ! Undefined control sequence.
    l.110 % Allow rollback to version~\version
                                              {2}: if we need to, version~\versi...

    ? No pages of output.
    Transcript written on siunitx.log.
```
AFAICS,  the `\version{}` command is defined in `siunitx.tex`, but not in `siunitx.dtx`.
Indeed, adding it in `siunitx.dtx` as per:
```
diff -c ./siunitx.dtx.ADD_VERSION_CMD ./siunitx.dtx
*** ./siunitx.dtx.ADD_VERSION_CMD	Thu Dec 26 17:35:30 2024
--- ./siunitx.dtx	Thu Dec 26 17:35:30 2024
***************
*** 28,33 ****
--- 28,34 ----
  \documentclass{l3doc}
  % Additional commands needed in this source
  \ProvideDocumentCommand\email{m}{\href{mailto:#1}{\nolinkurl{#1}}}
+ \NewDocumentCommand\version{m}{\ensuremath{#1}}
  % The next line is needed so that \GetFileInfo will be able to pick up
  % version data
  \usepackage{siunitx}
```
fixes things for me.

thanks for your valuable work

ciao
gabriele

**Comment by josephwright** [comment]
Aside: you shouldn't be directly typesetting `siunitx.dtx` as that would over-write the user docs created from `siunitx.tex`.

**Comment by balducci** [comment]
> Aside: you shouldn't be directly typesetting `siunitx.dtx` as that would over-write the user docs created from `siunitx.tex`.

Indeed:
```
...
latex foo.ins
latex foo.dtx
...
```
is what I have always done (and has always worked fine also with siunitx) in my scripts to generate  `.sty` files and docs from "source" latex packages

I see that in the downloaded .../macros/latex/contrib/siunitx/* files there is already a `siunitx.pdf` file, but shouldn't it be regenerated by running `latex siunitx.dtx`?

I'm probably missing something here ...?
-g

**Comment by josephwright** [comment]
> > Aside: you shouldn't be directly typesetting `siunitx.dtx` as that would over-write the user docs created from `siunitx.tex`.
> 
> Indeed:
> 
> ```
> ...
> latex foo.ins
> latex foo.dtx
> ...
> ```
> 
> is what I have always done (and has always worked fine also with siunitx) in my scripts to generate `.sty` files and docs from "source" latex packages

Why are you generating yourself?

> I see that in the downloaded .../macros/latex/contrib/siunitx/* files there is already a `siunitx.pdf` file, but shouldn't it be regenerated by running `latex siunitx.dtx`?

No, because it's the user docs generated from `siunitx.tex`.

> I'm probably missing something here ...? -g

The `siunitx` bundle has more than one source file and more than one output PDF (at some stage I may go from the current 2 to 3 PDFs), so there is more to things than running LaTeX on the `.dtx`. (BTW, I've shifted to using LuaTeX, so you'll want `lualatex ...`.)

**Comment by balducci** [comment]
thanks for spending the time to reply and for clarification

apologies for the noise

ciao

-g
